- docs/README.md
The name "Rust" should not be in all caps.
> Fix Rust typo in readme

- build/NuSpecs/ProjectReunionMetaPackage.nuspec
- build/NuSpecs/build-nupkg.ps1
Added a ProjectReunionMetaPackage.nuspec file and added build steps to build it and publish it to artifacts/drop.  For now it has a single reference for the Win2d.uwp Nuget package (version 1.25.0).  
Tested by taking the Win2d "simple sample", removing the Win2D reference, downloading the build artifact, setting up a nuget package source to a local directory and then installing and referencing the Microsoft.ProjectReunion.MetaPackage nuget package and building the sample.  
Once we publish the ProjectReunion nuget package (the one with actual contents) we can reference it but publishing has not occurred yet.
> User/eho makai/reunion metapackage

- dev/MRTCore/TestApps/winui_desktop_packaged_app/winui_desktop_packaged_app/MainWindow.xaml.cs
- dev/MRTCore/TestApps/winui_desktop_packaged_app_cpp/winui_desktop_packaged_app_cpp/App.cpp
- dev/MRTCore/TestApps/winui_desktop_packaged_app_cpp/winui_desktop_packaged_app_cpp/MainWindow.cpp
- dev/MRTCore/TestApps/winui_desktop_packaged_app_cpp/winui_desktop_packaged_app_cpp/MainWindow.h
- dev/MRTCore/TestApps/winui_desktop_packaged_app_cpp/winui_desktop_packaged_app_cpp/MainWindow.idl
- dev/MRTCore/TestApps/winui_desktop_packaged_app_cpp/winui_desktop_packaged_app_cpp/packages.config
- dev/MRTCore/TestApps/winui_desktop_packaged_app_cpp/winui_desktop_packaged_app_cpp/winui_desktop_packaged_app_cpp.vcxproj
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.idl
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/ResourceMap.cpp
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/ResourceMap.h
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/packages.config
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/UnitTest.cs
Made the `ResourceContext` parameter be the second parameter in the overloads, not the first.
Note: the unit tests run, but for various reasons I can't verify that the two test apps are working correctly. (VS refuses to open the managed project, and the native project needs the NuGet feed to be available and I can't figure out how to build a local version).
> Changed ResourceMap API to follow WinRT conventions.

- nuget.config
Add ProjectReunion-Dependencies to nuget.config (which enables pushing dependent nuget pkgs, e.g. taef.redist.wlk, needed by MRTCore).
> nuget.config add for projectreunion-dependencies

- build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
- build/ProjectReunion-release.yml
Push the Microsoft.ProjectReunion.*.nupkg to the private nuget feed under the artifacts feed 'ProjectReunion/Microsoft.ProjectReunion.nuget.internal'.  This is for use by WInUI3 for their November preview release to embed in their package.  After this release WinUI will be in the Project Reunion package and this internal nuget drop will no longer be necessary.  
This also pushes the Project Reunion metapackage but this will be ignored.
> User/eho makai/publish nuget private feed

- build/Helix/RunTestsInHelix.proj
- build/ProjectReunion-CI.yml
Summary:  this PR removes 19h1 helix queue from the test project.
Details:  I originally set up the helix tests to run on two different queues rs5 and 19h1 (just for the sake of ensuring we can run on multiple queues)  Talking with the helix team last week it sounded like the 19h1 queue was still having issues with scaling. This can cause some of our runs to take over an hour while the rs5 test finishes fast and is stuck waiting for 19h1 to get over whatever scaling issue they are facing.  The quick fix here is to remove 19h1 for now since it's just adding extra iteration time for our devs.  We can look at adding it back when we start looking at release gating and what candidates we need testing on to ensure a stable release.
Watch out for: Reducing the number of tests might cause some …
> Remove 19h1 helix queue from test project

- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
While loading x86 build of Microsoft.ApplicationModel.Resources.Projection.dll from a .net console app, a System.BadImageFormatException is thrown. Theoretically the projection dll should be architecture neutral. But to avoid this issue, add an explicit PlatformTarget.
> Add PlatformTarget for MRT projection project

- build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
- build/ProjectReunion-release.yml
- dev/MRTCore/azure-pipelines.yml
Summary:
Mostly a cosmetic change.  We in are in the process of coming up with real names for the different types of nuget packages, but until then, "full" is a better temporary name than "fat".
This changes the yml files, directory structure, and artifact name to reflect that.
> Rename nuget package to "full"

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Change Description
Add SkipNonexistentTargets param to MSBuild task that calls the GetMrtPackagingOutputs target for referenced projects.
Issue
The targets file recursively calls the GetMrtPackagingOutputs target on referenced projects (this is done to grab all resources, PRI files, etc., from said projects to incorporate into the PRI file that's being generated in the referencing project). The problem is that the GetMrtPackagingOutputs target doesn't exist in projects that don't use MRTCore.
Solution
To address the issue, simply add SkipNonexistentTargets="true" to the MSBuild task invocation!
How verified
App attached to bug now builds successfully.
> Add SkipNonexistentTargets param to MSBuild task that calls the GetMrtPackagingOutputs target for referenced projects.

- dev/MRTCore/azure-pipelines.yml
Package ES pool has huge backlogs. PublishMRT job no longer does any signing, thus no need to use Package ES.
> Move PublishMRT off Packge ES

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Copy paste of code comment:
The referenced project may not be using MRTCore. In that case, `GetMrtPackagingOutputs` won't be defined. However, if the project is of type UWP, it'll have `GetPackagingOutputs` defined. So, try calling `GetPackagingOutputs`. If it does not exist, we simply no-op - see the `SkipNonexistentTargets` parameter below.
Note: we renamed `GetPackagingOutputs` to `GetMrtPackagingOutputs` in MRTCore because .NET 5 calling `GetPackagingOutputs` resulted in issues. Us calling `GetPackagingOutputs` in a .NET 5 project though should be fine.
How verified:
Resources from the core project of the Adobe app now show up in the top-level resources.pri.
> [MRTCore] Call GetPackagingOutputs on referenced UWP projects.

- build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
This change copies the full package targets into the full package that will be pushed to the internal repo. The main thing needed here is the references to the project reunion winmds in the targets file.
> Copy the full package target files into the full package

- build/NuSpecs/ProjectReunion-Nuget-Native.targets
This is a change to temporarily remove the CopyLocals for the Project Reunion Foundation binaries. This package is only ever used as a framework package and so these do not need to be here for the initial bring up of the pipelines. In the future we will have a more robust programmatic solution.
> Remove the Project Reunion Foundation CopyLocals for binaries

- build/NuSpecs/ProjectReunion-Nuget-Native.targets
This change tell VS to not worry about the fact that the implementation dll is not in the final package.
> Tell VS not to look for implementation dll in final package

- build/ProjectReunion-BuildFoundation.yml
This adds a checkbox on the pipeline run widget that you can check if you want to do ReleaseSigning. It's easier than typing out "true" to a variable. Just quality of life changes.
> Quality of Life changes on ReleaseSigning controls

- dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.WinRt.props
Description:
The hintpath in the Microsoft.ApplicationModel.Resources.WinRT.props file did not match the path that the WinMD's location in the metapackage.  This change fixes that.
> Update MRTCore.WinRT.props hintpath value to point to the WinMD

- nuget.config
Add `<disabledPackageSources>`
Per latest guidance "How to Securely Configure Package Source Files" `nuget.config` should have `<packageSources>` and `<disabledPackageSources>` and start both with `<clear />`. Current `nuget.config` had no `<disabledPackageSources>`.
> Add <disabledPackageSources>

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
How verified:
Using a win32 app created using the Windows Desktop Wizard and a MRTCore NuGet package with the targets file modified.
> Add PRI gen support in win32 apps (tested with string and image resources).

- README.md
This change removes a stale status badge for a github workflow that's no longer in use. The project is currently being built using azure pipelines in a private repository. In the future I'll investigate how to provide better live build status, but I'm removing the old badge so that people don't get the wrong idea and thing the project is sitting unattended in a broken state.
> Removing stale status badge from readme

- build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
- build/NuSpecs/AppxManifest.xml
Adding an Appx Manifest that was previously being hardcoded into the PR Framework Package. Now it will be obtained from the Project Reunion Foundation Transport package.
> add appx manifest to foundation transport package

- .github/workflows/build.yml
- build/AzurePipelinesTemplates/ProjectReunion-NugetReleaseTest-Job.yml
- build/AzurePipelinesTemplates/ProjectReunion-WACKTests-Job.yml
- build/NuSpecs/build-nupkg.ps1
- build/ProjectReunion-BuildFoundation.yml
- build/ProjectReunion-CI.yml
- dev/MRTCore/azure-pipelines.yml
There was a decision to not support ARM and some of the packages we are using will not have an ARM version. 
Don't want to do have to do something like
#ifndef arm32
in our code.
> Stop building ARM for ProjectReunion Foundation

- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Helper.cpp
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/packages.config
Update MRTCore to use the newest UDK
Change the caller because the header and the api name changed
> Update MRTCore to use the newest UDK

- docs/roadmap.md
Unfortunately due to some work taking slightly longer than planned, the unpackaged support that was previously planned won't be coming in 0.5 and has been pushed back to 0.8. The work to complete unpackaged support just *barely* missed the dates to have it completed!
> Update roadmap (unpackaged apps to 0.8)

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Packaged win32 app's resources.pri didn't merge the PRI of the win32 app because that PRI was also called resources.pri.
The name of PRIs generated in win32 projects was recently changed to resources.pri:
[Changes to generate a Microsoft.ProjectReunion.Foundation NuGet package that supports MRTCore on win32. by rohanp-msft · Pull Request #394 · microsoft/ProjectReunion (github.com)](https://github.com/microsoft/ProjectReunion/pull/394/files)
Microsoft.ApplicationModel.Resources.PriGen.targets:
```
<ProjectPriFileName Condition="'$(ApplicationType)' == '' and '$(WindowsAppContainer)' == 'false' and '$(ProjectPriFileName)' == ''">resources.pri</ProjectPriFileName>
```
When that mod is removed, the PRI file is named after the project, and the merge happens as expected.
> Revert naming of win32 apps' PRI to the project name.

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Cherry pick commit 8f2e84182e1e: https://github.com/microsoft/ProjectReunion/pull/526
> [Cherry-pick] Revert naming of win32 apps' PRI to the project name.

- dev/VSIX/Directory.Build.props
- dev/VSIX/Extension/ProjectReunion.Extension.csproj
Main project file would occasionally fail to restore, VsToolsPath would occasionally not be set, causing VSIX targets to not execute.  Fix was to add fallback, as template project files do.
Template project files would fail to build, requiring 'win' RuntimeIdentifier.  Fix for this was to add it to directory.build.props, and not the template projects, as that breaks template instantation.
> address build/restore issues causing vsix pipeline failures

- build/ProjectReunion-Create-VSIX.yml
- dev/VSIX/Directory.Build.props
- dev/VSIX/packages.config
A few days ago I created a PR that created a pipeline to produce a signed VSIX. Said PR was merged into main and then cherrypicked ( #537  ) into release/project-reunion-2103. There, we saw that there were some extra things that were not needed, like an installation of VSSDK and we fixed them there. So now I am Cherry picking those changes into main as well :)
> Cherry-Pick: create VSIX pipeline fixes (#537)

- docs/Coding-Guidelines.md
Added best practice about catching C++ exceptions and HRESULTS per @kennykerr from [this thread](https://github.com/microsoft/ProjectReunion/pull/508#discussion_r586430665)
> Add note about catching exceptions in C++

- dev/VSIX/Extension/ProjectReunion.Extension.csproj
- dev/VSIX/Extension/source.extension.vsixmanifest
- dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.vstemplate
- dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/App.xaml.cs
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/App.cpp
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WinUI.Desktop.CppWinRT.WapProj.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.vstemplate
- dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/WinUI.UWP.Cs.ClassLibrary.vstemplate
- dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/WinUI.UWP.Cs.RuntimeComponent.vstemplate
- dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/WinUI.UWP.CppWinRT.BlankApp.vstemplate
UWP templates are removed, as there are active runtime restrictions preventing their functionality
> GA tweaks - VS 16.9 prereq, WinUI 3 rename, remove UWP templates, Suspending event

- dev/VSIX/Extension/ProjectReunion.Extension.csproj
- dev/VSIX/Extension/source.extension.vsixmanifest
- dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.vstemplate
- dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/App.xaml.cs
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/App.cpp
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WinUI.Desktop.CppWinRT.WapProj.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.vstemplate
- dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/WinUI.UWP.Cs.ClassLibrary.vstemplate
- dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/WinUI.UWP.Cs.RuntimeComponent.vstemplate
- dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/WinUI.UWP.CppWinRT.BlankApp.vstemplate
* GA tweaks - VS 16.9 prereq, WinUI 3 rename, UWP templates unsupported
* remove UWP templates - not supported in release
* remove experimental Suspending event
> cherry pick: GA tweaks - VS 16.9 prereq, WinUI 3 rename, remove UWP templates, Suspending event (#591)

- dev/DynamicDependency/MsixDynamicDependency.cpp
- dev/ProjectReunion_BootstrapDLL/MddBootstrap.cpp
- dev/ProjectReunion_BootstrapDLL/framework.h
Adding a trap if DynDep|Bootstrap APIs are called from an Elevated process to prevent accidental misuse, false bug reports and bloodshed and tears all around.
This block will be removed when we address Issue #567 https://github.com/microsoft/ProjectReunion/issues/567
> Add temporary trap to block calling DynamicDependencies (or Bootstrap) APIs if Elevated

- dev/DynamicDependency/PackageGraphManager.cpp
- dev/ProjectReunion_DLL/dllmain.cpp
- test/DynamicDependency/Test_Win32/TestMddBootstrap.cpp
- test/DynamicDependency/Test_Win32/pch.h
DynamicDependencies only supports not-packaged processes but the Detours hooks were always wired up. Fixed to skip skip that in a packaged process so Microsoft.ProjectReunion.dll can be used in packaged processes for other (not DynDep) features.
Also beefed up parameter validation in the Detour'd GetCurrentPackageInfo[2] to match the OS APIs' parameter validation.
Expanded test cases.
NOTE: Tests verifying package'd process behavior is blocked awaiting [Rewrite DynamicDependencies tests using TAEF #559](https://github.com/microsoft/ProjectReunion/issues/559)
> DynamicDependencies: Only Detour functions in not-packaged processes

- dev/VSIX/Directory.Build.props
- dev/VSIX/Extension/ProjectReunion.Extension.csproj
still investigating why nuget restores are behaving inconsistently.  when they do fail, the vsix build should also fail.
> Remove unnecessary Pkg* defines and avoid bad vsix builds when nuget restore fails 

- ProjectReunion.sln
- dev/ChangeTracker/ChangeTracker.vcxitems
- dev/ChangeTracker/EnvironmentVariableChangeTracker.cpp
- dev/ChangeTracker/EnvironmentVariableChangeTracker.h
- dev/ChangeTracker/IChangeTracker.h
- dev/Microsoft.Process.Environment/EnvironmentManager.cpp
- dev/Microsoft.Process.Environment/EnvironmentManager.h
- dev/ProjectReunion_DLL/ProjectReunion_DLL.vcxproj
- test/EnvironmentManagerTests/ChangeTrackerHelper.h
- test/EnvironmentManagerTests/EnvironmentManagerCentennialTests.cpp
- test/EnvironmentManagerTests/EnvironmentManagerCentennialTests.h
- test/EnvironmentManagerTests/EnvironmentManagerTests.vcxproj
- test/EnvironmentManagerTests/EnvironmentManagerTests.vcxproj.filters
- test/EnvironmentManagerTests/EnvironmentManagerUWPTests.cpp
- test/EnvironmentManagerTests/EnvironmentManagerUWPTests.h
- test/EnvironmentManagerTests/EnvironmentManagerWin32Tests.cpp
- test/EnvironmentManagerTests/EnvironmentManagerWin32Tests.h
- test/EnvironmentManagerTests/EnvironmentVariableHelper.h
- test/EnvironmentManagerTests/TestCommon.h
- test/EnvironmentManagerTests/TestSetupAndTeardownHelper.h
This change includes the implementation and testing of
1. GetEnvironmentVariable
2. SetEnvironmentVariable
3. ChangeTracking
The Change Tracker allows a centennial app to track any environment variable changes in the user and machine scope.  These changes will be removed when the app is uninstalled.
A non-Centennial app can still use this API to set an environment variable however.
> Adding the ability to get an environment variable and set an environment variable

- README.md
- docs/roadmap.md
Updating the readme and roadmap for the 0.5 release. Just simply changing "try it" to "use it" and removing the date from 0.5 on the roadmap
> Readme updates for 0.5 release

- specs/spec_template.md
This change proposes updates to the API spec template based on experience from existing specs we've been writing. This includes some formatting updates to better align with docs.microsoft.com, and some links to existing examples that can be followed.
> API spec template format updates

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Remove some unused Appx* properties in Microsoft.ApplicationModel.Resources.PriGen.targets.
Microsoft.ApplicationModel.Resources.PriGen.targets was created from Microsoft.AppxPackage.targets where a bunch of appx generation MSBuild script code was removed (Microsoft.AppxPackage.targets does more than just PRI generation, which is all that we want Microsoft.ApplicationModel.Resources.PriGen.targets to do, as the name suggests). At that point though, not all non-PRI gen related MSBuild script code was removed. I'll now try to remove it over several rounds. This is round 1.
Used the MRTCore CPP sample app. Got rid of build outputs. Replaced the prigen targets file in the nuget package install with the one in this change. Built and ran the app.
> Clean up of Microsoft.ApplicationModel.Resources.PriGen.targets (round 1)

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
We used to rely on Microsoft.WinUI.AppX.targets to set SDKVersion/SDKIdentifier for .net app. Replicate the logic here in case WinUI is not wanted, e.g WPF app.
> Set SDKVersion

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Remove some more unused Appx* properties and items in Microsoft.ApplicationModel.Resources.PriGen.targets.
Microsoft.ApplicationModel.Resources.PriGen.targets was created from Microsoft.AppxPackage.targets where a bunch of appx generation MSBuild script code was removed (Microsoft.AppxPackage.targets does more than just PRI generation, which is all that we want Microsoft.ApplicationModel.Resources.PriGen.targets to do, as the name suggests). At that point though, not all non-PRI gen related MSBuild script code was removed. I'll now try to remove it over several rounds. This is round 2.
Round 1: https://github.com/microsoft/ProjectReunion/pull/664
Used the MRTCore CPP sample app. Got rid of build outputs. Replaced the prigen targets file in the nuget package install with …
> Clean up of Microsoft.ApplicationModel.Resources.PriGen.targets (round 2)

- dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.WinRt.props
- dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.props
- dev/MRTCore/publish-mrt.yml
As MRTCore is no longer part of WinUI package, there is no need to hide the M.AM.R.winmd in a subfolder.
> remove subfolder for Microsoft.ApplicationModel.Resources.winmd

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Remove some unused targets and associated properties, as well as two unused items.
Microsoft.ApplicationModel.Resources.PriGen.targets was created from Microsoft.AppxPackage.targets where a bunch of appx generation MSBuild script code was removed (Microsoft.AppxPackage.targets does more than just PRI generation, which is all that we want Microsoft.ApplicationModel.Resources.PriGen.targets to do, as the name suggests). At that point though, not all non-PRI gen related MSBuild script code was removed. I'll now try to remove it over several rounds. This is round 3.
With regards to this specific change:
These targets are APPX specific. They were run before _CreateAppxBundlePlatformSpecificArtifacts which was removed in version 0 of Microsoft.ApplicationModel.Resources.PriGen.targets.
Round 1: …
> Clean up of Microsoft.ApplicationModel.Resources.PriGen.targets (round 3)

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
*.NET 6*
Used .NET 6 with MRTCore C# sample (lib and app). App built and ran fine.
Specific .NET version: windowsdesktop-runtime-6.0.0-preview.2.21154.2-win-x86.
Target framework of lib:
`<TargetFramework>net6-windows10.0.18362.0</TargetFramework>`
Target framework of app:
`<TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>`
*.NET 5*
Verified MRTCore C# sample (lib and app) work. For this, no changes were made to the sample app (they are already configured for .NET 5).
> Add PRI generation support for all .NET versions greater than 5.

- dev/MRTCore/build/DownloadDotNetRuntimeInstaller.ps1
- dev/MRTCore/build/versions.props
- dev/MRTCore/global.json
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
We're recommending to users moving up to .NET 5.0.5 which just released (equal to 5.0.202 in VS 16.9.3).  WinUI is making this change, along with cswinrt 1.2.1, so MRTCore should be consistent.
> update to cswinrt 1.2.1 and .NET 5.0.5

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
See the comment by Daniel Plaisted in: #707.
MRTCore C# lib and app under .NET 5 and .NET 6.
> Fix impl of is-greater-than-dot-net-5 version check.

- installer/dev/install.cpp
- installer/dev/project_reunion_definitions.h
Fixes some expected warnings in the installer build, particularly when using the override header with redefinition warnings. The header can get pulled in multiple times in the main build and again by the resource compiler.
Verified with running installer tests without issue.
> Fix Installer Build Warnings

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
This wasn't done in all cases. See the note in this page https://docs.microsoft.com/en-us/windows/apps/project-reunion/mrtcore/mrtcore-overview:
"
Before you can use MRT Core to retrieve strings and images in a WinUI 3 project that uses C#/.NET 5, you must ensure that these resources are configured so that they can be indexed in the resources.pri file. Otherwise, these resources cannot be retrieved by MRT Core.
Strings: Make sure the Build Action property for resources files (.resw) is set to PRIResource. This property is set automatically if you add a new Resources File (.resw) item to your project.
Images: Make sure the Build Action property for image files are set to Content. This property is set automatically if you add an existing image to a folder named Assets in your project.
" …
> In C#/.NET projects, pick up image and resw files for PRI generation.

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
Remove more unused MSBuild code.
Microsoft.ApplicationModel.Resources.PriGen.targets was created from Microsoft.AppxPackage.targets where a bunch of appx generation MSBuild script code was removed (Microsoft.AppxPackage.targets does more than just PRI generation, which is all that we want Microsoft.ApplicationModel.Resources.PriGen.targets to do, as the name suggests). At that point though, not all non-PRI gen related MSBuild script code was removed. I'll now try to remove it over several rounds. This is round 4.
Round 1: #664
Round 2: #696
Round 3: #704 
How verified
Used the MRTCore C# sample app and lib. Got rid of build outputs. Replaced the prigen targets file in the nuget package install with the one in this change. Built and ran the app.
> Clean up of Microsoft.ApplicationModel.Resources.PriGen.targets (round 4)

- build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
- build/NuSpecs/Intellisense/Microsoft.ApplicationModel.Activation.xml
- build/NuSpecs/Intellisense/Microsoft.ApplicationModel.DynamicDependency.xml
- build/publish-mrt.yml
- dev/MRTCore/packaging/Intellisense/Microsoft.ApplicationModel.Resources.Projection.xml
- dev/MRTCore/packaging/Intellisense/Microsoft.ApplicationModel.Resources.xml
With this change, we'll be publishing stubbed out Intellisense xml files into the transport package, and subsequently into the Project Reunion package.
Feature owners still need to fill in the Intellisense documentation, but these changes won't require pipeline changes, simply text changes to the xml file(s).
> Publish stub intellisense files into transport package

- dev/VSIX/Directory.Build.targets
- dev/VSIX/Extension/ProjectReunion.Extension.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WapProjTemplate.wapproj
Cherry pick of #809 into preview/0.8-preview1.
Original description:
> During testing, we discovered some issues with the preview VSIX:
> * Missing project templates if both GA and Preview VSIX were installed side-by-side
> Resolved by appending `.Preview` to TemplateID of all templates in preview VSIX
> * Nuget restore error when creating new C++ projects
> Resolved by ensuring that the Nuget template wizard data was pointing at the correct extension ID to use as a source repository
> * Nuget compatibility error from .wapproj when using VS 16.10 Preview to build a Desktop WinUI app
> The `AssetTargetFallback` property needs to be defined after the definition of the `TargetPlatformVersion` property as the former has a dependency on the latter.
> 
> Additionally, we decided to not set the …
> [Cherry pick] Fixes for Preview VSIX (#809)

- build/NuSpecs/ProjectReunion-Nuget-Native.targets
Symbols moved to other namespaces making this reference obsolete
> Remove obsolete reference to file Microsoft.ProjectReunion.winmd which doesn't exist anymore

- build/NuSpecs/ProjectReunion-Nuget-Native.C.props
- build/NuSpecs/ProjectReunion-Nuget-Native.WinRt.props
- build/NuSpecs/ProjectReunion-Nuget-Native.targets
Correct some Nuspec files for VS C++ consumption for unpackaged apps
Correct Nuget content determined via VS simple C++ project with a dependency on Project Reunion followed by repeated hacking the NuGet's native build files until the desired outcome, then porting the local changes to the checked in Nuspecs. Fun fun.
> Update Nuspecs for unpackaged consumption

- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/custom.props
The file was used for building in Package ES lab. We no longer use Package ES build.
> Remove custom.props

- Directory.Build.props
- dev/ProjectReunion_BootstrapDLL/MddBootstrap.cpp
MddBootstrapInitialize() had a PRfwk package name mismatch (looking for "Microsoft.ProjectReunion.Framework" instead of "Microsoft.ProjectReunion.<major>.<minor>[-tag]"). Corrected to look for the right PRfwk package name (now and into the future with different MajorMinor and/or Tag). As a happy perk tests are also unaffected.
Verified tests pass AND the Reunion nuget pass as expected with this fix to Microsoft.ProjectReunion.dll!
Also changed Directory.Build.props to not produce unnecessary noise during inner-loop builds.
> Update Bootstrap dll to match PRfwk

- build/Helix/ConvertWttLogToXUnit.ps1
- build/build-mrt.yml
- dev/MRTCore/mrt/Core/unittests/MrmTests.cpp
- dev/MRTCore/mrt/Core/unittests/UnitTest.vcxproj
- dev/MRTCore/mrt/Core/unittests/packages.config
This PR converts the MRT Core Unit Tests from the MSTest framework to TAEF.
This will enable running the Unit Tests inside Helix in the future in another PR.
There are 4 different test suites for MRT Core currently:
- BaseUnitTests 
- Already using TAEF.
- This already runs in Helix but the test results aren't reported in ADO.
- UnitTests
- This PR converts this test from MSTest to TAEF, and runs this test on the build machine.
- ManagedTests
- Uses MSTest/vstest.console.exe to run.
- Will investigate converting this to TAEF in a future PR.
- UnpackagedTests
- Already using TAEF.
- Doesn't yet run in the CI pipeline. (I plan to try and enable this in a future PR).
I had to use `wcscmp` for comparing strings in the tests, as otherwise the `VERIFY_` macro would get confused and try to …
> Convert MRT Core UnitTests from MSTest to TAEF

- dev/DynamicDependency/WinRTInprocModule.h
- dev/DynamicDependency/WinRTPackage.cpp
- dev/DynamicDependency/WinRTPackage.h
- test/DynamicDependency/Test_WinRT/Test_WinRT.cpp
- test/DynamicDependency/Test_WinRT/Test_WinRT.h
- test/DynamicDependency/data/Microsoft.ProjectReunion.Framework/appxmanifest.xml
2 bugs in AppxManifest-based UndockedRegFreeWinRT support we unnoticed due to a gap in test coverage
* 2+ `<Extension Category='windows.activatableClass.inProcessServer'>` in a manifest
* 2+ inprocservers with the same Path
Code updated to handle these cases as expected.
The PRfwk test package (`test\DynamicDependency\data\Microsoft.ProjectReunion.Framework`) was updated to ensure coverage of these scenarios
Added new WinRT_RoGetActivationFactory_* test cases to verify the fix. Tests pass now as expected
> DynamicDependencies bug in AppxManifest'd winrt inprocserver handling

- build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
- build/NuSpecs/Microsoft.ProjectReunion.Bootstrap.targets
- build/NuSpecs/Microsoft.ProjectReunion.Foundation.targets
This file was not being bin placed but needs to be.
Used a test app.
> Copy Microsoft.ProjectReunion.Bootstrap.dll to $(OutDir) for non-native projects.

- dev/DynamicDependency/PackageDependency.cpp
- tools/DevCheck.ps1
Also fixed cert access in DevCheck.ps1 causing false errors
> DynamicDependencies: fix PCWSTR[] access

- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/ProjectTemplate.vcxproj
We will use this property to identify WinUI project.
> Add UseWinUI property

- dev/MRTCore/mrt/Core/src/MRM.vcxproj
- dev/MRTCore/mrt/mrm/mrmex/mrmex.vcxproj
- dev/MRTCore/mrt/mrm/mrmmin/mrmmin.vcxproj
MRT Core doesn't use RTTI, but the `*.vcxproj` files that are used to build `MRM.dll` have this enabled (it is implicitly set by default).
This change disables RTTI for `MRM.dll` which reduces the overall binary file size (for x64 Release) by **37 KB**.
| File    | Size Before     | Size After     |
|---------|----------------:|---------------:|
| MRM.dll | 348,672 | 310,784 |
**Delta** = **37,888 bytes (37 KB)**
SizeBench delta for MRM.dll
| Name    | Size on disk Diff | Size in memory Diff | Size in memory (including section padding) Diff |
| ------- | ----------------- | ------------------- | ----------------------------------------------- |
| \_RDATA | 0                 | 0                   | 0                                               |
| .rsrc   | 0                 | 0 …
> Reduce MRM.dll binary size by 37 KB by disabling RTTI.

- dev/DynamicDependencyDataStore/DynamicDependency.DataStore.ProxyStub/DynamicDependency.DataStore.ProxyStub.vcxproj
- dev/DynamicDependencyDataStore/DynamicDependency.DataStore/DynamicDependency.DataStore.vcxproj
- dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.ProxyStub/DynamicDependencyLifetimeManager.ProxyStub.vcxproj
- dev/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager/DynamicDependencyLifetimeManager.vcxproj
- dev/ProjectReunion_BootstrapDLL/ProjectReunion_BootstrapDLL.vcxproj
- dev/ProjectReunion_DLL/ProjectReunion_DLL.vcxproj
Update Microsoft.ProjectReunion.dll, Microsoft.ProjectReunion.Bootstrap.dll, DynamicDependency DataStore and LifetimeManager to use the [Universal CRT](https://docs.microsoft.com/cpp/porting/upgrade-your-code-to-the-universal-crt?view=msvc-160) (like MRTCore's been doing) and VS' static CRT. This removes the dependency on the VS CRT redistributable at negible cost (see below).
Static analysis before/after using `LINK /DUMP /IMPORTS`, linker options `/MAP /VERBOSE` and `SizeBench` confirms the trivial size delta.
Disk size of x64 Binaries
|File | Size Before | Size After | Delta|
|---|---:|---:|---:|
|DynamicDependency.DataStore.exe                |  58,368 |  81,408 |  23,040 |
|DynamicDependency.DataStore.ProxyStub.dll      |  13,312 |  24,064 |  10,752 | …
> Use the Universal C Runtime

- build/build-mrt.yml
- dev/MRTCore/mrt/Core/src/MRM.cpp
also removed custom build configurations in mrt build task.
> Replace custom path handling in MRT

- dev/PowerNotifications/ClosedSourceMock.cpp
- dev/PowerNotifications/PowerNotifications.cpp
- dev/PowerNotifications/PowerNotifications.h
- dev/PowerNotifications/PowerNotifications.idl
- dev/PowerNotifications/PowerNotificationsPal.h
- test/PowerNotificationsTests/PowerTests.cpp
- Amending PowerMode Functions to use 
[PowerRegisterForEffectivePowerModeNotifications()](https://docs.microsoft.com/en-us/windows/win32/api/powersetting/nf-powersetting-powerregisterforeffectivepowermodenotifications)
- Removed SystemAwayStatus code
> Amending PowerMode Functions

- dev/ChangeTracker/ChangeTracker.vcxitems
- dev/ChangeTracker/EnvironmentVariableChangeTracker.cpp
- dev/ChangeTracker/EnvironmentVariableChangeTracker.h
- dev/ChangeTracker/IChangeTracker.h
- dev/ChangeTracker/PathChangeTracker.cpp
- dev/ChangeTracker/PathChangeTracker.h
- dev/ChangeTracker/PathExtChangeTracker.cpp
- dev/ChangeTracker/PathExtChangeTracker.h
- dev/Microsoft.Process.Environment/EnvironmentManager.cpp
- dev/Microsoft.Process.Environment/EnvironmentManager.h
- dev/Microsoft.Process.Environment/EnvironmentManager.idl
- test/EnvironmentManagerTests/ChangeTrackerHelper.h
- test/EnvironmentManagerTests/EnvironmentManagerCentennialTests.cpp
- test/EnvironmentManagerTests/EnvironmentManagerCentennialTests.h
- test/EnvironmentManagerTests/EnvironmentManagerUWPTests.cpp
- test/EnvironmentManagerTests/EnvironmentManagerUWPTests.h
- test/EnvironmentManagerTests/EnvironmentManagerWin32Tests.cpp
- test/EnvironmentManagerTests/EnvironmentManagerWin32Tests.h
- test/EnvironmentManagerTests/EnvironmentVariableHelper.h
- test/EnvironmentManagerTests/TestCommon.h
- test/EnvironmentManagerTests/TestSetupAndTeardownHelper.h
Includes implementation and testing for adding and removing parts for PATHEXT.
The change trackers were split up into
* EnvironmentVariableChangeTracker
* PathChangeTracker
* PathExtChangeTracker
The reason for the split is because tracking for PATH/PATHEXT are treated differently than EnvironmentVariables.  The reason for the difference is because PATH and PATHEXT allows for partial removals and deletions.
The second reason for the split was because KeyName() is used to keep the changes separated in the registry.
> Adding PathExt appending and removal + New removal logic.

- build/publish-mrt.yml
- dev/MRTCore/mrt/Microsoft.WindowsApp.Resources/projection/Microsoft.WindowsApp.Resources.Projection.csproj
Microsoft.WindowsApp.Resources.Projection should be targeting 10.0.17763.0. This is to get inalign with the RS5 support. This will also allow us to merge the thin packages into one.
> Microsoft.WindowsApp.Resources.Projection should be targeting 10.0.17763.0

- dev/MRTCore/build/versions.props
- dev/MRTCore/global.json
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
cherry pick https://github.com/microsoft/WindowsAppSDK/pull/1125. And remove an obsolete SDK ref, which had been removed in main, but not in release branch.
> MRTCore use CSWinRT 1.3.3 (#1125)

- build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
If the tests fail in the Helix environment, we still want to publish the various Helix log files as a pipeline artifact so things can be investigated.
Also, if we are running using Helix closed queues (which this repo doesn't currently do) then we'll also want the `HelixAccessToken` as well. (This change is moot for this repo, but would effect others like the PRClosed repo.)
> Publish the Helix log artifacts on failure too.

- build/build-mrt.yml
After the build pool switched to the private pool, MRTCore managed test started to fail due to some configuration issue. However, it didn't cause build break. Now it breaks the build in release branch. Disable it in release branch for now.
> Disable MRTCore managed test

- dev/VSIX/Directory.Build.targets
- dev/VSIX/Extension/WindowsAppSDK.Extension.csproj
- dev/VSIX/Extension/source.extension.vsixmanifest
This updates the experimental VSIX name to show (Experimental) instead of (Preview), to be consistent with our release channels.
Also, this sets <Preview> in the metadata to "true" to enable the "Preview" label on the VSIX, as described in the linked article.
https://devblogs.microsoft.com/visualstudio/new-preview-label-for-visual-studio-extensions-2/
Image copied from article with added oval and arrows to highlight difference.
> Rename preview VSIX to experimental

- dev/VSIX/Directory.Build.targets
- dev/VSIX/Extension/WindowsAppSDK.Extension.csproj
- dev/VSIX/Extension/source.extension.vsixmanifest
* Rename preview VSIX to experimental
Set "Preview" metadata label to "true"
* Restore original Microsoft.ProjectReunion and Microsoft.ProjectReunion.Preview VSIX identity
> Rename preview VSIX to experimental (#1178)

- build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
Now that the Windows App SDK project has it's own Helix queues setup, we can switch to using them instead of borrowing from the WinUI/XAML team's queues.
This change also adds 20H2 to the set of images being used for testing as well. (Previously we couldn't test on 20H2, as there was no "open" XAML queue to use for it).
> Use WinAppSDK's own Helix queues instead of the WinUI/XAML queues

- dev/MRTCore/mrt/Core/src/MRM.cpp
so that no unnecessary debug spew for TryGetValue.
> hide ERROR_MRM_NAMED_RESOURCE_NOT_FOUND

- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/ResourceCandidate.cpp
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/ResourceCandidate.h
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/ResourceMap.cpp
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/unittests/UnitTest.cs
if no ResourceContext is passed on ResourceMap::GetValue, a new context will be created and scoped to that function. Once GetValue returns, the context is deleted. To keep context alive, we pass ResourceContext to ResourceCandidate instead of the raw handle.
> Pass ResourceContext to ResourceCandidate

- dev/WindowsAppSDK_Insights/WindowsAppRuntimeInsights.h
This change will inform the caller that one must include the WIL package before including the header in their project.
> Include WIL before referencing WindowsAppRuntimeInsights.h

- build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
This is causing build failures when building native apps, including in CI builds that build test apps.
Sample app built after the change (locally).
> Delete linker dependency on removed lib.

- dev/MRTCore/global.json
the default rollForward value is latestPatch. Now the version on my machine is 5.0.400, and it fails to match 5.0.302. Change the value to latestMajor so that it builds as long as the version is greater or equal to 5.0.302.
> set rollForward value to latestMajor

- installer/dev/packages.h
Ensure order of WARfwk is arm64 > x64 > x86 to avoid a bug in appxsvc erroneously using e.g. x86 on an x64 machine if there's only WARfwk x86 and not x64
The installer has an ordered list to process packages - [fwk, main, singleton, ddlm] - and for each ordered as [x86, x64, arm64]. If you installed x86 first the appxsvc would then try to load the Environment dll and fail on x64(+arm64) systems due to a bug ("I see no x64 packages in this family but I do see an x86, I'll load that..."). This was purely if there's no native-arch-matching package in the family; long as WARfwk-x64 is on the machine the Environment dll would be loaded by the x64 appxsvc process, even if there's a newer version of other architectures (like I said, a bug).
But to workaround that in the short-term we can reorder …
> Ensure order of WARfwk install to avoid a Deployment issue

- build/ProjectReunion-BuildFoundation.yml
Current NugetAuthenticate and restore Microsoft.Telemetry.Inbox.Native is not restored before BuildMRT step. This prevents the telemetry from MrtCore components to be uploaded to Microsoft. Added the NugetAuthenticate and restore steps before BuildMRT step.
> Add the NugetAuthenticate and Restore telemetry internal

- build/CopyFilesToStagingDir.ps1
Microsoft.WindowsAppRuntime.Bootstrap.Net.dll was copied to the Transport's staging area not then not actually copied into the Transport package.
This may not be the right end directory in the NuGet but getting it into the NuGet unblocks other folks (docs, samples, etc). Doing testing but won't be finished as quickly as this will be available so unblock ASAP, and if it needs to move to other location(s) I'll relocate it via a follow up PR
[Bug# 35891850](https://task.ms/35891850)
> Microsoft.WindowsAppRuntime.Bootstrap.Net.dll not in Transport package

- dev/VSIX/Extension/Cpp/Dev16/source.extension.vsixmanifest
- dev/VSIX/Extension/Cpp/Dev17/Component/source.extension.vsixmanifest
- dev/VSIX/Extension/Cpp/Dev17/Standalone/source.extension.vsixmanifest
- dev/VSIX/Extension/Cs/Dev16/source.extension.vsixmanifest
- dev/VSIX/Extension/Cs/Dev17/Component/source.extension.vsixmanifest
- dev/VSIX/Extension/Cs/Dev17/Standalone/source.extension.vsixmanifest
This updates the titles and descriptions of our VSIXs to clarify that they hold templates for C++/C#, and which version of Visual Studio they target.
> VSIX titles/descriptions mention templates and VS versions

- build/CopyFilesToStagingDir.ps1
Microsoft.WindowsAppRuntime.Bootstrap.Net.dll was copied to the Transport's staging area not then not actually copied into the Transport package. (#1388)
cherry-pick 77023c6
> Cherrypick Microsoft.WindowsAppRuntime.Bootstrap.Net.dll to 1.0-preview1

- dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
For some reason the gremlins plaguing the automatic installation of the single-project MSIX extension via a VS Extension Pack (vsext) have returned.
Disabling this part for now, and we'll need to communicate to users to install that extension separately.
> The vsext install gremlins have returned, so disable it again.

- build/NuSpecs/Microsoft.WindowsAppSDK.Bootstrap.targets
This corrects 2 problems:
1. Microsoft.WindowsAppSDK.Bootstrap.targets copied the Bootstrap dll from `...\runtimes\lib\**cpu**\...` and handled it when `**cpu**` = `Win32` but not when it's `AnyCPU`. Either should grab the `x86` dll
2. Microsoft.WindowsAppRuntime.Bootstrap.Net.dll wasn't getting copied for .NET projects
I tested with various permutations of C++ and C# projects.  This doesn't affect C++ projects (were doing the right thing before, this doesn't _negatively_ impact them). OTOH C# projects now build successfully with content as expected.
This addresses [AnyCPU Class libraries are broken again #1217](https://github.com/microsoft/WindowsAppSDK/issues/1217#)
[Bug 33477857](https://task.ms/33477857)
> Copy Bootstrap .NET dll. Don't copy Bootstrap DLL if OutputType=Library

- dev/PushNotifications/PushNotificationManager.cpp
- dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListenerManager.cpp
- test/PushNotificationTests/APITests.cpp
- test/TestApps/PushNotificationsTestApp/main.cpp
Removed PushNotificationTokens from TestApp and fixed Register/Unregister Activator across tests. Also, added RegisterFullTrustApplication in RegisterLongRunningActivator.
> Fixing WNP_LRP tests 

- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
There are some problems hitting these project templates at the moment, so we're moving them back under the experimental flag.
> Disable single-project C# templates for preview 1

- build/ProjectReunion-BuildFoundation.yml
Fix signing pattern to capture all winmd and dll in the transport package
> Fix signing pattern to capture all winmd and dll in the transport package

- build/CopyFilesToStagingDir.ps1
Also sorted the groups of files alphabetically by category (the random organization was getting hard to find things)
> Move Bootstrap.Net assembly (dll) to lib\net5.0-windows10.0.17763.0

- dev/PushNotifications/GetRawNotificationEventArgs.h
- dev/PushNotifications/PushNotificationReceivedEventArgs.cpp
- dev/PushNotifications/PushNotificationReceivedEventArgs.h
- dev/PushNotifications/PushNotifications.vcxitems
- dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.cpp
- dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.h
- dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
- dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj.filters
- dev/PushNotifications/PushNotificationsLongRunningTask/utils.h
- dev/PushNotifications/utils.h
This PR fixes a couple of issues:
1. **Truncated payloads delivered to the app**: the Push payload is now processed correctly to comply with AppLifecycle command line expectations (i.e. truncation happened at the first space character - other activation types are already escaping such characters, now we do it too. Then, the payload is unescaped at GetRawNotificationEventArgs.h).
2. **Payloads with special characters crashed the app**: Special characters weren't playing okay with wstring->string conversion at PushNotificationReceivedEventArgs, because WideCharToMultiByte was erroring out with ERROR_INSUFFICIENT_BUFFER.
> Protocol Activation bug fixes

- dev/PushNotifications/PushNotificationManager.cpp
- dev/PushNotifications/PushNotificationManager.h
Pass remoteId as const value to CreateChannelAsync. As the value is const we don't need to pass by reference.
> Use remoteId as const value

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
MRT Core doesn't use [RTTI](https://en.wikipedia.org/wiki/Run-time_type_information), but the `*.vcxproj` file that is used for building `Microsoft.Windows.ApplicationModel.Resources.dll` doesn't explicitly disable it -- and it is enabled by default. We can turn it off, which saves ~70 KB.
| File    | Size Before     | Size After     |
|---------|----------------:|---------------:|
| Microsoft.Windows.ApplicationModel.Resources.dll | 178,688 | 107,520 |
**Delta** = **-71,168 bytes (69.5 KB)**
Note: I already disabled it for `MRM.dll` in the PR here: https://github.com/microsoft/WindowsAppSDK/pull/904, which saved 37 KB.
> Reduce Microsoft.Windows.ApplicationModel.Resources.dll binary size by 70KB by disabling RTTI.

- dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
- dev/VSIX/Extension/Original/WindowsAppSDK.Extension.csproj
This change removes the single-project MSIX extension pack from the Component flavor of the VSIX. The two Windows App SDK VSIXs and the single-project VSIX are going to be handled as individual components in that scenario.
Also updated the VS SDK references to the latest prerelease.
> Remove VSEXT from Component VSIX

- dev/Common/TerminalVelocityFeatures-DeploymentAPI.xml
- dev/Deployment/Deployment.idl
- dev/Deployment/DeploymentManager.cpp
- test/Deployment/APITests.cpp
Removes [experimental] attributes from the WindowsAppRuntime deployment API and sets the feature to being always available.
> Remove Experimental-ness from Deployment API

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
- build/CopyFilesToStagingDir.ps1
- build/ProjectReunion-BuildFoundation.yml
- dev/Bootstrap/CS/Microsoft.WindowsAppRuntime.Bootstrap.Net/Microsoft.WindowsAppRuntime.Bootstrap.Net.csproj
Fix x86 and arm64 Helix tests failing to build because Microsoft.WindowsAppRuntime.Bootstrap.Net.dll is in Amd64.
There was a race condition in the build where there are three jobs for amd64, x86, arm64 that builds Foundation and which ever job copied this dll to the net5.0-windows10.0.18362.0 folder is the one that gets included in the final WindowsAppSDK. 
This PR fixes this issue and allows the tests in x86 and arm64 to compile against the binary.
> Fix Helix tests failing to build because Microsoft.WindowsAppRuntime.Bootstrap.Net.dll is in Amd64

- build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
- build/Helix/packages.config
- test/WindowsAppSDK.Helix.TestCommon/WindowsAppSDK.Helix.TestCommon.csproj
This updates the "`Microsoft.Internal.WinUI.Helix`" package version to `0.5.4` to pick up the fix for the re-try logic when the Helix infra fails, causing endless timing out.
From my PR in the WinUI repo:
> We recently ran into an issue in `WindowsAppSDK` where the `ProcessHelixFiles.ps1` script was taking over ~2 hours to run (due to Helix infrastructure being down) as it never timed out / hit the maximum number of retries.
> Looking at the logs, the retry logic was never hitting the max attempts of 10 times to obtain the results from Helix.
> It turns out that these variables need to be explicitly referred to in the "global" scope, otherwise the individual functions end up redeclaring the same variable. (We want there to be a maximum number of retries overall for all functions.)
> Update the "Microsoft.Internal.WinUI.Helix" package version to 0.5.4

- dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/PushNotificationsLongRunningTask.ProxyStub.vcxproj
- dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/PushNotificationsLongRunningTask.ProxyStub.vcxproj.filters
- dev/PushNotifications/PushNotificationsLongRunningTask.ProxyStub/packages.config
- dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/PushNotificationsLongRunningTask.StartupTask.vcxproj
- dev/PushNotifications/PushNotificationsLongRunningTask.StartupTask/packages.config
Adding source link to automatically download the source code when debugging. This was added to all WindowsAppSDK dev projects in main. I'm adding the same packages to project that are in the feature branch WNP_LRP but not in main yet.
For all the details, see this PR: https://github.com/microsoft/WindowsAppSDK/pull/1500
> Adding source link to Notifications projects not yet in main

- dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
#1482 removed the MSIX vsext from the Component extension, but this was mistakenly done for the Dev16 extension. The Dev16 extension doesn't have a component-specific build with a different filename, so it builds twice, with the Component clobbering the Standalone.
This reverts the part of #1482 that touched the Dev16 projects.
Long-term, we should tidy up this part of the build so we do less work (i.e. don't build Dev16 twice).
> Unconditionally restore vsext to Dev16 VSIX

- dev/VSIX/Directory.Build.props
Fixes a small typo in https://github.com/microsoft/WindowsAppSDK/commit/46048b9eb4d79399fe9eb2f5c30812be61798a8c
> Fix small typo in commit 46048b9e.

- build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
- build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
This was missed in a rename and causes problems on native projects.
> Fix incorrect winmd name in NuSpecs

- dev/AppLifecycle/ActivationRegistrationManager.cpp
- dev/AppLifecycle/Association.cpp
- dev/AppLifecycle/Association.h
- dev/WindowsAppRuntime_DLL/pch.h
When changes happen to associations, the shell must be notified.  If it is not, then it may take a long time to show updated icons or other resources from the registration change.  This updates the AppLifecycle APIs to automatically notify the shell every time a registration happens.
> Notify the Shell when association data changes.

- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cs
to support `ImplicitUsings` and fix a bug with the intersection of `Microsoft.WindowsAppSDK.Runtime.Version` with `System.Version`.
Fixes #1686
> feat: Added global:: to MddBootstrapAutoInitializer.

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
If there are multiple `traceloggingconfig.h` files from different package versions of WIL, then the script fails as it only expects there to be one `traceloggingconfig.h` file.
Instead, replace all of the files with the one from `microsofttelemetry.h`
> Fix inline PowerShell to support multiple traceloggingconfig.h files from different WIL versions.

- WindowsAppRuntime.sln
- build/CopyFilesToStagingDir.ps1
- dev/Common/IsWindowsVersion.h
- dev/DynamicDependency/API/MddDetourPackageGraph.cpp
- dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/DynamicDependencyLifetimeManagerShadow.vcxproj
- dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/DynamicDependencyLifetimeManagerShadow.vcxproj.filters
- dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/packages.config
- dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/pch.cpp
- dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/pch.h
- dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/winmain.cpp
- dev/UndockedRegFreeWinRT/urfw.cpp
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
- dev/WindowsAppRuntime_BootstrapDLL/framework.h
- test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/Makefile.mak
- test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/Microsoft.WindowsAppRuntime.Release!4.1.0
- test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/appxmanifest.xml
https://task.ms/36777674
cherry-pick commit d7b2e035171f622975140e970c6cdc8b24eddff4 from main
Non-AppExtension implementation for <=19H1
Altered Bootstrap to workaround AppExtension issue on RS5+19H1:
1) Bootstrap enumerates potential DDLMs via PackageManager.FindsPackagesByPackageType(framework) instead of AppExtension.OpenCatalog(ddlm)
2) Bootstrap uses a DesktopBridge application process instead of a PackagedCOM OOP Server to indicate WinAppSDK Framework package-in-use
3) the package-in-use process quits when it's told to (because MddBootstrapShutdown was called) or the caller process terminated (w/o calling MddBootstrapShutdown) instead of last COM reference to the PackagedCOM OOP Server was Release'd.
We now get N 'shadow' processes (1 per Bootstrap-calling process) instead of 1 …
> Unpackaged Windows App SDK app doesn't run on RS5/19H1 (#1681)

- dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
(cherry picked from commit 55b5768e982c0425d0e15da9a14ae7cfa616c962)
(Copying the description of #1522 here)
#1482 removed the MSIX vsext from the Component extension, but this was mistakenly done for the Dev16 extension. The Dev16 extension doesn't have a component-specific build with a different filename, so it builds twice, with the Component clobbering the Standalone.
This reverts the part of #1482 that touched the Dev16 projects.
Long-term, we should tidy up this part of the build so we do less work (i.e. don't build Dev16 twice).
> Cherry pick: Unconditionally restore vsext to Dev16 VSIX (#1522)

- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
- dev/VSIX/Extension/Directory.Build.targets
- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WapProjTemplate.wapproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.vstemplate
Cherry-picking #1581 to the 1.0 Stable branch so the VS2022 VSIX templates will target .NET 6 by default, not .NET 5.
> [Cherry-pick] Updating WinUI C# project templates to target .NET 6 when building in Dev17 (#1581)

- dev/AppLifecycle/Association.cpp
Currently appIds used for association data and instancing delineation are not consistent across instances of execution for x86.  The std::hasher returns a type of size_t which is then expanded in StringCchPrintf.  The data is 32bit on x86 platforms which leads to the printf code pulling in garbage for the first half of the number.  This causes the number being different every time.
This fix keeps the appId based off of 64bit numbers, but expands the 32bit version to be 64bit and fills in the upper half with another copy of the 32bit value.
This will likely be a temporary fix though, as during investigating the root cause it was discovered that the values are not consistent between x86 and x64.  This is much more of an edge case (x86 and x64 variants of the same app, on the same machine …
> Fix x86 instancing appId generation.

- dev/Common/IsWindowsVersion.h
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
https://task.ms/36938053
Rewrite IsWindows10_*OrGreater() to workaround GetVersionEx() lying to the caller (us) if the process' exe wasn't 'built for the OS' (PE Header indicating it's built for 20H1+ or (somehow) same via a SxS manifest). This caused IsLifetimeManagerViaEnumeration() to always evaluate to using the Enumeration algorithm even on newer platforms where we wanted the AppExtension algorithm.
Also changed the testing environment variable to MICROSOFT_WINDOWSAPPRUNTIME_DDLM_ALGORITHM=0|1 (Enumeration|AppExtension).
Changes tested via test collateral as well as walking through the relevant code in the debugger bit fiddling results to ensure ultimately 100 branch coverage.
> IsLifetimeManagerViaEnumeration() always returned true

- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
Update GetEnvironmentVariable()-succeeeded check to avoid undefined behavior if the function failed due to insufficient buffer
This corrects the issue @huichen123 identified @ https://github.com/microsoft/WindowsAppSDK/pull/1751#discussion_r745980956
> Update GetEnvironmentVariable()-succeeeded check

- .github/ISSUE_TEMPLATE/bug-report.yaml
Eliminate the checkboxes since they create tasks (switch to dropdown for that), and re-order the dropdowns so NuGet package version is first (since that's most important), and switch the version numbers so you can still see what version you selected (previously the long version name would get cut off in the UI)
> Update bug report template

- build/CopyFilesToStagingDir.ps1
- dev/Licensing/MsixLicensing.cpp
- dev/Licensing/MsixLicensing.h
- dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime-Licensing.cpp
- dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime-Licensing.h
- dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime.Bootstrap.def
- dev/WindowsAppRuntime_BootstrapDLL/WindowsAppRuntime_BootstrapDLL.vcxproj
- dev/WindowsAppRuntime_BootstrapDLL/framework.h
- dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
Add an API to install our licenses.
Those who directly install the WindowsAppSDK packages (i.e. don't run WindowsAppRuntimeInstaller.exe and don't use the Deployment API) need to install the *.msix packages AND their licenses.
Easiest way to do that is to
```
#include <WindowsAppRuntime-Licensing.h>
...
const uint32_t c_majorMinorVersion{ WINDOWSAPPSDK_RELEASE_MAJORMINOR };
PCWSTR c_versionTag{ WINDOWSAPPSDK_RELEASE_VERSION_TAG_W };
const auto hr{ WindowsAppRuntime_InstallLicenses(c_majorMinorVersion, c_versionTag) };
if (FAILED(hr))
{
...error...
}
```
NOTE: There's also `WindowsAppRuntime_InstallLicensesInPackage()` but that's primarily for testing.
See `WindowsAppRuntime-Licensing.h` for more details.
> Add Licensing API

- build/ProjectReunion-BuildFoundation.yml
Fix parameter names for AssetsName and AssetsVersions. 
I noticed Foundation builds were not publishing correctly.
> Fix parameter names for AssetsName and AssetsVersions

- eng/Version.Details.xml
- eng/Versions.props
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-Build-Steps.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildAndIntegrationTest-Steps.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
- global.json
> FI main into WNP_ToastNotifications

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildSolution-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-PublishProjectOutput-Steps.yml
- build/ProjectReunion-BuildFoundation.yml
- build/build-mrt.yml
SBOM generation is enabled in each platform and configuration of the MRT and the main Foundation build. 
The json from the generations will be placed in mrtcore_binaries and windowsappsdk_binaries build artifacts for each platform and configuration.
> Enable SBOM generation for WindowsAppSDK

- dev/ToastNotifications/ToastNotificationManager.cpp
- test/TestApps/ToastNotificationsTestApp/main.cpp
- test/ToastNotificationTests/APITests.cpp
- Implements the ToastNotificationManager::Setting API
- Includes unit tests checking for the enabled scenario for unpackaged/packaged applications
> Add ToastNotificationManger::Setting API

- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
DDLM package names are `Microsoft.WinAppRuntime.DDLM.<minor><patch>.<msixminor>.<msixbuild>.<msixrevision>[-shortversiontag]`. But we only want to match down to `<minor>`. The code+spec(comment) was wrong to look for `<minor>.*` needs to be `<minor>*`
For want of a nail...
> MddBootstrapInitialize package enumeration if release Minor version >0

- build/AzurePipelinesTemplates/WindowsAppSDK-PublishProjectOutput-Steps.yml
- build/ProjectReunion-BuildFoundation.yml
- build/build-mrt.yml
- dev/VSIX/Extension/Cpp/Common/it-IT/VSPackage.it-IT.resx
- dev/VSIX/Extension/Cpp/Common/ko-KR/VSPackage.ko-KR.resx
- dev/VSIX/Extension/Cpp/Common/pt-BR/VSPackage.pt-BR.resx
- dev/VSIX/Extension/Cs/Common/it-IT/VSPackage.it-IT.resx
- dev/VSIX/Extension/Cs/Common/ko-KR/VSPackage.ko-KR.resx
- dev/VSIX/Extension/Cs/Common/pt-BR/VSPackage.pt-BR.resx
- eng/Version.Details.xml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
- global.json
Forward Integration from feature/WNP_ToastNotifications_L1 to WNP_ToastNotifications_L2.
Conflicts in the following files:
* dev/ToastNotifications/ToastActivationCallback.h
* dev/ToastNotifications/ToastNotificationManager.cpp
* dev/ToastNotifications/ToastNotificationUtility.h
* test/TestApps/ToastNotificationsTestApp/main.cpp
* test/TestApps/ToastNotificationsTestAppPackage/Package.appxmanifest
* test/ToastNotificationTests/APITests.cpp
Conflicts were resolved by keeping the changes in the L2 branch and rejecting incoming changes from L1. (git checkout --ours)
The result is identical to https://github.com/microsoft/WindowsAppSDK/pull/1993, which makes sense since we're simply cascading changes from main into our L1, then into our L2.
> FI WNP_ToastNotifications_L1into WNP_ToastNotifications_L2

- specs/dwritecore/DWriteCore.md
This spec change adds an `IDWriteFontSet4` interface with two new methods.
The majority of the spec change is background to explain the need for a new font selection algorithm and to describe the algorithm itself.
All other APIs in the spec are already existing.
> Add new font selection APIs to DWrite API spec

- specs/AppLifecycle/Restart/restartApi.markdown
Bringing in Restart API spec into main. This spec addresses the gaps in restart today and how we can expose new functions to manage restart across all app types.
> AppLifecycle Restart API

- dev/ToastNotifications/ToastNotification.cpp
- dev/ToastNotifications/ToastNotification.h
- test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
- test/TestApps/ToastNotificationsTestApp/main.cpp
- test/TestApps/ToastNotificationsTestApp/pch.h
- test/ToastNotificationTests/APITests.cpp
This is the implementation of ToastNotification class.
Also added several unit tests to verify the toast properties in packaged and unpackaged scenarios.
> Implemented ToastNotification + unit tests

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.idl
Provide explicit interface name and id to ResourceLoader/ResourceManager/ResourceContext. They are the same as auto generated by MIDL so there is no change to the user.
> Add MRTCore interface name and id

- build/ProjectReunion-BuildFoundation.yml
- build/scripts/ConvertVersionDetailsToPackageConfig.ps1
Exclude "CsWinRT.Dependency*" in version.details.xml from converting to package.config.
These are not real packages.
Also call devcheck.ps1 in the any CPU stage
> Exclude "CsWinRT.Dependency*" in version.details.xml from converting to package.config

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/projection/Microsoft.Windows.ApplicationModel.Resources.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppLifecycle/Microsoft.Windows.AppLifecycle.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.ApplicationModel.DynamicDependency/Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.ApplicationModel.WindowsAppRuntime/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.PushNotifications.Projection/Microsoft.Windows.PushNotifications.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.System.Power/Microsoft.Windows.System.Power.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.System/Microsoft.Windows.System.Projection.csproj
- eng/Versions.props
There was a mistake with [this PR](https://github.com/microsoft/WindowsAppSDK/pull/1916) that used the CsWinRTDependencyWindowsSdkPackagePackageVersion for the Windows metadata used by CsWinRT.
Instead, it should be used for WindowsSdkPackageVersion. 
Further, CsWinRTDependencyWindowsSdkPackagePackageVersion should include just the patch version, as the Windows version can vary. This means instead of taking "10.0.18362.23-preview" from Maestro, just take "23-preview".
> Correct CsWinRTWindowsMetadata

- dev/RestartAgent/RestartAgent.vcxproj
The Windows SDK version set in the RestartAgent project should match that of other projects.
> Update the Windows SDK version for RestartAgent

- dev/RestartAgent/RestartAgent.vcxproj
- test/TestApps/PushNotificationsDemoApp/PushNotificationsDemoApp.vcxproj
- test/TestApps/PushNotificationsDemoApp/main.cpp
- Bring back code to load bootstrap when the demo runs as an unpackaged app
- Ensure the bootstrp.dll is marked delayload
- Ensure activation info is configured according to run mode: packaged or unpackaged.
> Fix push demo so packaged and unpackaged projects run properly 

- Directory.Build.props
- dev/MRTCore/mrt/Core/src/MRM.vcxproj
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
Enable build options so Release binaries are APIscan-friendly.
https://task.ms/37934927
All product projects had the right settings except `/DEBUGTYPE:FIXUP`.
`ApiScan.Cpp.props` sets `/Zi /Gf /Gy` and `/DEBUG /OPT:REF /OPT:ICF /INCREMENTAL:NO /DEBUGTYPE:CV,FIXUP` (albeit via english-y named XML Elements) but only a couple of MRT projects imported that. This change moves the import to `Directory.Build.props` so all projects get the necessary options for Release builds.
Needed compiler options => `/Zi /Gf /Gy`
* `/Zi` - Debug Information Format = Program Database (PDB)
* `/Gf` - Enable string pooling = Yes. Also enabled if `/O1` (optimize for size) or `/O2` (optimize for speed) are set
* `/Gy` - Enable Function-Level Linking = Yes
Needed linker options => `/DEBUG /DEBUGTYPE:CV,FIXUP …
> Enable APIscan-friendly build options

- dev/AccessControl/Microsoft.Windows.Security.AccessControl.cpp
- dev/Common/AppModel.PackageGraph.h
- dev/DynamicDependency/API/DataStore.cpp
- dev/DynamicDependency/API/DataStore.h
- dev/DynamicDependency/API/MsixDynamicDependency.cpp
- dev/DynamicDependency/API/MsixDynamicDependency.h
- dev/DynamicDependency/API/pch.h
- dev/DynamicDependency/DynamicDependencyLifetimeManagerShadow/winmain.cpp
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
- dev/WindowsAppRuntime_DLL/pch.h
- test/DynamicDependency/Test_Win32/TestMddBootstrap.cpp
- test/DynamicDependency/Test_Win32/Test_GetCurrentPackageInfo.cpp
- test/DynamicDependency/Test_Win32/Test_LifetimeManagement.cpp
- test/DynamicDependency/Test_Win32/Test_Win32.h
- test/DynamicDependency/Test_WinRT/Test_WinRT.h
DynamicDependencies: support elevation
Expands test suite to run all tests elevated. Verified expanded test suite passes.
https://task.ms/36589098
resolves #567
> DynamicDependencies: support elevation

- build/ProjectReunion-BuildFoundation.yml
Add button to allow publishing even if there are test failures.
After investigation of the integration test failures from the internal build, I believe the issue stems from the Foundation package being not updated in the WinUI first. So we need the ability to just publish the package even if there are integration test failures so it can propogate through WinUI before making it to Internal.
> Add button to allow publishing even if there are test failures

- build/scripts/ConvertVersionDetailsToPackageConfig.ps1
- eng/Version.Details.xml
This allows us to not have an exclude list in the ConvertToVersionDetails powershell script.
> Move CSWinRT to Toolset Dependencies in Version.Details.xml

- dev/PowerNotifications/PowerNotifications.h
- dev/PowerNotifications/PowerNotifications.idl
The original PowerNotifications have EffectivePowerMode is an IAsyncOperation<T> typed as a property. Instead of introducing a breaking change, it was suggested to introduce a non-async version and update the documentation to use it instead. This PR adds the said API.
> Adding a non-async PowerNotificiations::EffectivePowerMode method

- test/TestApps/ToastNotificationsTestApp/main.cpp
Introducing DisplayName/Icon inference logic broke the Toast unit tests, since now it's mandatory to specify the assets before calling AppNotificationManager::Register().
Ran all Toast tests on SV2 after the fix and using the latest lifted DLL. All tests are passing now.
> Set icon before running the unpackaged-scenario tests

- dev/AppNotifications/AppNotificationManager.cpp
When registering an activator for Toast check if there are handlers registered with the Toast Notification Manager, if so then use the multi use flag in CoRegister otherwise use the single use flag to launch a new process each time.
> Modify the CoRegister for Com Activation so if there are not notification handlers registered a new process will be launched every time

- specs/Deployment/MSIXPackageVersioning.md
- specs/Deployment/MSIXPackages.md
Update MSIX package names' spec to match actual 1.0 behavior (missed updating spec when we updated code for 1.0-stable)
> Update MSIX package names' spec

- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cs
Added global:: to MddBootstrapAutoInitializer to support <ImplicitUsings>enable</ImplicitUsings> and fix a bug with the intersection of Microsoft.WindowsAppSDK.Runtime.Version with System.Version.
Cherry-pick'd from main (1.1): https://github.com/microsoft/WindowsAppSDK/pull/1685
git cherry-pick 1f46ce69
https://task.ms/38083595
> Add global:: to MddBootstrapAutoInitializer to support <ImplicitUsings>enable</ImplicitUsings>

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
- dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
- dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
- dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
- dev/WindowsAppRuntime_DLL/packages.config
- specs/AppLifecycle/StateNotifications/AppLifecycle StateNotifications.md
- specs/Deployment/MSIXPackageVersioning.md
- specs/Deployment/MSIXPackages.md
Conflict resolution: kept incoming changes, excepted for the solution file where I kept both.
Of note: This brings the latest UDK into the WNP_ToastNotifications_L1
How tested: ran all push and toast notifications unit tests, didn't notice anything unexpected.
> FI main into feature branch WNP_ToastNotifications_L1

- dev/AppNotifications/AppNotificationManager.cpp
- test/TestApps/ToastNotificationsDemoApp/main.cpp
- test/TestApps/ToastNotificationsDemoAppPackage/Package.appxmanifest
There was a bug with using REG_SINGLEUSE on app launch for AppNotification activation. The issue was that the com object was not activated the first time and only on the second activation would another process be created.
Now if the app has no foreground handlers, was launched by any ExtendedActivationKind that is not AppNotification, and receives a AppNotification activation, we CoCreateInstance the app and propagate the arguments through Activate.
> Fix AppNotification activation when no foreground handlers defined

- dev/AppNotifications/AppNotification.h
- dev/AppNotifications/AppNotificationProgressData.cpp
- dev/AppNotifications/AppNotificationProgressData.h
- dev/AppNotifications/AppNotificationUtility.cpp
- dev/AppNotifications/AppNotifications.idl
- dev/AppNotifications/NotificationProgressData.cpp
- dev/AppNotifications/NotificationProperties.cpp
- dev/AppNotifications/NotificationProperties.h
- test/TestApps/ToastNotificationsTestApp/main.cpp
Per API review feedback, we need a ctor that takes in a sequence number. Sequence number needs to be non-zero and enforced, otherwise we throw.
> Modify constructor for AppNotificationProgressData per API review

- build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
- build/ProjectReunion-CI.yml
- build/build-mrt.yml
This change modifies the build pipeline to publish the entire `BuildOutput` folder as an artifact, so that we can download it later  in the test stage of the pipeline, and then push it over to Helix. (This is make enabling more tests in Helix easier in the future.)
This also removes the previous build artifact that was published containing the MRT Core test binaries, and uses the `BuildOutput` artifact instead for running the MRT cores. 
(So this is doing both Step 1 & 2 together at the same time.)
> Publish all BuildOutput as a pipeline artifact, to enable running additional tests in the future.

- dev/AppNotifications/AppNotificationActivatedEventArgs.h
- dev/AppNotifications/AppNotifications.idl
- test/TestApps/ToastNotificationsDemoApp/main.cpp
> Change EventArgs to Argument

- dev/PushNotifications/PushNotificationManager.cpp
- dev/PushNotifications/PushNotificationReceivedEventArgs.cpp
- dev/PushNotifications/PushNotificationReceivedEventArgs.h
- dev/PushNotifications/PushNotifications.idl
- test/TestApps/PushNotificationsDemoApp/main.cpp
Update the idl and all the callers on the WindowsAppSDK and the demo and test apps.
Verified that the Push Notification tests keep passing.
> Remove the Handled property from PushNotificationReceivedEventArgs

- build/NuSpecs/AppxManifest.xml
- dev/AppNotifications/AppNotificationManager.cpp
- dev/AppNotifications/AppNotificationUtility.cpp
- dev/AppNotifications/AppNotificationUtility.h
- test/Deployment/data/WindowsAppRuntime.Test.Framework/appxmanifest.xml
- test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
This fixes an issue where we assumed that Registry operations return HRESULTS rather than Win32 Status error messages. We have identified and fixed this issue.
Unit tests pass after fixing some bugs.
> Address Bug in Registry access Read/Write operations

- dev/AppLifecycle/AppInstance.cpp
- dev/AppLifecycle/SharedMemory.h
This PR fixes a race condition and a crash.
Crash was observed together with @aeloros during resizing of the shared memory for the Key when there is a lot of contention on the shared memory.
The race condition can happen when two instances call FindOrRegisterForKey. Consider instance1 and instance2.
- Instance1 acquires the keyCreationMutex, meaning that it will become the instance for the provided key. 
- While Instance1 is updating the key, Instance2 finds that the mutex is already created and so it moves on to iterate the instances to find the instance with the provided key. It can for a short period of time read the key before Instance1 can update it.
This PR protects the read of the Key with the same mutex as the write.
Fixes ADO bug 38344737
Verified the changes with a local build …
> Fix race condition and crash in AppInstance.FindOrRegisterForKey("key")

- installer/dev/WindowsAppRuntimeInstall.vcxproj
Fix missing quote in Installer vcxproj.
This will fix the build break in WinAppSDK Nightly builds that checks out these files
> Fix missing quote in Installer vcxproj

- dev/AppNotifications/AppNotificationUtility.cpp
- dev/AppNotifications/AppNotificationUtility.h
Description: GetConsoleWindow in AppNotificationUtility returns a Null pointer when we are working with WinUI apps.
Fix: Fallback to default displayname and icon when console window is not available for use.
> Default display name when no window handle available in Notifications

- specs/Deployment/DeploymentAPI.md
Proposal to add DeploymentOptions object to Deployment API to allow force update of Windows App SDK packages.
> Deployment API: Add DeploymentInitializeOptions with an option to force update WinAppSDK packages

- dev/AppLifecycle/AppInstance.cpp
This PR reverts a suggestion made in #2211 to use try_create. try_create returns true even if the named mutex already exists since it calls CreateMutexExW and so we have to manually check GetLastError(). This behaviour is documented at: https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createmutexexw
> Revert try_create use as it breaks single instancing.

- build/publish-mrt.yml
- dev/MRTCore/packaging/MrtCore.PriGen.targets
- dev/MRTCore/packaging/ProjectItemsSchema.xaml
**Description**
Please see issue: https://github.com/microsoft/WindowsAppSDK/issues/1898
**Credit**
The fix here is from @evelynwu-msft (thanks Evelyn!) with two modifications from me.
Used https://github.com/microsoft/WindowsAppSDK/issues/1898#issuecomment-1058629425 with the following modifications:
- Upgraded the NuGet package to WAS 1.0.
- Commented out the contents of Directory.Build.targets.
- Moved fix into MrtCore.PriGen.targets in the NuGet pkg with the None ItemGroup removal bit removed (it's not needed, and if kept, will introduce an issue).
- Removed the change to the DisplayName (changes the name displayed in the Build Action drop-down list where there is already a "Resource").
Without and with fix:
- Delete string in RESW in the StringResources project.
- …
> [MRT Core] Add support for VS's FastUpToDate check in MRT Core.

- dev/DynamicDependency/API/MsixDynamicDependency.h
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
Fixed MddBootstrapInitialize scanning for DDLMs erroneously excluded packages with release != *.0.0
Added logging to DDLM enumeration to improve troubleshooting failures
Improved logging in package scan for DDLM(s). Logs DDLMs that do and don't meet the criteria and who's the winner. Here's they snippets logged by WIL when asking for MddBootstrapInitialize(1.0, "", 0.0.0.0)
```
Msg:[Bootstrap.Intitialize: Scanning packages for Major.Minor=1.0, Tag=, MinVersion=0.0.0.0] [FindDDLMViaEnumeration(MDD_E_BOOTSTRAP_INITALIZE_SCAN_FOR_DDLM)]
Msg:[Bootstrap.Intitialize: Microsoft.WinAppRuntime.DDLM.1.433.1758.0-x6_1.433.1758.0_x64__8wekyb3d8bbwe is applicable (Major.Minor=1.0, Tag=, MinVersion=0.0.0.0)] [FindDDLMViaEnumeration(MDD_E_BOOTSTRAP_INITALIZE_DDLM_SCAN_MATCH)]
Msg:[Bootstrap.Intitialize: …
```
> Fixed MddBootstrapInitialize scanning for DDLMs erroneously excluded packages with release != *.0.0

- dev/DynamicDependency/API/MsixDynamicDependency.h
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
* Fix MddBootstrapInitialize filter erroneously excluding packages with release != *.0.0. Added logging to DDLM enumeration to improve troubleshooting failures
`git cherry-pick 14375b96764ca5becd8007d3563575cd603ce2bf`
https://task.ms/38494338
> Fixed MddBootstrapInitialize scanning for DDLMs erroneously excluded packages with release != *.0.0 (#2248)

- dev/DynamicDependency/API/MsixDynamicDependency.h
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
…packages with release != *.0.0 (#2248)
Cherrpick of #2248
* Fix MddBootstrapInitialize filter erroneously excluding packages with release != *.0.0. Added logging to DDLM enumeration to improve troubleshooting failures
* Incorporated feedback
> [CherryPick] Fixed MddBootstrapInitialize scanning for DDLMs erroneously excluded packages with release != *.0.0

- dev/Projections/CS/Microsoft.Windows.System/Microsoft.Windows.System.Projection.csproj
I used the wrong path for the HintPath node in the csproj for Environment Manager.  Manually verified that C# can use Environment Variables.
> Enabling projections for Environment Manager.

- dev/PushNotifications/PushNotificationUtility.h
There is a case where the exe is not in a filepath in the registry but is a standalone exe. This fixes that scenario.
> Fix bug in GetExeNameFromFilePath

- dev/AppLifecycle/AppLifecycle.idl
The AppLifecycle types were not on an api contract in the 1.0 release. And in the meantime, there have been two additions to these types:
- The enum `ExtendedActivationKind` added `AppNotification`
- The runtimeclass `AppInstance` added the static method `Restart`.
Without adding a new contract version, these changes would create an ABI breaking change. These two additions are now in the v2 contract version.
(Note: this will need to be cherry-picked into the 1.1 release branch)
> Add AppLifecycle contract

- dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.vstemplate
- dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
WinUI item templates are appearing in projects where they do not belong. For example, here they are appearing in a C# console application:
In the .vstemplate files for each project item, there is a [TemplateGroupID property](https://docs.microsoft.com/en-us/visualstudio/extensibility/templategroupid-element-visual-studio-templates?view=vs-2022) that specifies what kind of project an item templates will show up in. The WinUI item templates correctly set this property. However, there is a [ShowByDefault property](https://docs.microsoft.com/en-us/visualstudio/extensibility/showbydefault-visual-studio-templates?view=vs-2022) which specifies that the template will only be displayed under the specified `TemplateGroupID` when set to `false`.
The current WinUI item templates have `ShowByDefault` …
> Prevent WinUI item templates from showing up in other project types

- dev/AppNotifications/AppNotification.cpp
- dev/AppNotifications/AppNotificationManager.cpp
- dev/AppNotifications/AppNotificationProgressData.cpp
- dev/AppNotifications/AppNotifications.idl
- dev/PushNotifications/PushNotificationChannel.cpp
- dev/PushNotifications/PushNotificationChannel.h
- dev/PushNotifications/PushNotificationCreateChannelResult.cpp
- dev/PushNotifications/PushNotificationManager.cpp
- dev/PushNotifications/PushNotificationReceivedEventArgs.cpp
- dev/PushNotifications/PushNotifications.idl
Turns out that activating APIs for preview and stable releases, requires more than just updating the terminal velocity xml files, it requires eradicating all references to the feature from the code. (feature_) from the IDL and gates from the code.
For reference: https://github.com/microsoft/WindowsAppSDK/pull/2224.
> Remove [experimental] tags take 2

- dev/MRTCore/packaging/MrtCore.PriGen.targets
Please see issue https://github.com/microsoft/WindowsAppSDK/issues/2324 for a description.
I confirmed that for both .NET 5 and .NET 6 WPF projects created in VS 2022, the property is automatically added and set to true.
Note: We don't restrict this to WPF projects because there is no harm in including the item in other project types.
Thanks to @drewnoakes for the help.
1. Use the .NET SDK change https://github.com/dotnet/sdk/pull/24139 (the change isn't merged yet, so you can do this manually by copying over the text in the change to the existing .NET 6 installation).
2. Create a WPF project targeting .NET 6.0. Add a WAP project to it to make it packaged (you'll need to make the WAP project the startup project and add a project reference to the WPF project).
3. Install …
> Add PRIResource build action to WPF projects.

- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/ProjectTemplate.vcxproj
This change:
* Renames the `EnablePreviewMsixTooling` property (used to opt into Single-project MSIX Packaging) to `EnablePreviewTooling`
* C++ project templates now select a C++ toolset based on the currently used version of Visual Studio (#1788)
* Bake the `HasPackageAndPublishMenu` property (used by Visual Studio to determine if it should enable the `Package and Publish` Solution Explorer context menu) into the project templates that use Single-project MSIX Packaging so that it is available even if the WinAppSdk Nuget package hasn't been restored yet
> Project template updates (Single-project MSIX Packaging and C++ toolset)

- specs/WinRT/WinRTAPIContracts.md
Added list of contacts acrocss WinAppSDK. NOTE: The list is meant to start the dialogue. There's undoubtedly corrections and additions needed.
Added TOC and section numbering. Minor formatting corrections
NOTE: This is a work-in-progress. Goal is to have a master list of the various contract names across features, then bring the list through API Review in 1 pass, then update code to match if/as necessary.
> List of contracts across WinApSDK

- dev/AppNotifications/AppNotificationManager.cpp
- dev/PushNotifications/PushNotificationManager.cpp
No need to wait for the payload if it has already been delivered. Push/AppNotificationManager no longer throw E_TIMEOUT if you call GetActivatedEventArgs twice.
> Return the payload if it was processed already.

- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/ProjectTemplate.vcxproj
Fixes [Bug 38465376: Package.appxmanifest is missing from Blank App, Packaged (C++) single project template solution](http://task.ms/38465376).
When creating a new C++ app using the `Blank App, Packaged (WinUI 3 in Desktop)` project template, the included `Package.appxmanifest` file doesn't appear in Solution Explorer until after the project has been reloaded, even though it is automatically included in the project by the WinAppSdk `.targets`.
Apparently `Package.appxmanifest` needs to be explicitly included via the .vcxproj rather than an imported .targets file (even if both inclusions are using the same MSBuild condition!) in order for it to appear in Solution Explorer immediately after creating a new project.
Just VS C++ doing VS C++ things. ¯\\\_(ツ)_/¯
> Fix `Package.appxmanifest` not appearing in Solution Explorer when creating a new C++ project

- dev/AppLifecycle/AppInstance.cpp
- dev/AppLifecycle/AppInstance.h
This PR fixes additional issues with the AppInstance feature:
- Resolves an issue where calling FindOrRegisterForKey("key") will always duplicate the named Mutex, preventing new instances from being created once the actual named instance has closed.
- Resolves an issue where calling FindOrRegisterForKey("key") followed by FindOrRegisterForKey("key2"), will cause the first instance to be named "key2" and all subsequent instances will share the name "key", because FindOrRegisterForKey("key2") will override the m_keyCreationMutex making it looks like no instance is named "key" yet.
We now acquire the lock on the mutex to identify what process is the owner. I added extra comments to make sure the order of release the lock and releasing the mutex is handled correctly.
> Resolve issues where AppInstance.FindOrRegisterForKey("key") can return null.

- test/TestApps/PushNotificationsDemoApp/main.cpp
- test/TestApps/ToastNotificationsTestApp/main.cpp
During AppNotification registration for unpackaged apps, we don't retrieve icon/displayName from window anymore. Hence, in this PR we remove the sample code used to set icon and display name using Shell APIs.
> Deleting SetDisplayNameAndIcon from test and demo apps

- build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.props
- build/publish-mrt.yml
- dev/MRTCore/packaging/MrtCore.PriGen.targets
- dev/MRTCore/packaging/MrtCore.props
This reverts commit 045d154c2e92e161e3775e3fec3f95aa5c215e7e.
> Revert 'Use .NET SDK's default inclusion support for Windows App SDK and remove our own broken solution. (#2381)'

- dev/MRTCore/packaging/MrtCore.PriGen.targets
There is no risk in not doing this, but it's still the right thing to do. I say there is no risk because the properties aren't referenced in native projects.
- WinUI app (WAP based) C# app: properties were set.
- WinUI app (WAP based) C++ app: properties were not set.
> [MRT Core] Set properties to get default file inclusion only if we're in a .NET project.

- dev/AppNotifications/AppNotificationUtility.h
Fix warning C4018: '<': signed/unsigned mismatch in dev\AppNotifications\AppNotificationUtility.h for x86 platform.
> Fix warning C4018 on x86

- dev/Common/Common.vcxitems
- dev/Common/Common.vcxitems.filters
- dev/Common/WindowsAppRuntime.SelfContained.cpp
- dev/Common/WindowsAppRuntime.SelfContained.h
- dev/Common/WindowsAppRuntime.VersionInfo.cpp
- dev/Common/WindowsAppRuntime.VersionInfo.h
- dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
- dev/WindowsAppRuntime_Insights/WindowsAppRuntimeInsights.h
- docs/Coding-Guidelines/SelfContained.md
- test/Common/Test_SelfContained.cpp
- test/Common/pch.h
- test/PushNotificationTests/BaseTestSuite.cpp
- test/PushNotificationTests/pch.h
- test/TestApps/PushNotificationsTestApp/main.cpp
- test/TestApps/PushNotificationsTestApp/pch.h
Cherry-pick of #2411 
* Added Microsoft::WindowsAppRuntime::VersionInfo::RuntimeInformation as a (partial) runtime-equivalent WindowsAppSDK-VersionInfo.h to workaround the chicken-egg problem where we need to know the versioninfo now but it's nto defined until higher in the build tree (the Aggregator pipeline at the top)
* Replaced WindowsAppRuntime_SelfContainedTestInitialize with WindowsAppRuntime_VersionInfo_TestInitialize as we moved the functionality down a level
* Removed dead code
* Update docs for IsSelfContained
* Update test to match SelfContained/VersionInfo::TestInitialize change
* Add missing #include
> [Ask mode approved] [Cherry-pick] Fix IsSelfContained() to lookup framework packagefamilyname at runtime

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/projection/Microsoft.Windows.ApplicationModel.Resources.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppLifecycle/Microsoft.Windows.AppLifecycle.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppNotifications.Projection/Microsoft.Windows.AppNotifications.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.ApplicationModel.DynamicDependency/Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.ApplicationModel.WindowsAppRuntime/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.PushNotifications.Projection/Microsoft.Windows.PushNotifications.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.System.Power/Microsoft.Windows.System.Power.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.System/Microsoft.Windows.System.Projection.csproj
- eng/Version.Details.xml
- eng/Versions.props
In https://github.com/microsoft/WindowsAppSDK/pull/2015#discussion_r792928818 it was suggested we rename the variable to be more accurate. https://github.com/microsoft/CsWinRT/pull/1140 is the corresponding CsWinRT PR.
> Rename CsWinRT Dependency Variable for Windows SDK

- Directory.Build.props
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildSolution-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
- build/CopyFilesToStagingDir.ps1
- build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.targets
- build/NuSpecs/Microsoft.WindowsAppSDK.UndockedRegFreeWinRT.CS.targets
- build/NuSpecs/Microsoft.WindowsAppSDK.UndockedRegFreeWinRTCommon.targets
- build/NuSpecs/WindowsAppSDK-Nuget-Native.UndockedRegFreeWinRT.targets
- build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
- dev/UndockedRegFreeWinRT/UndockedRegFreeWinRT-AutoInitializer.cpp
- dev/UndockedRegFreeWinRT/UndockedRegFreeWinRT-AutoInitializer.cs
- dev/UndockedRegFreeWinRT/UndockedRegFreeWinRT.vcxitems
- dev/UndockedRegFreeWinRT/urfw.cpp
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapActivity.cpp
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapActivity.h
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cs
- dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
- dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
- dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj.filters
- dev/WindowsAppRuntime_DLL/WindowsAppRuntime_EnsureInitialization.cpp
- dev/WindowsAppRuntime_DLL/WindowsAppRuntime_EnsureIsLoaded.cpp
- dev/WindowsAppRuntime_MSIXInstallFromPath/main.cpp
Enable UndockedRegFreeWinRT automagic initialization, when using WinAppSDK/SelfContained.
NOTE: This is similar to Bootstrapper automagic initialization, when an unpackaged app is using WinAppSDK/MSIX.
You can disable (opt-out) this auto-initialization by defining the project property `<WindowsAppSdkUndockedRegFreeWinRTInitialize>false</WindowsAppSdkUndockedRegFreeWinRTInitialize>`.
If undefined (the default) this is enabled with `<WindowsAppSDKSelfContained>` is `true`
https://task.ms/38121572
> UndockedRegFreeWinRT auto-initialization

- build/NuSpecs/AppxManifest.xml
- test/Deployment/data/WindowsAppRuntime.Test.Framework/appxmanifest.xml
- test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
Add DeploymentInitializeOptions ACID to framework package manifest.
Rectify existing Deployment ACIDs in framework package manifest by replacing DeploymentStatus (enum in Deployment idl) with DeploymentResult (runtime class in Deployment idl) in it.
> Update Deployment ACIDs in Framework package manifest

- WindowsAppRuntime.sln
- build/CopyFilesToStagingDir.ps1
- test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/Microsoft.WindowsAppRuntime.Framework.vcxproj
* Copy DeploymentAgent executable to TestFwkPkg
* Make DeploymentAgent a dependency to build Microsoft.Windows.Framework
Co-authored-by: Santosh Chintalapati <sachinta@ntdev.microsoft.com>
> Copy DeploymentAgent executable to TestFwkPkg (#2467)

- build/NuSpecs/Microsoft.WindowsAppSDK.UndockedRegFreeWinRTCommon.targets
- build/NuSpecs/WindowsAppSDK-Nuget-Native.UndockedRegFreeWinRT.targets
- dev/UndockedRegFreeWinRT/UndockedRegFreeWinRT-AutoInitializer.cpp
Some refinements on the UndockedRegFreeWinRT self-contained and auto-initialization support
Testing here is a matter of modifying the nuget used by IntegrationTests in the Aggregator and then 'porting'/copying those changes from the local nuget to the actual source here. The Aggregator update is blocked until this makes it into the build
A couple of bits are less than elegant but work and can be refined later, when not so blocking/urgent.
> UndockedRegFreeWinRT self-contained and auto-initialization support

- dev/UndockedRegFreeWinRT/urfw.cpp
UrfwInitialize() didn't report if ExtRoLoadCatalog() errored and returned a failing HRESULT (only trapped thrown exceptions, but the implementation does both)
> UrfwInitialize() didn't report if ExtRoLoadCatalog() returned error

- dev/UndockedRegFreeWinRT/UndockedRegFreeWinRT-AutoInitializer.cs
- dev/UndockedRegFreeWinRT/catalog.cpp
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cs
Remove
```c#
if (Assembly.GetEntryAssembly() != Assembly.GetExecutingAssembly())
{
return;
}
```
shortcircuit as it casts too wide a net right now. That catches loading for reflection AND for common test cases e.g.
```
te.exe foo.dll
```
as auto-initialization isn't restricted to exes (i.e. it gets compiled into foo.dll) and then Entry!=Executing.
Revert this for now and restore later when #2456 is addressed (by restricting auto-init by default to only compile into EXEs; require explicit opt-in to compile into DLLs)
> Remove C# auto-initialization check for reflection

- dev/UndockedRegFreeWinRT/UndockedRegFreeWinRT-AutoInitializer.cpp
- dev/UndockedRegFreeWinRT/UndockedRegFreeWinRT-AutoInitializer.cs
URFW auto-initializers were incorrectly referencing `UndockedRegFreeWinRT_EnsureIsLoaded()` when it should have been `WindowsAppRuntime_EnsureIsLoaded()`. This was usually harmless to the C++ auto-init but fatal to C# :-(
> Fix URFW auto-init reference to EnsureIsLoaded()

- build/NuSpecs/Microsoft.WindowsAppSDK.UndockedRegFreeWinRT.CS.targets
- build/NuSpecs/Microsoft.WindowsAppSDK.UndockedRegFreeWinRTCommon.targets
- build/NuSpecs/WindowsAppSDK-Nuget-Native.UndockedRegFreeWinRT.targets
- dev/UndockedRegFreeWinRT/UndockedRegFreeWinRT-AutoInitializer.cpp
- dev/UndockedRegFreeWinRT/UndockedRegFreeWinRT-AutoInitializer.cs
- dev/UndockedRegFreeWinRT/catalog.cpp
- dev/UndockedRegFreeWinRT/urfw.cpp
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cs
Cherry-picking all fixes by @DrusTheAxe to get UndockedRegFreeWinRT auto-initializer and support for self-contained working, into 1.1-stable.
> Fix issues in UndockedRegFreeWinRT auto-initializer and support for Self-contained

- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WinUI.Desktop.CppWinRT.WapProj.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.vstemplate
- dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/WinUI.UWP.Cs.ClassLibrary.vstemplate
- dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/WinUI.UWP.Cs.RuntimeComponent.vstemplate
- dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/WinUI.UWP.CppWinRT.BlankApp.vstemplate
This fixes #1665 by removing the spurious "Windows App SDK" platform tag.
> Remove superfluous "Windows App SDK" platform tag

- test/PushNotificationTests/BaseTestSuite.cpp
- test/PushNotificationTests/BaseTestSuite.h
- test/PushNotificationTests/PackagedTests.h
- test/PushNotificationTests/PushNotificationTests.vcxproj
- test/PushNotificationTests/UnpackagedTests.h
Issue Description:
TEST_METHOD setup should be done in the METHOD_SETUP/CLEANUP functions instead of the CLASS_* functions. Previously, the tests were using the incorrect dll to set the VersionInfo::TestInitialize with the package family name of the test package.
Fix:
Move environment setup to METHOD_SETUP.
Validation:
Ran PushNotificationTests unit tests in TAEF.
> Fix Unit Testing bug for PushNotifications

- dev/AppNotifications/AppNotificationManager.cpp
- dev/AppNotifications/AppNotificationManager.h
- dev/AppNotifications/AppNotifications.idl
- dev/PushNotifications/PushNotificationManager.cpp
- dev/PushNotifications/PushNotificationUtility.h
- test/TestApps/ToastNotificationsDemoApp/main.cpp
Branch was based on stable 1.1 branch which led to unnecessary files being merged to main. Previous PR was closed here: https://github.com/microsoft/WindowsAppSDK/pull/2505
Issue:
In elevated scenarios, PushNotifications do not work for both unpackaged + packaged applications and the IsSupported API doesn't include this limitation. Also for AppNotifications, there is no IsSupported API. Elevated scenarios are currently not supported for AppNotifications so we are added an IsElevated check to this newly added IsSupported API.
Fix:
Added IsElevated check to the Push/AppNotification IsSupported API.
Verified:
Changes were tested by manually running scenarios of unpackaged/packaged + non-elevated/elevated and confirming correct behavior of Push/AppNotification APIs.
> Notification Mitigation - AppNotificationManager::IsSupported

- specs/PushNotifications/PushNotifications-spec.md
The link to the 'Push Flow For Windows App SDK' diagram was broken due to file extension mismatch. Capitalize 'png' to fix this.
> Fix broken link to the 'Push.PNG' diagram

- eng/Version.Details.xml
This change picks up final stable license changes for installing licenses via the bootstrapper (initialization API) for the 1.1 stable release.
> Updating reference to pick up license installation fix.

- specs/dwritecore/DWriteCore.md
This change updates the DWriteCore API specification to include new color font APIs, which will be added to both system DWrite and DWriteCore.
The new color font APIs are needed to support new capabilities in version 1 of the OpenType COLR table, including gradients, transforms, and composition modes. The relevant chapter of the OpenType spec is here: https://docs.microsoft.com/en-us/typography/opentype/spec/colr
Note: Much of the new overview material is describing existing APIs.
> Add new DWrite color APIs.

- dev/Deployment/DeploymentManager.cpp
DeploymentManager.Intiialize() calls InitializeProcThreadAttributeList() to determine the size of the buffer needed but threw an exception if if failed - which it always will because it returns FALSE and `GetLastError() == ERROR_INSUFFICIENT_BUFFER`
> Bug 39711964: WinAppSDK: DeploymentManager doesn't handle ERROR_INSUFFICIENT_BUFFER

- dev/Deployment/DeploymentActivityContext.h
- dev/Deployment/DeploymentManager.cpp
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapActivity.h
Main problem is that CreateProcess is called with PROCESS_CREATION_DESKTOP_APP_BREAKAWAY_OVERRIDE instead of PROCESS_CREATION_DESKTOP_APP_BREAKAWAY_ENABLE_PROCESS_TREE which have opposite affects. The latter is what we need to create a breakaway process outside desktop app runtime environment.
Along with it, updated CreateProcess to start DeploymentAgent.exe in running mode and not in suspend mode (+ xfer foreground rights + resume it) as that's not required.
And telemetry is also reporting failure incorrectly even in case of success due to GetActivity method returning a copy of tracelogger activity object which is short lived instead of a reference to it -this is also fixed.
> Deployment agent break away process creation fixes

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/TestCommon/CommonTestCode.cs
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/TestClass.cs
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/ResourceLoader.cpp
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/ResourceLoader.h
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/unittests/UnitTest.cs
Previously ResourceManager by default uses user preferred language, but ResourceLoader uses windows display language. Now make ResourceLoader also use user preferred language.
> Make ResourceLoader use same context as default ResourceManager

- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.h
The Bootstrapper's C++ API in MddBootstrap.h uses modern C++ types like uint32_t. Depending on your code and order of #include's you could get undefined errors because stdint.h wasn't included before MddBootstrap.h. This is uncommon as most folks use the Bootstrap auto-initializer and even those who explicitly use this often add the header after other things that do bring in stdint.h. This ensures zero problem even for the rare birds who might hit it.
The workaround if you hit the problem today is to add stdint.h before MddBootstrap.h e.g.
```c++
#include <stdint.h>
#include <MddBootstrap.h>
```
https://task.ms/39766902
> MddBootstrap.h -- Add stdint.h

- dev/UndockedRegFreeWinRT/catalog.cpp
Undocked RegFree WinRT had a long-standing bug in ParseFileTag() where it retrieved the filename via `xmlReader->GetValue()` into a raw pointer and then used it AFTER calling `xmlReader->Read()`. That's a no-no -- GetValue returns a raw pointer to the current-context; you need to deep-copy if if you want to use it after you change the parser's current-context (e.g. by calling Read), as per https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms752870(v=vs.85)
>Note
>
>The pointer returned by GetValue is only valid until you move the reader to another node. When you move the reader to another node, XmlLite may reuse the memory referenced by the pointer. Therefore, you should not use the pointer after calling one of the following methods: …
> 39817966: [WinAppSDK 1.1] Unpackaged + self-contained Blank Project crashes at startup

- build/ProjectReunion-BuildFoundation.yml
Because we have two pipelines using this template, PR and Nightly, we need to disable one from publishing to the feed.
> Publish to Feed and Maestro if build is scheduled or PublishPackage is true

- dev/VSIX/Extension/Directory.Build.targets
Adding a timestamp should not be necessary anymore because WinAppSDK Nuget Versions should be unique.
> Remove Timestamp from VSIX version due to WinAppSDK NuGet Version Update

- dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.vstemplate
- dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
In a [previous PR](https://github.com/microsoft/WindowsAppSDK/pull/2289), I attempted to prevent the WinUI C# templates from appearing in projects unrelated to WinUI. To do so, I set the [ShowByDefault](https://docs.microsoft.com/en-us/visualstudio/extensibility/showbydefault-visual-studio-templates?view=vs-2022) property to `false`. When this property is `false`, the decision to show/hide the item templates falls to the [AppliesTo](https://docs.microsoft.com/en-us/visualstudio/extensibility/appliesto-element-visual-studio-templates?view=vs-2022) and [TemplateGroupID](https://docs.microsoft.com/en-us/visualstudio/extensibility/templategroupid-element-visual-studio-templates?view=vs-2022) properties.
The C# templates currently hold the value `CSharp + SharedAssetsProject`. However, an …
> Fix issue where WinUI C# and C++ item templates are not appearing in WinUI projects

- specs/AppLifecycle/EnvironmentVariables/AppLifecycle - Environment Variables (EV).md
- specs/AppLifecycle/EnvironmentVariables/AppLifecycle Environment Variables.md
I realized that the API used to manipulating environment variables can work down level. The restriction to EM was tracking the changes so they could be reverted when a package was removed.
I split up the changes. IsSupported always returns true. If the developer wants to know if the changes will be tracked, they can call the object method AreChangesTracked.
This PR has the spec change and is my formal request for an API review.
> Making EM RS5+. Limiting the tracking capability to Windows11+ (Spec)

- dev/DynamicDependency/API/MddDetourPackageGraph.cpp
- dev/DynamicDependency/API/MddDetourPackageGraph.h
- dev/DynamicDependency/API/PackageGraphManager.cpp
If `GetCurrentPackageInfo3()` is called with any `PackageInfoType` value it doesn't handle (but Windows does) we return an error instead of giving the OS a crack at it.
Changed to pass unknown enum values down to Windows instead of prematurely rejecting them.
> Detoured GetCurrentPackageInfo3() should route to the OS any PackageInfoType value it doesn't handle

- build/build-mrt.yml
- dev/MRTCore/build/DownloadDotNetCoreSdk.ps1
- dev/MRTCore/global.json
This is a follow-up to PR #1916.
The old `versions.props` file used by the script used to have two PropertyGroup XML nodes, and the new file only has one. This means that script ends up *not* getting the version from the new `Versions.props` file, which ultimately means that nothing actually gets installed. (Overall the script is a no-op).
We also need to add a check on `$dotNetSdkVersionLkg` as in the script, as within the `Versions.props` file it's defined to be `$(CsWinRTDependencyDotNetCoreSdkPackageVersion)`. But this doesn't get interpreted by PowerShell, so the string exists verbatim. This later causes the `dotnet-install.ps1` to fail, as it wants a real version number. But if its set to `$(CsWinRTDependencyDotNetCoreSdkPackageVersion)` we should just skip the second install step, …
> Fix the .NET SDK installer script used by MRT Core, and don't run the script anymore

- dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
There's a vulnerability in Newtonsoft.Json older versions. We don't use it directly, but the VSIX projects bring it in via dependencies. Adding an explicit reference to the new version.
> Update Newtonsoft.Json explicit reference in Dev16 extension projects

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/unittests/MrtCoreManagedTest.csproj
The existing reference to Newtonsoft.Json version 9.0.1 comes from Microsoft.NET.Test.Sdk, and has vulnerabilities. Even the latest Microsoft.NET.Test.Sdk package still uses that version. So add a reference to version 13.0.1 explicitly.
> add explicit Newtonsoft.Json reference

- dev/AppLifecycle/AppInstance.cpp
If we can't open the cleanup event, ignore it.
Fixes ADO#38606299
> [AppLifecycle] Properly ignore cleanup event if it can't be opened.

- installer/dev/install.cpp
Discussion #2708: [WindowsAppRuntime installation error: The package could not be installed because a higher version of this package is already installed](https://github.com/microsoft/WindowsAppSDK/discussions/2708)
>Microsoft.WindowsAppRuntime.1.1_1000.516.2156.0_x64__8wekyb3d8bbwe Package deployment result : 0x80073d06 The package could not be installed because a higher version of this package is already installed. One or more install operations failed. Result: 0x80073d06
That's a bug - it should be OK, not an error.
If v1.1.3 is installed and you run the installer for v1.1.2 we call packageManager.AddPackageAsync(...v1.1.2...) which returns 0x80073d06 == `ERROR_INSTALL_PACKAGE_DOWNGRADE` which is technically an error but functionally it's OK. If you build with 1.1.2 we don't require …
> WindowsAppRuntimeInstaller.exe fails if newer version present

- dev/VSIX/Extension/ProjectReunion.Extension.csproj
There's a vulnerability in Newtonsoft.Json older versions. We don't use it directly, but the VSIX projects bring it in via dependencies. Adding an explicit reference to the new version.
(copied from main #2662 )
> Update Newtonsoft.Json explicit reference

- WindowsAppRuntime.sln
- build/CopyFilesToStagingDir.ps1
- build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
- build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
- dev/Projections/CS/Microsoft.Windows.Security.AccessControl.Projection/Microsoft.Windows.Security.AccessControl.Projection.csproj
The runtime support for this feature shipped in 1.1, but the changes to put the winmd and headers in the nuget were missed. This fixes it.
> Put AccessControl files into transport package

- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.h
As requested by [Fix 'noexcept' C compile errors #2686](https://github.com/microsoft/WindowsAppSDK/pull/2686)
> Remove noexcept from Bootstrapper API so it can be used from C

- build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
Not-Build break 'build\native\WindowsAppSDK-Nuget-Native.C.props(32,13): error MSB4066: The attribute 'SourceFiles' in element <Copy> is unrecognized.' -- Foundation builds but the aggregator doesn't. I suspect it's because of the <Copy> command can't go in a <PostBuildEvent>, maybe something more complicated with the PostBuildEvent DependsOn a <Target> to do the copy...but I can't find any clear docs or net links clearly spelling it out so rather than fiddling while Rome burns I'm switching back to the original xcopy.exe solution to un-break the pipeline.
Will follow up with folks to understand why the PR's build didn't pick this up
> <Copy> vs XCOPY.EXE -- Unbreak WindowsAppSDK-Nuget-Native.C.props

- .github/ISSUE_TEMPLATE/bug-report.yaml
- WindowsAppRuntime.sln
- build/CopyFilesToStagingDir.ps1
- build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
- build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
- build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
- dev/AppLifecycle/AppInstance.cpp
- dev/Projections/CS/Microsoft.Windows.Security.AccessControl.Projection/Microsoft.Windows.Security.AccessControl.Projection.csproj
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.h
- eng/Version.Details.xml
- installer/dev/install.cpp
Straight up Forward Integration of develop into notification feature branch. There were no conflicts.
> FI develop into notification feature branch

- dev/AppNotifications/AppNotifications.idl
The AppNotificationManager::IsSupported API along with two enums were incorrectly added without updating the contract version.
This PR correctly adds the enums and IsSupported API by updating the AppNotificationContract in the idl.
> Fix AppNotification contract issues for IsSupported

- dev/AppLifecycle/AppInstance.cpp
If we can't open the cleanup event, ignore it.
Fixes ADO#38606299
Cherry-picked from #2658
> [1.1][AppLifecycle] Properly ignore cleanup event if it can't be opened.

- dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.cpp
- dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilderUtility.h
- dev/AppNotifications/AppNotificationBuilder/AppNotificationButton.cpp
- dev/AppNotifications/AppNotificationBuilder/AppNotificationButton.h
- dev/AppNotifications/AppNotificationBuilder/AppNotificationTextProperties.cpp
- dev/AppNotifications/AppNotificationBuilder/AppNotificationTextProperties.h
- test/AppNotificationBuilderTests/APITests.cpp
Addressing last round of feedback from: https://github.com/microsoft/WindowsAppSDK/pull/2786
Beside nits, one important issue that must addressed in this PR is retrieving the version number. Dev/Common should have a utility function to retrieve the version number. Let's make sure that whatever solution we used, it's the same for all WindowsAppSDK.
From @DrusTheAxe 
> Ugh. Version checks. That's a minefield (as in, a reliable answer is a minefield...)
> 
> Please use functions in dev\common\IsWindowsVersion.h e.g. WindowsVersion::IsWindows10_19H10OrGreater(). That has checks for >=19H1 and >=20H1, and if additional version checks are needed extend as appropos.
> 
> That avoids the minefield of GetVersion mechanisms which don't necessarily yield the expected answer
> AppNotificationBuilder - Code Improvements

- dev/AppNotifications/AppNotificationActivatedEventArgs.cpp
- dev/AppNotifications/AppNotificationActivatedEventArgs.h
- dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.cpp
- dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilderUtility.h
- dev/AppNotifications/AppNotificationBuilder/AppNotificationButton.cpp
- dev/AppNotifications/AppNotificationBuilder/AppNotificationComboBox.cpp
- dev/AppNotifications/AppNotificationBuilder/AppNotificationProgressBar.cpp
- dev/AppNotifications/AppNotifications.idl
- dev/AppNotifications/AppNotifications.vcxitems
- test/AppNotificationBuilderTests/APITests.cpp
- test/AppNotificationBuilderTests/AppNotificationBuilderTests.vcxproj
- test/AppNotificationBuilderTests/AppNotificationBuilderTests.vcxproj.filters
- test/AppNotificationBuilderTests/pch.h
- test/TestApps/ToastNotificationsDemoApp/ToastNotificationsDemoApp.vcxproj
- test/TestApps/ToastNotificationsDemoApp/main.cpp
- test/TestApps/ToastNotificationsDemoApp/pch.h
This PR contains the implementation of encoding special characters into the activation arguments for AppNotification/Button activation.
The encoded args can be retrieved in the App through AppNotificationActivatedEventArgs.Arguments which returns a decoded mapping of key/values pairs.
Added unit tests to verify correct encoding and manual testing to verify decoding from app activation was returning key/value mapping correctly.
> Encoding/Decoding AppNotificationBuilder arguments

- build/NuSpecs/Microsoft.WindowsAppSDK.BootstrapCommon.targets
Only default WindowsAppSdkBootstrapInitializer if OutputType=Exe|Winexe
Don't set WindowsAppSdkBootstrapInitializer=true when making libraries, only executables
See https://github.com/microsoft/WindowsAppSDK/issues/2456#issuecomment-1115834582 for more details.
#closes 2456
> Only default WindowsAppSdkBootstrapInitializer if OutputType=Exe|Winexe

- dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
With the move to building with VS 2022, this is causing some build pain.
> Update the versions of the VS SDK NuGet packages used to build the VSIXs

- dev/Common/IsWindowsVersion.h
- installer/dev/MachineTypeAttributes.h
- installer/dev/install.cpp
- installer/dev/main.cpp
1. Fix the logic in determining whether a given Procedure is found in the given library or not.
2. Fix console output that wasn't respecting quiet option.
3. Fix Push notifications LRP restart decision logic to be inclusive of ARM64 architecture as well.
Tested and validated the Installer on a real arm64 devices on both Windows 10 and Windows 11 versions.
> Fix Installer to work on ARM64 on Windows 10

- dev/Common/IsWindowsVersion.h
- installer/dev/MachineTypeAttributes.h
- installer/dev/WindowsAppRuntimeInstall.vcxproj
- installer/dev/WindowsAppRuntimeInstall.vcxproj.filters
- installer/dev/install.cpp
- installer/dev/main.cpp
- installer/dev/pch.h
Cherry-picked from https://github.com/microsoft/WindowsAppSDK/pull/2901 and https://github.com/microsoft/WindowsAppSDK/pull/2841
Fix installer to not attempt to install x64 framework package on Windows 10 ARM64 systems.
Fix console output that wasn't respecting quiet option.
Fix Push notifications LRP restart decision logic to be inclusive of ARM64 architecture as well.
> User/sachinta/fix installer for windows10 arm64 on release 1.1 stable

- .gitignore
- BuildTransportPackage.cmd
- BuildTransportPackage.ps1
Added BuildTransportPackage.ps1 and BuildTransportPakcage.cmd to allow building the Framework package with local foundation changes.
The script was made by looking at ProjectReunion-BuildFoundation.yml.
Script was tested manually in both release and debug for x64 by
1. adding a __debugbreak to GetForUser in EM.
2. Making a sample program that calls EnvironmentManager::GetForUser
3. Use the nuget package generated from BuildAll
4. Install the DDLM and framework packages on my test vm
5. Deploy the sample program to my test vm
6. Run the sample.
__debugbreak hit and I was able to step through the code.
> Script to build foundation transport package

- specs/Windowing/DisplayArea.md
Spec for adding a new static method to WinAppSDK 1.2:
DisplayArea.GetFromDisplayId(DisplayId)
> DisplayArea.GetFromDisplayId

- specs/VersionInfo/VersionInfo.md
Spec for new API to query Windows App SDK runtime version in use at runtime
WindowsAppSDK-VersionInfo.h at build-time provides what you're built with, but that's merely a "minimum criteria" what you'll use at runtime when using WinAppSDK framework-dependent (aka as MSIX packages). If you build with 1.2.3 you could run with 1.2.3, or 1.2.4, or 1.2.5, or... This lets you query for what is in use at runtime
See [Runtime query'able version information #2889](https://github.com/microsoft/WindowsAppSDK/pull/2889) for the implementation
https://task.ms/41026156
> Runtime query'able version information API spec

- build/NuSpecs/AppxManifest.xml
Introduced in https://github.com/microsoft/WindowsAppSDK/pull/2939 due to a bad merge
> Fix Duplicate ActivatableClass entries in appxmanifest

- specs/Deployment/DeploymentAPI.md
Update to the DeploymentManager spec with new initialization options to support the DeploymentManager auto-initializer. 
DeploymentManager's auto-initializer is modeled after the Bootstrapper's auto-initializer as they pose similar behavioral requirements.
For more information see
* [DeploymentManager auto-initializer #2835](https://github.com/microsoft/WindowsAppSDK/pull/2835) and for more details.
* [Updated Bootstrapper spec for MddBootstrapIntialize2(...options) #2335](https://github.com/microsoft/WindowsAppSDK/pull/2335)
* [Rich information on Bootstrap initalization failure #2316](https://github.com/microsoft/WindowsAppSDK/pull/2316)
https://task.ms/41000657
> DeploymentInitializeOptions spec update

- build/NuSpecs/Microsoft.WindowsAppSDK.DeploymentManagerCommon.targets
Fix WindowsAppSdkDeploymentManagerInitialize to default to true when WindowsPackageType=MSIX (was backwards before)
> Fix WindowsAppSdkDeploymentManagerInitialize to default to true when WindowsPackageType=MSIX

- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
> Add SDK Build Tools package reference, for when full Windows SDK isn't installed

- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/App.xaml.cs
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/App.xaml.cs
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/App.cpp
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/App.cpp
Changing comments in the `OnLaunched` method for Desktop applications. These comments held true for UWP but `OnLaunched` always gets called.
> WinUI 3 new project templates have incorrect comment about OnLaunched

- specs/dynamicdependencies/DynamicDependencies.md
Add `MddGetPackageGraphRevisionId()` (Flat-C API) and `PackageGraphRevisionId` property (WinRT API), for alignment with [Windows 11 API / terminology](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/framework-packages/use-the-dynamic-dependency-api).
GenerationId is soft-deprecated (predecessor equivalent to PackageGraphRevisionId still supported but will go away in a future release).
Also corrected spec missing updates:
* Corrected missing changes per previous API Review and implementation
* Added missing contracts (added in WinAppSDK 1.1)
https://task.ms/41077950
> Add MddGetPackageGraphRevisionId() + M.W.AM.DynamicDependency.PackageDependency.PackageGraphRevisionId API Spec

- dev/Common/IsWindowsVersion.h
- dev/DynamicDependency/API/M.AM.DD.PackageDependency.cpp
- dev/DynamicDependency/API/M.AM.DD.PackageDependency.h
- dev/DynamicDependency/API/M.AM.DynamicDependency.idl
- dev/DynamicDependency/API/MddDetourPackageGraph.cpp
- dev/DynamicDependency/API/MsixDynamicDependency.cpp
- dev/DynamicDependency/API/MsixDynamicDependency.h
- dev/DynamicDependency/API/PackageGraphManager.cpp
- dev/DynamicDependency/API/PackageGraphManager.h
- dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
- test/DynamicDependency/Test_Win32/Test_GetCurrentPackageInfo.cpp
- test/DynamicDependency/Test_Win32/Test_Win32.cpp
- test/DynamicDependency/Test_Win32/Test_Win32.h
Add MddGetPackageGraphRevisionId() and PackageGraphRevisionId property.
Detour GetPackageGraphRevisionId() (new in recent Windows previews).
Detach Detour'd functions in reverse order that we Detour'd them.
Moar Tests!
https://task.ms/41077943
> Add MddGetPackageGraphRevisionId() and PackageGraphRevisionId property

- dev/UndockedRegFreeWinRT/urfw.cpp
UrfwInitialize() fails if exe lacks a Fusion manifest
UrfwInitialize() calls ExtRoLoadCatalog() calls CreateActCtxW() to create an activation context with the executable's Fusion manifest. If the exe has no manifest CreateActCtxW() returns ERROR_INVALID_HANDLE with GetLastError=ERROR_RESOURCE_DATA_NOT_FOUND. ExtRoLoadCatalog() detects the failure but (1) `SetLastError(ERROR_OUTOFMEMORY)` due to a developer mistake copy-pasta error handling from a wil::make_unique call (i.e. memory allocation) and (2) treats not-found as an error.
Executables aren't required to have Fusion manfiests. Requiring one is an error.
To repro, create a tiny trivial exe with NO Fusion manifest and 
```
int main()
{
LoadLibrary("Microsoft.WindowsAppRuntime.dll")
return 0;
}
```
Run under the debugger you'll see …
> UrfwInitialize() fails if exe lacks a Fusion manifest

- docs/Coding-Guidelines.md
- docs/Coding-Guidelines/WinRT-Registration.md
This is a polished form of the information in issue #2352 [WinAppSdk is difficult to use with reg-free WinRT due to class/file naming, pairs](https://github.com/microsoft/WindowsAppSDK/issues/2352#)
and particularly [in this comment](https://github.com/microsoft/WindowsAppSDK/issues/2352#issuecomment-1087004638).
> Doc WinAppSDK's WinRT registration choice

- .github/workflows/build.yml
This adds the ISSUE_TEMPLATE directory to the list of directories that are not built.
> skip checks on bug template

- dev/UndockedRegFreeWinRT/urfw.cpp
Microsoft.WindowsAppRuntime.dll fails in DllMain if loaded by a process whose exe has resources but not an embedded SxS fusion manifest. Those are distinct error codes from `CreateActCtxW()` but we only trapped for one. Updated to trap for both conditions.
https://task.ms/41853965
> Microsoft.WindowsAppRuntime.dll!DllMain fails if exe has resources but no SxS manifest

- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/app.manifest
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/app.manifest
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/app.manifest
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/app.manifest
This PR fixes microsoft/microsoft-ui-xaml#5659
Basically, the DPI awareness settings in the project template are needlessly complicated. 
Those complicated settings are recommendable if old versions of Windows are supported, however WindowsAppSDK requires Windows 10 1809, which easily supports the most modern setting.
> Simplify Project Template: DpiAwareness in `app.manifest`

- dev/VSIX/Directory.Build.props
Update versions used in the project templates.
SDK Build Tools - 10.0.22621.755
CppWinRT - 2.0.220929.3
Windows Implementation Library 1.0.220914.1
These match the versions in the Samples in https://github.com/microsoft/WindowsAppSDK-Samples/pull/268
The Minimum VS version is also updated to 17.0.
> update vsix versions

- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win10-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WapProjTemplate.wapproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win10-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WapProjTemplate.wapproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/ProjectTemplate.vcxproj
The VC++ project system expects the `ARM64` platform name to be all caps so for consistency in mixed-language solutions we should update the project templates to reflect this (bad things happen, i.e. file access conflicts, if projects within a solution use inconsistent casing for the `ARM64` platform and a parallel build is invoked via `/m`).
> Normalize `ARM64` platform in project templates

- dev/VSIX/Directory.Build.props
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win10-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WapProjTemplate.wapproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win10-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WapProjTemplate.wapproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/ProjectTemplate.vcxproj
Numerous build issues in new blank applications and allows creation of Appx in Arm64 VS
Issues with double-building due to casing differences and uses the VC++ recommendation (C# doesn't care).
[update vsix versions by bpulliam · Pull Request #3100 · microsoft/WindowsAppSDK (github.com)](https://github.com/microsoft/WindowsAppSDK/pull/3100/files)
[Normalize ARM64 platform in project templates by evelynwu-msft · Pull Request #3101 · microsoft/WindowsAppSDK (github.com)](https://github.com/microsoft/WindowsAppSDK/pull/3101/files)
> [1.2-stable] Update Project Templates in the VSIX for ARM64 (non-fork)

- dev/VSIX/Directory.Build.props
> Update cppwinrt for ComponentConnectorT build error fix

- dev/VSIX/Directory.Build.props
- dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
- dev/VSIX/Extension/Cpp/Dev17/Component/source.extension.vsixmanifest
- dev/VSIX/Extension/Cpp/Dev17/Standalone/source.extension.vsixmanifest
- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev17/Component/source.extension.vsixmanifest
- dev/VSIX/Extension/Cs/Dev17/Standalone/source.extension.vsixmanifest
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
In order for a VS extension to be installed on ARM64 the appropriate [additions](https://learn.microsoft.com/en-us/visualstudio/extensibility/arm64/target-arm64-visual-studio-extension?view=vs-2022) need to be made to the VSIX manifest. This change does that for the WinAppSDK Project Templates extension.
> Allow WinAppSDK Project Templates VSIX to be installed on ARM64

- dev/VSIX/Directory.Build.props
- dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
- dev/VSIX/Extension/Cpp/Dev17/Component/source.extension.vsixmanifest
- dev/VSIX/Extension/Cpp/Dev17/Standalone/source.extension.vsixmanifest
- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev17/Component/source.extension.vsixmanifest
- dev/VSIX/Extension/Cs/Dev17/Standalone/source.extension.vsixmanifest
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
In order for a VS extension to be installed on ARM64 the appropriate [additions](https://learn.microsoft.com/en-us/visualstudio/extensibility/arm64/target-arm64-visual-studio-extension?view=vs-2022) need to be made to the VSIX manifest. This change does that for the WinAppSDK Project Templates extension.
(cherry picked from commit 9f3ed820847002d391a4ba19ad2def89d44afc24)
(cherry picked from #3120)
> [Cherry-pick] Allow WinAppSDK Project Templates VSIX to be installed on ARM64

- dev/AppNotifications/AppNotificationManager.cpp
- dev/AppNotifications/AppNotificationTelemetry.h
- test/AppNotificationTests/AppNotifications.Test.h
- test/AppNotificationTests/UnpackagedTests.cpp
Now it's time to bring WIL activities goodness to App Notifications.
**How verified:** While running the AppNotificationTests suite, I recorded AppNotificationTelemetry traces in an etl file and I was able to see the new activities there.
**Bonus:** I fixed a couple of minor test bugs on AppNotificationTests.
> Introducing WIL activities for AppNotifications

- WindowsAppSDK.Build.Cpp.props
Added the /Qspectre compiler flag, as suggested by BinSkim, as a project wide default setting.
> Update WindowsAppSDK.Build.Cpp.props to add /Qspectre flag

- dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Component Governance Checks failing due to expired NewtonSoft.Json version
> Update Newtonsoft.Json explicit reference in VSIX projects

- DevCheck.ps1
- Directory.Packages.props
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/projection/Microsoft.Windows.ApplicationModel.Resources.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppLifecycle/Microsoft.Windows.AppLifecycle.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppNotifications.Builder.Projection/Microsoft.Windows.AppNotifications.Builder.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppNotifications.Projection/Microsoft.Windows.AppNotifications.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.ApplicationModel.DynamicDependency/Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.ApplicationModel.WindowsAppRuntime/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.PushNotifications.Projection/Microsoft.Windows.PushNotifications.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.Security.AccessControl.Projection/Microsoft.Windows.Security.AccessControl.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.System.Power/Microsoft.Windows.System.Power.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.System/Microsoft.Windows.System.Projection.csproj
- eng/Version.Dependencies.props
- eng/Version.Dependencies.xml
- eng/Version.Details.xml
Unfortunately, Maestro is not happy with how we format our manual dependencies in version.details.xml. 
We need to leave version.details.xml alone and move our manual dependencies into a version.dependencies.xml.
>  Separate Maestro dependencies and manual dependencies into two xml files

- dev/Kozani/KozaniManager/KozaniManager.vcxproj
- dev/Kozani/KozaniManager/packages.config
- dev/Kozani/KozaniManager/pch.h
- dev/Kozani/KozaniRemoteManager/KozaniRemoteManager.vcxproj
- dev/Kozani/KozaniRemoteManager/packages.config
- dev/Kozani/KozaniRemoteManager/pch.h
- tools/ProjectTemplates/dev.cpp.exe+dll.com-oopserver/PurojekutoTenpuret/PurojekutoTenpuret.vcxproj
- tools/ProjectTemplates/dev.cpp.exe+dll.com-oopserver/PurojekutoTenpuret/packages.config
- tools/ProjectTemplates/dev.cpp.exe+dll.com-oopserver/PurojekutoTenpuret/pch.h
- tools/ProjectTemplates/dev.cpp.exe.com-oopserver-main/PurojekutoTenpuret.vcxproj
- tools/ProjectTemplates/dev.cpp.exe.com-oopserver-main/PurojekutoTenpuretActivity.h
- tools/ProjectTemplates/dev.cpp.exe.com-oopserver-main/packages.config
- tools/ProjectTemplates/dev.cpp.exe.com-oopserver-main/pch.h
dev.cpp.*.com-oopserver[-main] templates (and thus Kozani[Remote]Manager) were lacking C++/WinRT support - you could build but not consume WinRT
> dev.cpp.*.com-oopserver[-main] + Kozani[Remote]Manager lacking C++/WinRT support

- dev/PushNotifications/PushNotificationManager.cpp
- test/PushNotificationTests/BaseTestSuite.cpp
- test/PushNotificationTests/BaseTestSuite.h
- test/PushNotificationTests/PackagedTests.cpp
- test/PushNotificationTests/PackagedTests.h
- test/PushNotificationTests/UnpackagedTests.cpp
- test/PushNotificationTests/UnpackagedTests.h
…eTime (#3335)
* Initial fix
The ExpirationTime being returned by PushNotificationChannel has been returning incorrectly. Instead of returning value 30 days from the request, it is returning some value in year 1602. This is because originally, the code was using winrt::copy_from_abi to copy the DateTime. The fix is to take the ExpirationTime from the ABI and convert it to a winrt::DateTime.
* Add unit test
Added a unit test verifying the returned channel is within the expected range.
* Change constraint
* Update upper bound
* Change upper bound to 1 min
WARNING:
For status checks on the develop …
> [CherryPick] Fix PushNotificationChannel::ExpirationTime

- dev/PushNotifications/PushNotificationManager.cpp
- test/PushNotificationTests/BaseTestSuite.cpp
- test/PushNotificationTests/BaseTestSuite.h
- test/PushNotificationTests/PackagedTests.cpp
- test/PushNotificationTests/PackagedTests.h
- test/PushNotificationTests/UnpackagedTests.cpp
- test/PushNotificationTests/UnpackagedTests.h
* Fix PushNotificationChannel::ExpirationTime incorrectly returning DateTime (#3335)
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/3388
https://github.com/microsoft/WindowsAppSDK/pull/3335
WARNING:
(https://dev.azure.com/ms/ProjectReunion/_build?definitionId=391&_a=summ …
> [CherryPick] Fix PushNotificationChannel::ExpirationTime (#3388)

- DevCheck.ps1
@kythant this fixes a pipeline break so the PR can't complete on its own. Need a superadmin (like yourself :-) to complete it without waiting for the PR build to complete.
Check-TAEFServiceImagePath would fail (Powershell error) if no TAEF service is registered. Repro'd locally and verified the fix fixes it.
> DevCheck fix: No taefservice detected = boom

- WindowsAppSDK.Build.Cpp.props
- dev/AppNotifications/AppNotificationManager.cpp
Fixing return strategy (needs to be co_return) preventing use of /await:strict when compiling the SDK
> Add /await:strict to C++ build props

- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
The addition of VersionInfo also needs to be added to the build yaml.
WARNING:
> [1.3] Fix Version Info Experimental

- build/ProjectReunion-BuildFoundation-Weekly.yml
**Problem**
When the packageVersion string is being referenced in StageAndPackge, it contains an unresolved PipelineType variable, like this: "1.4.0-20230325.0.develop.$(PipelineType)", resulting in the error.
**Proposed Fix**
Explicitly populate the PipelineType property in the pipeline definition yml file ProjectReunion-BuildFoundation-Weekly.yml.
**How built**
Earlier draft built fine. Will go through normal PR validation.
**How tested**
In the following sample run of the weekly pipeline, the error in question no longer repros. The packageVersion string is fully resolved to a valid package version string in StageAndPackge.
https://microsoft.visualstudio.com/ProjectReunion/_build/results?buildId=67377364&view=results
-----
A microsoft employee must use /azp run to validate using the …
> Bug 43948918 - fix error in the StageAndPackge stage in Foundation repo's weekly pipeline

- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
The addition of VersionInfo also needs to be added to the build yaml.
WARNING:
> Fix Version Info Experimental

- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
One instance of the call to the NuGetAuthenticate task is still referencing an old version.
Updated to reference the same newer task version as elsewhere in the project.
How built:
- Topic branch built fine.
- Will go through usual PR validation
How tested:
In the test run below, the 2nd call to the NuGetAuthenticate task from the job "Build Release_x64" no longer triggers the "version is deprecated, needs to upgrade task" warning in the ADO bug.
- https://microsoft.visualstudio.com/ProjectReunion/_build/results?buildId=67739316&view=results
---
WARNING:
For status checks on the develop branch, …
> ADO bug 43814738 - Fixed call to deprecated NuGetAuthenticate

- build/ProjectReunion-CI.yml
Updated the CredScan and PostAnalysis tasks to target their newer versions, according to warnings in Guardian logs.
How Built:
- will go through usual PR validation
How tested:
- will observe in official pipeline runs whether the Guardian warnings are gone.
--------
WARNING: …
> ADO b#44156775 - Updated versions of some tasks

- specs/dynamicdependencies/DynamicDependencies.md
Extend the API with support for initialization options
* Flat-C: Add enum `MddBootstrapInitializeOptions`
* Flat-C: Add `MddBootstrapInitialize2()` same as `MddBootstrapInitialize()` plus the `options` parameter
* C++: Add enum `InitializeOptions`
* C++: Add optional `options` parameter to `Initialize*()`
* C#: Add enum `InitializeOptions`
* C#: Add `Initialize()` and `TryInitialize()` overloads for optional `options` parameter
> Updated Bootstrapper spec for MddBootstrapIntialize2(...options)

- installer/dev/WindowsAppRuntimeInstall.vcxproj
Installer fails to build ARM64 (CETCOMPAT=true not compatible)
https://task.ms/44283881
> 44283881 Installer fails to build ARM64 (CETCOMPAT=true not compatible)

- NuGet.config
- eng/common/nuget.config
This PR addresses https://task.ms/44315588.
In order to support the Nuget template wizard (used for installing Nuget packages into newly created projects that utilize `packages.config`, i.e. our C++ project templates) it is necessary to include all Nuget packages that will be installed in the VSIX's payload. An error will occur during project creation if one of those packages is missing. 
In this case, it turns out that `Microsoft.Windows.SDK.BuildTools` is now included in Visual Studio's shared Nuget package cache (used by Nuget as the default fallback source) which prevents the build from locating the corresponding `.nupkg` for inclusion in the VSIX payload. The solution is to disable the fallback sources in `nuget.config` to ensure that the `.nupkg` will be downloaded and present in …
> Resolve Nuget install error when creating new C++ project using WinAppSDK 1.3 VSIX

- NuGet.config
- eng/common/nuget.config
(cherry picked from commit 2d864daba5861a41f1b292fb534c12d6791a88bb)
Original PR  (#3596) description:
> This PR addresses https://task.ms/44315588.
> 
> In order to support the Nuget template wizard (used for installing Nuget packages into newly created projects that utilize packages.config, i.e. our C++ project templates) it is necessary to include all Nuget packages that will be installed in the VSIX's payload. An error will occur during project creation if one of those packages is missing.
> 
> In this case, it turns out that Microsoft.Windows.SDK.BuildTools is now included in Visual Studio's shared Nuget package cache (used by Nuget as the default fallback source) which prevents the build from locating the corresponding .nupkg for inclusion in the VSIX payload. The solution is to …
> [Cherry-pick] Resolve Nuget install error when creating new C++ project using WinAppSDK 1.3 VSIX

- DevCheck.ps1
- test/Kozani/KozaniManagerRuntimeTests/packages.config
DevCheck: set ExitCode to non-zero if 1+ issues detected
Fix KozaniManagerRuntimeTests' Dependencies
> DevCheck ExitCode if issues detected. Fix dependencies

- DevCheck.ps1
Change Get-Service to ignore errors, for when there's a service that's malformed or would otherwise tank the Get-Service command
WARNING:
> Change Get-Service calls to ignore errors

- BuildAll.ps1
Small tweak to the `BuildAll.ps1`'s `vswhere` command so it can find and use Visual Studio Preview installations. This allows `BuildAll.cmd/ps1` to actually be usable by people like me who only have a prerelease version of Visual Studio installed.
> Make BuildAll.ps1 compatible with VS prerelease installs

- installer/dev/WindowsAppRuntimeInstall.vcxproj
- installer/test/InstallerFunctionalTests/constants.h
To improve our naming convention, we are updateing Installer exe name to specify architecture to differentiate between each architecture.
> Update Installer exe to include Architecture

- build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
> Fix PostBuild event for copying Bootstrap DLL

- test/VersionInfo/VersionInfoTests.cpp
VersionInfo WinRT API can't be used in non-experimental builds or compile errors
> Don't reference VersionInfo WinRT API if it's disabled

- build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
Commit `e03da672` from Fix #3683 caused build errors in some cases like this:
```
PostBuildEvent:
xcopy.exe /y "D:\app\Output\Packages\Microsoft.WindowsAppSDK.1.4.230705001-experimental.nightly\build\native\..\..\runtimes\win10-x64\native\Microsoft.WindowsAppRuntime.Bootstrap.dll" "D:\app\Output\Debug\x64\Internal\V7\Bin\appoutput\Microsoft.WindowsAppRuntime.Bootstrap.dll"
:VCEnd
Does D:\app\Output\Debug\x64\Internal\V7\Bin\appoutput\Microsoft.WindowsAppRuntime.Bootstrap.dll specify a file name
or directory name on the target
(F = file, D = directory)?
```
Adding `/-I` in the xcopy command should fix this by telling it to assume single file in this case.
Note: This `/-I` can cause "insufficient memory" errors if a filename isn't specified. Also note that the GitHub customer had some …
> Add /-I to xcopy command to fix build errors.

- build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
The attempted fix for #3708 caused problems in build pipelines due to /-I parameter not being known in that environment. Reverting back to previous state for now before #3683.
> Revert back to old xcopy command for now to unblock build pipelines.

- eng/Version.Details.xml
Basically, to match versions in use by Win UI:
CSWinRT – 2.0.2 (currently 2.0.0)
.NET SDK – 6.0.412 (currently 6.0.301)
.NET Runtime – 6.0.20 (currently 6.0.6)
-----
WARNING:
and run the build against your PR …
> Udpate CsWinRT and WinAppSDK Depedency versions

- dev/VSIX/Directory.Build.props
(cherry picked from commit 9005d3311dd6c8e80ee7479f117a593e173625d9)
Original PR description (#3729):
> Updating VS project templates to use the latest C++/WinRT Nuget package. The version we were previously using in some cases did not emit the fully-qualified name for types in the function signatures of projected types (e.g. the projection for Microsoft.UI.Xaml.Markup.ComponentConnector; the projected Connect() method had the signature void Connect(int32_t connectionId, Windows::Foundation::IInspectable const& target) rather than void Connect(int32_t connectionId, winrt::Windows::Foundation::IInspectable const& target). Because the Microsoft.UI.Xaml namespace now has an API that consumes a type from the Microsoft.Windows.ApplicationModel.Resources namespace, the non-fully qualified name …
> [release/1.4-stable] Use latest C++/WinRT in C++ project templates

- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
- dev/VSIX/WindowsAppSDK.Extension.sln
This cherry pick implements the removal of VSIX Cruft and drops support for older versions of Visual Studio. 
Original PR: https://github.com/microsoft/WindowsAppSDK/pull/3739.
> VSIX Cruft Cherry-Pick 

- installer/dev/InstallActivityContext.cpp
- installer/dev/InstallActivityContext.h
- installer/dev/install.cpp
Fix crashes in the installer, which appears to account for 95%+ of crashes in WindowsAppRuntimeInstall.exe.
Errors fixed:
* InstallActivityContext.cpp was passing an hstring to StringCchPrintf for the activity Id. **Fix**: call ".data()" on the hstring to properly pass the WCHAR*.
* InstallActivityContext.cpp was passing std::wstring to StringCchPrintf for the resource (package) id and error text. **Fix**: call ".c_str()" on the std::wstring to properly pass the WCHAR*.
* InstallActivityContext.cpp for ProvisionPackage failures wasn't passing the resource/package id for one of the "%s" arguments. **Fix**: Pass m_currentResourceId.c_str() for that argument.
* InstallActivityContext.cpp for StagePackage failures was passing a GUID for one of the "%s" arguments. **Fix**: convert the GUID to …
> Fix crashes in the installer

- installer/dev/InstallActivityContext.cpp
- installer/dev/InstallActivityContext.h
- installer/dev/install.cpp
(cherry-picked from commit `cc3f5aa7`)
Fix crashes in the installer, which appears to account for 95%+ of crashes in WindowsAppRuntimeInstall.exe.
Errors fixed:
* InstallActivityContext.cpp was passing an hstring to StringCchPrintf for the activity Id. **Fix**: call ".data()" on the hstring to properly pass the WCHAR*.
* InstallActivityContext.cpp was passing std::wstring to StringCchPrintf for the resource (package) id and error text. **Fix**: call ".c_str()" on the std::wstring to properly pass the WCHAR*.
* InstallActivityContext.cpp for ProvisionPackage failures wasn't passing the resource/package id for one of the "%s" arguments. **Fix**: Pass m_currentResourceId.c_str() for that argument.
* InstallActivityContext.cpp for StagePackage failures was passing a GUID for one of the "%s" …
> [release/1.4-stable] Fix crashes in the installer

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildTransportPackage-Stage.yml
A change in Buildall.ps1 in the Aggregator now properly passes the VersionTag which is now causing issues with any version tag that has a '.' char
> Fix WinAppSDK Version Schema on WinAppSDKIntegrationBuildAndTest

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
Improve MRTCore build reliability by adding retry on build task. 
This stage has been failing with 
C:\__w\_temp\codeql3000\d\cpp\working/tmp/2b2bea2d-680e-4ece-8bea-034b1315f03a.c(1): error C2118: negative subscript [C:\__w\1\s\dev\MRTCore\mrt\Microsoft.Windows.ApplicationModel.Resources\src\Microsoft.Windows.ApplicationModel.Resources.vcxproj]
from time to time
> Improve MRTCore build reliability

- build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
- build/NuSpecs/Microsoft.WindowsAppSDK.Bootstrap.CS.targets
- build/NuSpecs/Microsoft.WindowsAppSDK.DeploymentManager.CS.targets
- build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.targets
Cherry-pick for 1.4.2 servicing. This fix enables removal of [this workaround](https://github.com/microsoft/WinUI-Gallery/blob/258d8c8b033b456689675b5f76cf66f62d5c300a/WinUIGallery/WinUIGallery.csproj#L251C39-L251C39).
> Add auto initializer sources without a target, and define a user-available property to add WindowsAppSDK-VersionInfo.cs exactly once

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildTransportPackage-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-PackNuget-Steps.yml
- build/ProjectReunion-BuildFoundation.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-PR.yml
- build/WindowsAppSDK-Foundation-Release.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-Build-Steps.yml
> Only Publish NuGet Package to Feed in Release and Nightly Builds

- installer/dev/WindowsAppRuntimeInstall.rc
- installer/dev/WindowsAppRuntimeInstall.vcxproj
- installer/dev/WindowsAppSDK-VersionInfo.h
WindowsAppRuntimeInstall.exe doesn't have a version resource. That means all crash telemetry comes in for version 0.0.0.0, which prevents seeing if fixes in the latest version have improved reliability.
This fix adds a version resource using the existing AssemblyInfo.ver. This won't provide enough information to see if/which servicing release the installer is from, but it at least will show which major.minor version it is from.
> Add version info to WindowsAppRuntimeInstall.exe

- installer/dev/WindowsAppRuntimeInstall.rc
- installer/dev/WindowsAppRuntimeInstall.vcxproj
- installer/dev/WindowsAppSDK-VersionInfo.h
Cherry-pick from #3884.
WindowsAppRuntimeInstall.exe doesn't have a version resource. That means all crash telemetry comes in for version 0.0.0.0, which prevents seeing if fixes in the latest version have improved reliability.
This fix adds a version resource using the existing AssemblyInfo.ver. This won't provide enough information to see if/which servicing release the installer is from, but it at least will show which major.minor version it is from.
> Add version info to WindowsAppRuntimeInstall.exe for release/1.4-stable

- build/CopyFilesToStagingDir.ps1
This PR addresses an issue where the wrong binary (Microsoft.WindowsAppRuntime.dll) was deployed instead of the intended Microsoft.WindowsAppRuntime.Bootstrap.dll. This correction ensures that the appropriate binaries are deployed for .NET8 support, particularly addressing the breaking changes in the .NET8 framework.
>  Fix: Correct Binary Deployment for .NET8 Breaking Change Support

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildTransportPackage-Stage.yml
Increase Job Timeout to 120 for Build
It is timing out because PublishPipelineArtifacts is taking a long time on non-OneBranch Pipeline builds.
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/4001
> Increase Job Timeout to 120 for Build 

- build/CopyFilesToStagingDir.ps1
https://github.com/microsoft/WindowsAppSDK/pull/3998
WARNING:
> Fix: Correct Binary Deployment for .NET8 Breaking Change Support Cherry-Pick

- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x86.pubxml
**Current Behavior:**
The current MSBuild logic checks if the Target Framework Moniker (TFM) is NET8 and conditionally sets the runtime identifiers to win-x86, win-x64, win-arm64 (from win10-x86, win10-x64, win10-arm64).
**Proposed Changes:**
Instead of checking for a specific TFM (like net8.0), the logic should be based on whether the target framework version is greater than or equal to 8. 
**Reason for Change:**
This change ensures our build process stays forward-compatible with upcoming .NET versions, starting from .NET 9. It also simplifies our project templates by removing the need for future updates when new .NET versions are released.
> Update MSBuild PropertyGroup for Extended .NET Runtime Identifier Support

- build/CopyFilesToStagingDir.ps1
- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.vstemplate
.NET8 introduced a [conditional breaking change](https://github.com/dotnet/docs/issues/35398) that influences how the runtime host looks for RID-specific assets. In NET8, support for non-portable RIDs (runtime identifiers specific to versions and distributions, such as win10-x86) is discontinued. The folder structure of the Microsoft.WindowsAppSDK NuGet is structured with assets marked using these non-portable RIDs:
The changes made to the `CopyFilesToStagingDir.ps1` script along with the project template changes should help support the .NET8 scenario. The selection of the project template's RIDs is conditional and based on the TFM chosen by the user. If NET8 is chosen, the RIDs become portable, enabling the runtime host to locate the RID-specific assets that were previously unattainable.
> [1.4] Correct Binary Deployment for .NET8 Breaking Change Support

- dev/VSIX/Extension/Cpp/Common/VSPackage.resx
- dev/VSIX/Extension/Cs/Common/VSPackage.resx
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/WinUI.Desktop.CppWinRT.UnitTestApp.vstemplate
The vsix can be built for both 'stable' and 'experimental' releases. The name of the template as displayed in the Visual Studio UI is different across these two flavors. For the experimental build we add 1 to the localized resource id to get the id for the experimental version. 
This is done in `Extension\Directory.Build.targets` by `_ExperimentalVsTemplateXslt`. To make the two new unit test projects work correctly here, I had to update the resource ids and include a string for use by the experimental vsix.
> Visual Studio Template Unit Test App: Fix name and id strings for experimental builds.

- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.vstemplate
This pull request builds upon our ongoing efforts to enhance the WindowsAppSDK by introducing support for .NET 8 and making several key improvements:
**Unit Tests Updated for Portable RIDs:** Modified unit tests to use portable Runtime Identifiers (RIDs), enabling cross-platform compatibility.
**Corrected Publish Profile Path**: Fixed an outdated publish profile path to align with the current project structure.
**Default DotNetVersion Set to 8.0 in Project Templates**: Updated project templates to default to .NET 8.0,
> Enhance WindowsAppSDK with .NET 8 Support & Further Improvements

- BuildAll.ps1
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
Make MrtCore copy its build files (including binlog) to outputDirectory.
> Make MrtCore copy its build files (including binlog) to outputDirectory (2)

- build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
Stop running tests on retired OS images.
------
WARNING:
> Fixing build break by manually porting changes in Main to 1.4-stable

- build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
Start running tests on Win11 23h2 Professional arm64 OS image
--------
WARNING:
> Start running tests on Win11 23h2 Profession arm64 OS image

- build/AzurePipelinesTemplates/WindowsAppSDK-Publish-Stage.yml
[4034](https://github.com/microsoft/WindowsAppSDK/pull/4034) broke the yml.
1) Two Stages had the same name
2) A job in a stage needs to have zero dependencies
> Nightly Build Break Fixes 

- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.vstemplate
**Issue**: The current XML configuration in our project file uses a less-than sign (<) in the Condition attribute for RuntimeIdentifiers. This syntax is causing XML parsing errors because the less-than sign is interpreted as the start of a new tag.
**Solution**: This pull request resolves the XML parsing issue by replacing the less-than sign (<) with its XML entity equivalent &lt;. This change ensures that the XML parser correctly interprets the character as part of the attribute value, rather than as XML syntax.
The reference to the `NuGetPackageInstaller` WizardExtension is also removed as the Dynamic Retrieval logic has not been cherry-picked into a release branch from `main`
> Fix XML Syntax Error in RuntimeIdentifiers Conditions

- .gitmodules
- BuildAll.ps1
- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
The relative path in the submodules to the Aggregator is causing issues. 
Because Foundation is public, I've failed to consider the implications of having a submodule to a private repository.
> Revert Building Mock WindowsAppSDK and SubModules

- dev/MRTCore/mrt/Core/src/MRM.cpp
- dev/UndockedRegFreeWinRT/UndockedRegFreeWinRT-AutoInitializer.cs
- dev/UndockedRegFreeWinRT/catalog.cpp
PublishSingleFile creates a self-extracting exe that deposits embedded files into a temporary folder.  As noted in #2597, this causes dll SxS redirection issues, as well as resources.pri lookup issues.  The support here (which requires coordinated changes in aggregator) sets a base directory env var, which is used to configure the generated self-contained app.manifest entries to enable custom SxS redirection via the undocumented loadFrom attribute, e.g.:
`<asmv3:file name="microsoft.ui.xaml.dll" loadFrom="%MICROSOFT_WINDOWSAPPRUNTIME_BASE_DIRECTORY%microsoft.ui.xaml.dll">`
> PublishSingleFile dll and resources.pri redirection support

- dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.vstemplate
- dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WinUI.Desktop.CppWinRT.WapProj.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/WinUI.Desktop.CppWinRT.UnitTestApp.vstemplate
- dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.vstemplate
Fixes the incorrect casing of WinUI in the project templates:
This regression was introduced by https://github.com/microsoft/WindowsAppSDK/pull/3745
> Fix casing of ProjectTypeTag

- dev/Common/IsWindowsVersion.h
- test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj
- test/DynamicDependency/Test_Win32/Test_Win32.cpp
- test/DynamicDependency/Test_Win32/Test_Win32.h
- test/DynamicDependency/Test_Win32/pch.h
- test/DynamicDependency/Test_WinRT/DynamicDependency_Test_WinRT.vcxproj
- test/DynamicDependency/Test_WinRT/Test_WinRT.cpp
- test/DynamicDependency/Test_WinRT/Test_WinRT.h
- test/DynamicDependency/Test_WinRT/pch.h
- test/inc/WindowsAppRuntime.Test.TAEF.h
Temporarily skip test case FullLifecycle_FilePathLifetime_Frameworks_WindowsAppRuntime_MathAdd_Elevated() to unblock pipeline runs.
---------
WARNING:
> 48525090 - Skipping a test case to temporarily avoid hitting this bug

- build/WindowsAppSDK-Foundation-PR.yml
- dev/MRTCore/mrt/Core/src/MRM.cpp
- dev/UndockedRegFreeWinRT/UndockedRegFreeWinRT-AutoInitializer.cs
- dev/UndockedRegFreeWinRT/catalog.cpp
Reverting https://github.com/microsoft/WindowsAppSDK/pull/4067
Due to failure in the ingestion
> REVERT: PublishSingleFile dll and resources.pri redirection support

- dev/MRTCore/mrt/Core/src/MRM.cpp
- dev/UndockedRegFreeWinRT/UndockedRegFreeWinRT-AutoInitializer.cs
- dev/UndockedRegFreeWinRT/catalog.cpp
PublishSingleFile creates a self-extracting exe that deposits embedded files into a temporary folder. As noted in https://github.com/microsoft/WindowsAppSDK/issues/2597, this causes dll SxS redirection issues, as well as resources.pri lookup issues. The support here (which requires coordinated changes in aggregator) sets a base directory env var, which is used to configure the generated self-contained app.manifest entries to enable custom SxS redirection via the undocumented loadFrom attribute, e.g.:
<asmv3:file name="microsoft.ui.xaml.dll" loadFrom="%MICROSOFT_WINDOWSAPPRUNTIME_BASE_DIRECTORY%microsoft.ui.xaml.dll">
> Cherry-pick  PublishSingleFile dll and resources.pri redirection support 

- build/WindowsAppSDK-CommonVariables.yml
- build/WindowsAppSDK-Versions.yml
> Bump version to 1.6 and set build to experimental

- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
This PR removes the line
`<AssemblyName Condition="'$(EnableExperimentalVSIXFeatures)'=='true'">$(BaseAssemblyName).Experimental</AssemblyName>` from our Azure DevOps XAML build configuration. This change addresses a critical issue where experimental builds append .Experimental to DLL names, causing VSIX load failures in projects using the WindowsAppSDK.Cs.Extension.Dev17.dll. The removal ensures consistent DLL naming and reliable VSIX loading across all build types. Testing confirms no adverse effects on experimental or standard builds, enhancing overall development experience and pipeline stability.
>  Resolve VSIX Load Failure in Experimental Builds

- build/WindowsAppSDK-SyncMirroredRepository.yml
- build/WindowsAppSDK-SyncTrigger.yml
In order to trigger Foundation-ES-SyncMirrorRepos, this PR stands up a new Foundation-ES-SyncMirrorReposTrigger that will be triggered on CI for main and release/* branches. 
Foundation-ES-SyncMirrorRepos will be setup to run on build completion of Foundation-ES-SyncMirrorReposTrigger on main and release/*branches. 
Documentation [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops) states [Default branch for manual and scheduled builds](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-default-branch?view=azure-devops) is ran when build completion is triggered which in our case is the main branch.
> CI trigger Foundation-ES-SyncMirrorRepos via Trigger Pipeline

- specs/applicationdata/ApplicationData.md
ApplicationData APIs comparable to those in namespaces [Windows.Storage](https://learn.microsoft.com/uwp/api/windows.storage) and [Windows.Management.Core](https://learn.microsoft.com/uwp/api/windows.management.core) but with additional functionality, improved developer experience and performance optimizations.
Issue #2639
Microsoft-internal tasks [22308619](https://task.ms/22308619), [30002314](https://task.ms/30002314), [39401257](https://task.ms/39401257), [39414843](https://task.ms/39414843), [40050113](https://task.ms/40050113) and [48332357](https://task.ms/48332357).
> Microsoft.Storage.ApplicationData API Spec

- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WapProjTemplate.wapproj
The <PublishProfile> path in the project file has been updated to match the newly adopted portable Runtime Identifier (RID). It has been changed from win10-$(Platform).pubxml to win-$(Platform).pubxml.
> Update to Publish Profile Path for Portable RIDs in Wapproj Template

- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WapProjTemplate.wapproj
This change adds https://github.com/microsoft/WindowsAppSDK/pull/4141 into release/1.4-stable.
> Cherry-pick commit a6d41bf from main to release/1.4-stable

- dev/MRTCore/packaging/MrtCore.PriGen.targets
(Addresses https://github.com/microsoft/microsoft-ui-xaml/issues/8857)
The MRT Core targets are incorrectly merging the PRIs of references into the final PRI in all cases. Suppose you have Package A which contains some WinUI controls, which results in some XBFs being inserted as resources into its PRI. There is also a Package B that relies on Package A version 1.0. Finally, there is an App C that relies on both Package A (version 1.1) and Package B. Because Package B is including the PRI resources from Package A version 1.0 in its own PRI, when App C attempts to merge the PRI resources from all of its dependencies a conflict will arise and break the build.
Package B should not be including the PRI resources from Package A in its own PRI, and instead should advertise the dependency and …
> Libraries should not merge PRIs from references into their own PRI

- dev/MRTCore/packaging/MrtCore.PriGen.targets
(Addresses https://github.com/microsoft/microsoft-ui-xaml/issues/8857)
The MRT Core targets are incorrectly merging the PRIs of references into the final PRI in all cases. Suppose you have Package A which contains some WinUI controls, which results in some XBFs being inserted as resources into its PRI. There is also a Package B that relies on Package A version 1.0. Finally, there is an App C that relies on both Package A (version 1.1) and Package B. Because Package B is including the PRI resources from Package A version 1.0 in its own PRI, when App C attempts to merge the PRI resources from all of its dependencies a conflict will arise and break the build.
Package B should not be including the PRI resources from Package A in its own PRI, and instead should advertise the dependency and …
> [Cherry pick][WinAppSDK 1.5] Only merge PRIs from references if the project is producing an executable

- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
Async SDL stages were recently deployed to our pipelines.
But due to issues with ArtifactNames not resolving and the stages not being able to download artifacts as a result, we'll disable them to avoid getting orange check marks.
> Disable Async SDL Stage Due to Issues with Artifact Name Recognition

- dev/MRTCore/packaging/MrtCore.PriGen.targets
(Addresses https://github.com/microsoft/microsoft-ui-xaml/issues/8857)
The MRT Core targets are incorrectly merging the PRIs of references into the final PRI in all cases. Suppose you have Package A which contains some WinUI controls, which results in some XBFs being inserted as resources into its PRI. There is also a Package B that relies on Package A version 1.0. Finally, there is an App C that relies on both Package A (version 1.1) and Package B. Because Package B is including the PRI resources from Package A version 1.0 in its own PRI, when App C attempts to merge the PRI resources from all of its dependencies a conflict will arise and break the build.
Package B should not be including the PRI resources from Package A in its own PRI, and instead should advertise the dependency and …
> [WinAppSDK 1.4 Servicing] Libraries should not merge PRIs from references into their own PRI

- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Resolved an issue where MSBuild incorrectly searched the entire filesystem for `NuGet.VisualStudio.dll` due to an undefined path property. The solution was to add the `PackageReference` with `GeneratePathProperty="true"` for `NuGet.VisualStudio` earlier, ensuring the correct path is available and scoped for targeted file search.
> Fix NuGet.VisualStudio DLL Discovery in MSBuild

- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x86.pubxml
The unit tests do not work with PublishTrimmed=true. So building the unit test project in Release configuration will result in the tests no working. 
The fix is to set PublishTrimmed=false unconditionally instead of basing it on the Configuration.
> C# Unit Test Project: Set PublishTrimmed =false even in Release mode.

- dev/Projections/CS/Microsoft.Windows.Management.Deployment.Projection/Microsoft.Windows.Management.Deployment.Projection.csproj
Microsoft.Windows.Management.Deployment.Projection.csproj was using 2nd `<CSRWinRTIncludes>` to resolve the DynDep type dependency when that's a singular 'namespace of the project's output' so the projection had DynDep types and not PkgMgmt. Changed it to a `<ProjectReference Include=...\DynDep.csproj>` and happiness.
Verified projection assembly content via ILSpy.
KUDOS to Steve Otteson for the magic incantation!
> Fixed Microsoft.Windows.Management.Deployment.Projection.csproj

- dev/Projections/CS/Microsoft.Windows.Management.Deployment.Projection/Microsoft.Windows.Management.Deployment.Projection.csproj
Microsoft.Windows.Management.Deployment.Projection.csproj had a 2nd <CSRWinRTIncludes> to resolve the DynDep type dependency when that property is a singular 'namespace of the project's output' so the projection had DynDep types and not PkgMgmt. Changed it to a <ProjectReference Include=...\DynDep.csproj> and happiness.
Verified projection assembly content via ILSpy.
KUDOS to Steve Otteson for the magic incantation!
https://task.ms/48917378
cherry-pick b82d1edbb9d9e8390c53b82a2812041befb8aab5
> [1.5 servicing] Fixed Microsoft.Windows.Management.Deployment.Projection.csproj

- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x86.pubxml
Cherry Pick of #4175 to release/1.5-stable.
The unit tests do not work with PublishTrimmed=true. So building the unit test project in Release configuration will result in the tests no working.
The fix is to set PublishTrimmed=false unconditionally instead of basing it on the Configuration.
> [CP to 1.5] C# Unit Test Project: Set PublishTrimmed =false even in Release mode

- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
- build/ProjectReunion-BuildFoundation.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
> Fix Publish symbols to Public Servers not using a PAT

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
- build/WindowsAppSDK-Versions.yml
Enabled compiler version override on the 2 main .sln files being built on this repo, by injecting a call to the WinUndockNativeCompiler task.
How tested: 
In the draft pipeline run: [https://microsoft.visualstudio.com/ProjectReunion/_build/results?buildId=90033170&view=results](url), both .sln files were built using the LKG compiler instead of the pre-existing compiler on the VM.
WARNING:
and run the build against your PR branch …
> 45977412: [Compliance] Enable compiler version override on the 2 main .sln files being built on this repo 

- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
- build/ProjectReunion-BuildFoundation.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
* Use PAT
* Use - group: PublicSymbols-Secrets
* Add to public pipleine
WARNING:
> [Cherrypick 1.5] Fix Publish symbols to Public Servers not using a PAT

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildTransportPackage-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-PackNuget-Steps.yml
- build/ProjectReunion-BuildFoundation.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
> [Cherrypick 1.4] Fix Publish symbols to Public Servers not using a PAT

- build/WindowsAppSDK-SyncMirroredRepository.yml
- build/WindowsAppSDK-SyncTrigger.yml
I initially thought the triggers to sync the release branches was due to a config issue. But turns out it was because I had not port the yml file that was required for the trigger to the release branches. So the trigger pipeline couldn't run.
> [Cherrypick] CI trigger Foundation-ES-SyncMirrorRepos via Trigger Pipeline

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
- build/WindowsAppSDK-Versions.yml
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/4178
Enabled compiler version override on the 2 main .sln files being built on this repo, by injecting a call to the WinUndockNativeCompiler task.
How tested:
In the draft pipeline run: [https://microsoft.visualstudio.com/ProjectReunion/_build/results?buildId=90033170&view=results](https://github.com/microsoft/WindowsAppSDK/pull/url), both .sln files were built using the LKG compiler instead of the pre-existing compiler on the VM.
WARNING: …
> 45977412: [Compliance] Enable compiler version override on the 2 main .sln files being built on this repo (Cherrypick)

- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
MSBuild incorrectly searched the entire filesystem for NuGet.VisualStudio.dll due to an undefined path property.  The fix outlined in https://github.com/microsoft/WindowsAppSDK/pull/4166 was not working as PkgNuget_VisualStudio was undefined at that point, so an exhaustive search was still happening. This addresses that problem.
> Regression with NuGet.VisualStudio DLL Discovery in MSBuild 

- dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.csproj
- dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.csproj
- dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.csproj
- dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.csproj
- dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.csproj
- dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.csproj
- dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.csproj
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.csproj
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.csproj
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.csproj
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.csproj
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/WinUI.Desktop.CppWinRT.UnitTestApp.csproj
- dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.csproj
The build is unable to find this, but there was never impact of not finding it since it was not used.
Removing it.
> Remove unneeded references to VisualStudio.CoreUtility

- build/ProjectReunion-BuildFoundation.yml
- build/ProjectReunion-CI.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
- build/WindowsAppSDK-Versions.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-GlobalVariables.yml
Following the pattern already in use on the Agg and Closed repos, factored out the LKG package info from the local
WindowsAppSDK-Versions.yml, and extract that info from the recently introduced global copy
eng/common/AzurePipelinesTemplates/WindowsAppSDK-GlobalVariables.yml instead.
The copy in this PR was manually fetched from the Agg repo, because the sync is currently not working.
How tested:
- PR validation is in progress
- Verified in the logs of the PR validation pipeline run, the LKG compiler is being used to build the main .sln file and the mrtcore .sln file.
----
WARNING:
For status …
> 45977412: [Compliance] On the WindowsAppSDK repo, switch over to reference the LKG package info from a global source

- dev/MRTCore/packaging/MrtCore.PriGen.targets
This PR addresses an inconsistency in `MrtCore.PriGen.targets` where the default `RuntimeIdentifiers` were set to non-portable RIDs, irrespective of the .NET version being targeted. The change aligns the default RIDs with the .NET version specified in the project's TargetFramework.
The previous logic incorrectly defaulted to non-portable RIDs, which was not compatible with .NET 8's portable RIDs. .NET 8 and later support simplified, portable RIDs like win-x86, win-x64, and win-arm64, rendering the more specific win10-* RIDs unnecessary. This update ensures that `MrtCore.PriGen.targets` defaults to the correct set of RIDs based on the targeted .NET version:
> Align MrtCore.PriGen.targets with NET8 Runtime Identifier Defaults

- docs/pull_request_template.md
This reverts commit 0b3c0da393f667fec85c6e62d5a7b1114045784d.
WARNING:
PullRequest from Forks will also fail to trigger validation.
Please create your PullRequest directly on the repository.
> Revert "Update PR Template MD to warn about PullRequests on Forks"

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
To eliminate the use of our PAT in ProjectReunionInternal service connection
> Remove ProjectReunionInternal Service Connection in NuGetAuthenticate taks

- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-AnyCPU-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
Enabled automated APIScan and PREfast scans.
This a straight port of a [`reviewed PR`](https://dev.azure.com/microsoft/ProjectReunion/_git/WindowsAppSDK/pullrequest/10567664?path=/build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml).
PREFast:
- There are pre-existing errors, to avoid breaking the pipelines, disabled the "break on error" setting until those errors are resolved.
- Focus on scanning x64fre as a start.
APIScan:
- There are pre-existing errors, to avoid breaking the pipelines, disabled the "break on error" setting until those errors are resolved.
- Pointed APIScan to a APIScanTarget folder where we put binaries to be scanned. This allows us to exclude files and folders from being scanned.
Genera notes:
- The non-OneBranch public pipeline does not seem to support …
> 49601674: [Compliance] Enabled automated APIScan and PREfast scanning

- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
- dev/AppLifecycle/RedirectionRequestQueue.h
- dev/Deployment/DeploymentManager.cpp
- dev/Deployment/DeploymentTraceLogging.h
- dev/DeploymentAgent/main.cpp
- dev/MRTCore/mrt/mrm/UnitTests/DecisionInfo.UnitTests.cpp
- dev/MRTCore/mrt/mrm/UnitTests/ResourceMap.UnitTests.cpp
- dev/MRTCore/mrt/mrm/UnitTests/ResourceReference.UnitTests.cpp
- dev/MRTCore/mrt/mrm/UnitTests/TestLinks.cpp
- dev/MRTCore/mrt/mrm/UnitTests/TestReverseMap.cpp
- dev/MRTCore/mrt/mrm/UnitTests/UnifiedView.UnitTests.cpp
- dev/MRTCore/mrt/mrm/UnitTests/Util.UnitTests.cpp
- dev/MRTCore/mrt/mrm/UnitTests/testEnvironment.cpp
- dev/MRTCore/mrt/mrm/UnitTests/testHSchema.cpp
- dev/MRTCore/mrt/mrm/UnitTests/testMap.cpp
- dev/MRTCore/mrt/mrm/UnitTests/testPri.cpp
- dev/MRTCore/mrt/mrm/UnitTests/testQualifier.cpp
- dev/MRTCore/mrt/mrm/UnitTests/testUtils.cpp
- dev/MRTCore/mrt/mrm/include/mrm/platform/CoreQualifierTypes.h
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapTracelogging.h
- installer/dev/console.cpp
- installer/dev/tracelogging.h
Addressed the pre-existing errors reported by PREfast, thus allowing us to enable the "break the build on errors" setting for PREfast. 
Testing was done in the corresponding internal pipeline, the pipeline build was successful with the "break on error" setting. 
PR validation has succeeded.
----
WARNING:
> 49601674: [Compliance] address pre-existing PREfast errors and enable break-on-error setting for PREfast

- installer/dev/console.cpp
Fixed a cut-and-paste error not caught by this PR validation pipeline but caught later by the internal aggregator pipeline while building the Installer.
----
WARNING:
> 49601674: Fixed a cut-and-paste error

- dev/VSIX/Extension/Cpp/Dev17/WizardImplementationCpp.cs
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.vstemplate
This pull request delivers a critical fix to the `WizardImplementationCpp.cs` file, enhancing the NuGet package installation mechanism for C++ projects. The improvement detects the project type via the project's GUID. For `vcxproj` (C++ project files), it bypasses the previously used `SolutionRestoreFinished` event and directly invokes `InstallNugetPackagesAsync`. This ensures both SingleProject C++ and Wapproj C++ projects receive timely and efficient NuGet package installations during project creation, effectively tailoring the process to the project type and optimizing performance.
> NuGet Installation Optimization for C++ Project Templates 

- dev/MRTCore/packaging/MrtCore.PriGen.targets
This is causing a build break in some cases for .NET 8.
> Remove win-arm from RuntimeIdentifiers

- dev/MRTCore/packaging/MrtCore.PriGen.targets
Fixing the other half (.NET 6 and 7) to remove arm.  Also, arm64 was missing for some reason.
> add win10-arm64; remove win10-arm

- dev/Deployment/DeploymentManager.cpp
- dev/Deployment/DeploymentManager.h
A recent prefast bug fix initialized an _Out_ variable athat was actually an _InOut_, so that the initialization clobbered the existing value. The parameter was not being used as an out param, so the correct fix is to change it to a const.
> Fix initialization of _InOut_ variable

- dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/BlankWindow.xaml
- dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/BlankWindow.xaml.cs
- dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/BlankWindow.h
- dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/BlankWindow.xaml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/MainWindow.xaml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/MainWindow.xaml.cs
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/MainWindow.xaml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/MainWindow.xaml.cs
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/UnitTestApp.xaml.cs
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/UnitTestAppWindow.xaml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/UnitTestAppWindow.xaml.cs
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/MainWindow.h
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/MainWindow.xaml
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/MainWindow.h
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/MainWindow.xaml
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/MainWindow.cpp
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/MainWindow.xaml
It is doing 2 things.
1. reverts #4035 Add custom titlebar to default Cs and Cpp WinUI template as there are changes coming later which will address some of the issues this PR was trying to solve, but better.
2. Adds window title in default template. As a result, every window will have a title by default, which would be name of the project (app).
Obviously, the user can choose to change it by using `<Title>` markdown in Window or `Window.Title` api, if they wish.
Solving https://task.ms/50309832
> Reverts changes to default titlebar template and add a Window title to it

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-AnyCPU-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
Exclude the \Packages folder from PREfast scans, as we are adopting the policy of "each repo should focus on scanning its own bits". These changes are already in use in WinUI pipelines, just porting them to the Foundation pipelines
.
--------------
WARNING:
> 49601674: Exclude the \Packages folder from PREfast scans

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-AnyCPU-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
Fixed the cut-and-paste error in the previous PR for this bug.
----
WARNING:
> 49601674: Fixing the previous PR

- dev/Deployment/DeploymentManager.cpp
- dev/UndockedRegFreeWinRT/typeresolution.cpp
This reverts commit 8d366d91b7d786a8130f307bd52286d45c46effc.
We're getting some test failures due to this line, because phstrMetaDataFilePath can be null:
RETURN_IF_FAILED(WindowsCreateString(L"", 0, phstrMetaDataFilePath));
> Fix a test failure due to WindowsCreateString error

- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
`$DotNetVersion$` was accidentally removed when changing the project template to installl NuGet packages dynamically. This change reintroduces it.
> Class Library $DotNetVersion$ fix

- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/WinUI.Desktop.CppWinRT.UnitTestApp.vstemplate
Changed the preferred solution configuration from `Debug|x86` to `Debug|x64` in the project template to align with the target platform requirements.
> Changing Default Platform to x64

- build/CopyFilesToStagingDir.ps1
- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x86.pubxml
This update refactors the project configuration to exclusively use portable runtime identifiers (`win-x86`, `win-x64`, `win-arm64`), aligning with .[NET 8’s default behavior](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/rid-graph) and eliminating non-portable runtime identifiers (`win10-x86`, `win10-x64`, `win10-arm64`). This change simplifies the setup, reduces maintenance overhead, and prevents the [NETSDK1206](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1206) warning by removing non-portable RIDs​.
For new projects targeting .NET 8 or higher, this configuration will work seamlessly. However, users with existing projects targeting .NET 7, using older project templates, and relying on the Microsoft.WinAppRuntime.Bootstrap.dll in unpackaged …
> Refactor Runtime Identifiers to Support .NET 8 and higher by default

- .github/policies/resourceManagement.yml
Mirror most of the policy changes from microsoft/microsoft-ui-xaml#9071:
* Added descriptions to the different rules to make it clearer what each one does.
* Added a new rule to add needs-triage to new or re-opened Issues.
* Added a new rule to add needs-triage tag to Issues that get commented on after they are Closed.
Changed some labels to match the microsoft-ui-xaml policy:
* Use "needs-triage" instead of "needs-triage :mag:".
* Use "no-recent-activity" instead of "status-no recent activity".
* Use "needs-author-feedback" instead of "needs-author feedback".
A few labels were added and updated accordingly.
There are still a few differences from the microsoft-ui-xaml policy:
* This preserves a policy to close issues labelled as "duplicate".
* This doesn't add three "Pull_Request" rules …
> Update GitHub ResourceManagement policy yml

- build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
With this PR: remove conditional support for < NET 8 and get rid of assets under Wi… · microsoft/WindowsAppSDK@8b6c0f8 (github.com) , Microsoft.WindowsAppRuntime.Bootstrap.dll is no longer being copied to the nonportable RID runtime folder (win10-arch)
> Copy Microsoft.WindowsAppRuntime.Bootstrap.dll from portable RID folder

- build/CopyFilesToStagingDir.ps1
- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x86.pubxml
Reverts microsoft/WindowsAppSDK#4425
> Revert "Refactor Runtime Identifiers to Support .NET 8 and higher by default"

- dev/Projections/Directory.Build.props
- eng/common/VersionInfo/AssemblyInfo.cs
- eng/common/VersionInfo/GenerateVersionInfo.ps1
We have `IsTrimmable` set in our projection projects.  But this doesn't show up in the resulting assembly as an assembly attribute.  This turns out it is due to at some point we started using a custom `AssemblyInfo.cs` which meant the attribute that was generated in the default one is no longer there.  While checking the assembly I also noticed the `IIDOptimizer` is inserting a type that is unused given nothing needs to be optimized and that the vtable lookup generation table was generated because CsWinRT failed to properly detect this as a projection project.  So, disabling those with the respective properties to control them.
WARNING:
Please see pipeline …
> Fix missing trimming annotation and set couple cswinrt properties

- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
There is an issue with versioning collision if the release branch is run on both nightly and official pipeline because the $PipelineType variable is only tagged on to the version on the main branch.
While the original intent was that the release would only run on official, this is not always the case and does not match reality.
The fix is to always tag on the $PipelineType variable to the versioning no matter what branch. 
We also don't need to condition on the develop branch anymore so this is archaic.
> Remove condition for develop and main branch on versioning and always add $(PipelineType) to the tag

- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
Enable APIScan according to parameters.runStaticAnalysis, instead of hardwiring it to be always enabled.
How built:
- The changes built successfully in a [private pipeline run](https://microsoft.visualstudio.com/ProjectReunion/_build/results?buildId=99974019&view=results)
How tested:
- When parameters.runStaticAnalysis is set to true, APIScan was enabled as expected in a successful [private pipeline run](https://microsoft.visualstudio.com/ProjectReunion/_build/results?buildId=99976947&view=results)
- When parameters.runStaticAnalysis is set to false, APIScan was disabled as expected in a successful [private pipeline run](https://microsoft.visualstudio.com/ProjectReunion/_build/results?buildId=99974019&view=results)
---
A microsoft employee must use /azp run to validate using the pipelines …
> [BuildFix] Fix APIScan config to properly honor parameters.runStaticAnalysis

- .config/tsaoptions.json
Update tsaoptions.json to update area path for TSA bug filing.
CP of [PR #4464](https://github.com/microsoft/WindowsAppSDK/pull/4464) to 1.4
--
WARNING:
> Update tsaoptions.json (#4464)

- .config/tsaoptions.json
Update tsaoptions.json to update area path for TSA bug filing.
CP of [PR #4464](https://github.com/microsoft/WindowsAppSDK/pull/4464) to 1.6
--
WARNING:
> Update tsaoptions.json to update area path for TSA bug filing.

- .config/tsaoptions.json
Update tsaoptions.json to update area path for TSA bug filing.
CP of [PR #4464](https://github.com/microsoft/WindowsAppSDK/pull/4464) to 1.5
--
WARNING:
> Update tsaoptions.json to update area path for TSA bug filing

- build/ProjectReunion-BuildFoundation.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
Originally used in Symbols Publishing but is no longer needed
> Remove unused variable group: PublicSymbols-Secrets

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-AnyCPU-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
This template uses ESRPCodeSigningTask to version 5 which eliminates the use of secrets from the App Registration by using Federated Credentials.
> Update ESRPCodeSigningTask to Version 5; Use WindowsAppSDK-EsrpCodeSigning-Steps.yml From WindowsAppSDKConfig Repository

- dev/PowerNotifications/PowerNotifications.h
This is a fix for PowerNotifications' Suspend Status callback throwing an exception. 
This was due to the code resetting the status and throwing an exception if the status is checked before it has been set/after it had been reset. The error here was that since there are multiple suspend callbacks from the system, the status was being reset before there was a chance to read it. The fix removes the resetting of the status as it isn't needed.
Fixes:
#2833
> [PowerNotifications] Suspend status fix

- build/AzurePipelinesTemplates/WindowsAppSDK-CallTouchDownBuild-Steps.yml
Update TouchdownBuildTask to Version 4 which eliminates the use of secrets by moving to using federated credentails
Switched our TDBuild registration to use an existing ProjectReunion App registration that already has a federated credentials setup
Migration guide:
https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/touchdown-build/apis-and-integration/touchdown-build-azure-devops-task/touchdown-build-azure-devops-task-migration
> Update TouchdownBuildTask to Version 4 

- test/PackageManager/API/PackageDeploymentManagerTests_IsPackageRegistrationPending.cpp
Nightly build is running into failures 
https://microsoft.visualstudio.com/ProjectReunion/_build/results?buildId=102381838&view=logs&j=1c272cb4-a7de-5c81-98c5-aeeff8319ee2&t=48f8fc41-e087-5792-5dca-ac677875ff2f
##[error]70. PREfast Error C6216 - File: file:///C:/__w/1/s/test/PackageManager/API/PackageDeploymentManagerTests_IsPackageRegistrationPending.cpp. Line: 160. Column 13. 
This PR resolves this prefast issue. 
Validation run here
https://microsoft.visualstudio.com/ProjectReunion/_build/results?buildId=102392887&view=results
> Fix C6216 on PackageDeploymentManagerTests_IsPackageRegistrationPending.cpp

- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
Switching away from the outgoing symweb to Cloud symweb.
Similar changes have been made to internal repos.
///////////////
WARNING:
> 51996148: switch to Cloud symweb

- BuildAll.ps1
- TestAll.ps1
- build/CopyFilesToStagingDir.ps1
- build/NuSpecs/build-nupkg.ps1
- build/ShouldSkipPRBuild.ps1
- build/StripSymbols.ps1
- build/scripts/ConvertVersionDetailsToPackageConfig.ps1
- build/scripts/Install-WindowsSdkISO.ps1
- build/scripts/windows-sdk.ps1
- dev/MRTCore/build/DownloadDotNetCoreSdk.ps1
- dev/MRTCore/build/Initialize-InstallMSBuild.ps1
- eng/common/Scripts/ConvertVersionDetailsToPackageConfig.ps1
- eng/common/Scripts/GetLKGCompilerPackageInfoIfNeeded.ps1
- eng/common/Scripts/MaestroGetRequest.ps1
- eng/common/Scripts/MaestroHelpers.ps1
- eng/common/Scripts/MaestroPostRequest.ps1
- eng/common/Scripts/PublishPublicSymbols.ps1
- eng/common/Scripts/StripSymbols.ps1
- eng/common/Scripts/UpdateVersionDetailsConfig.ps1
- eng/common/VersionInfo/GenerateVersionInfo.ps1
- tools/GenerateDynamicDependencyOverrides.ps1
- tools/GeneratePushNotificationsOverrides.ps1
- tools/TerminalVelocity/Generate-TerminalVelocityFeatures.ps1
- tools/VerifyCopyrightHeaders.ps1
b#48614111:  Add "break on error" setting to the top of powershell scripts in WASDK
With this PR, "break on error" is enabled everywhere except for 2 small blocks in 2 ps1 files, which are being tracked by 2 separate bugs.
//////////
WARNING:
> b#48614111:  Add "break on error" setting to the top of powershell scripts in WASDK

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-PublishSymbol-Steps.yml
Updated BuildInstaller Template to allowed to be used from a OneBranch pipeline
Updated template to include
-ESRPCodeSigning step
-PublishSymbols step
-SDL Analysis step
Refactored the PublishSymbols step from other templates into
build/AzurePipelinesTemplates/WindowsAppSDK-PublishSymbol-Steps.yml
> Allow use of WindowsAppSDK-BuildInstaller-Steps.yml from the WindowsAppSDKAggregator Repository

- eng/common/Scripts/MaestroHelpers.ps1
Fixed pre-existing "array index out of bound" bug in a Powershell script, exposed by enabling strict mode 3.0.
PR validation passed.
///////////////////
WARNING:
> [Build] Fixing pre-existing "array out of bound" bug exposed by enabling strict mode 3.0

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
> Fix trailing quote when passing in folder path in Installer Template

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
A nightly could fail in the test stages but succeeds in the Aggregator stage. 
This change allows it so the Foundation build can still download the WindowsAppSDK Nuget package even if the build partially fail.
> Allow Installer validation stage to download from a build that has failed

- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x86.pubxml
Based on repro steps provided here:
https://github.com/microsoft/microsoft-ui-xaml/issues/9740
RuntimeIdentifier(s) are already provided in the ProjectTemplate.csproj file.
> Remove RuntimeIdentifier elements from publish profiles - they don't work

- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/App.xaml.cs
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/App.xaml.cs
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/UnitTestApp.xaml.cs
[Nullable reference types](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references) states:
"Beginning with .NET 6, new projects include the <Nullable>enable</Nullable> element in all project templates."
Following suit with WinAppSDK C# templates, and addressing warning on m_window.
> Enable nullable reference types on new projects (.NET guidance) and fix warning

- build/ProjectReunion-BuildFoundation.yml
Disabling Installer Validation Stage.
A simple failure in the Aggregator stage will bring the PR validation down.
> Disabling Installer Validation Stage

- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
[CVE-2024-30105](https://github.com/advisories/GHSA-hh2w-p6rv-4g7w) applies to .NET Core projects, not .NET FX.  Adding an override here anyway to get resolve component governance failure.
> Override System.Text.Json version to work around false positive CVE-2024-30105

- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.csproj
The conditional logic for `PublishReadyToRun` and `PublishTrimmed` properties was moved from the `.pubxml` files to the project file, ensuring proper configuration for Debug and Release builds regardless of the platform.
> Move Conditional Logic from .pubxml to Project Files

- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.csproj
This change fixes   #4552 and places the Publish Properties in the appropriate file
> Placing Publish Properties in Appropriate File

- eng/common/AzurePipelinesTemplates/WindowsAppSDK-GlobalVariables.yml
Updated from LKG16 to LKG17.
///////////////////////////////
WARNING:
> 51915845: Update WindowsAppSDK-GlobalVariables.yml to move from LKG16 to LKG17

- eng/common/AzurePipelinesTemplates/WindowsAppSDK-GlobalVariables.yml
Updated WindowsAppSDK-GlobalVariables.yml to move from LKG16 to LKG17.
////////////
WARNING:
> 51915845: [1.6] Migrate from LKG16 to LKG17

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
- build/ProjectReunion-BuildFoundation.yml
Reenable Installer Validation where instead of downloading from the latest main branch, we download from the latest official build which is controlled by two pipeline variables.
This should give us more stability in the validation.
> Reenable Installer Validation using Latest Official WindowsAppSDK builds

- specs/mrtcore/PrimaryLanguageOverride/PrimaryLanguageOverride.md
Changing the application language using [PrimaryLanguageOverride](https://learn.microsoft.com/uwp/api/windows.globalization.applicationlanguages.primarylanguageoverride) property from `Windows.Globalization.ApplicationLanguages` namespace is not supported for WindowsAppSDK un-packaged apps, only for packaged. To support language change for unpackaged applications `Microsoft.Windows.Globalization.ApplicationLanguages` type is introduced in
MRTCore. `Microsoft.Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride` property is supported both for packaged and unpackaged WindowsAppSDK apps.
WARNING:
Please see pipeline link to verify that the build …
> [mrtcore] Microsoft.Windows.Globalization.ApplicationLanguages API specs

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
Fix ExtractWindowsAppSDKVersion deleting the NuGet Package that the VSIX build needs by copying it to a temporary location and extracting it from there
> Fix ExtractWindowsAppSDKVersion deleting the NuGet Package

- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
Corrected the `IsPackageDeploymentFeatureSupported()` checks for `IsPackageReadyOrNewerAvailable` (available on some platforms), `ResetPackage` (not available; vNext) and `RepairPackage` (not available; vNext)
Once in will be brought to shiproom for 1.6 approval
This corrects checks to address KNOWN ISSUES in [PackageDeploymentManager: IsReadyOrNewerAvailable(), FrameworkUdk update, Implement not-implemented functions, Tests!](https://github.com/microsoft/WindowsAppSDK/pull/4453)
#4453 
https://task.ms/52754253
> Fix IsPackageDeploymentFeatureSupported

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/ResourceContext.cpp
(Original PR:  #4604)
Sync between old and new API. If old one (Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride) was set more recently than the new one (Microsoft.Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride), also update the new one to the latest value.
Only do this for packaged apps, as Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride is not supported for unpackaged apps.
(cherry picked from commit aaa39d5e70937d39f76bab8e585e485e0ea7cb15)
WARNING: …
> [MRTCore] Sync between WGA.PrimaryLanguageOverride and MWGA.PrimaryLanguageOverride

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
- dev/WindowsAppRuntime_DLL/packages.config
- test/ApplicationData/packages.config
- test/PackageManager/API/packages.config
- test/PackageManager/data/PackageManager.Test.M.Black.msix/packages.config
- test/PackageManager/data/PackageManager.Test.M.Blacker.msix/packages.config
- test/PackageManager/data/PackageManager.Test.M.White.msix/packages.config
- test/PackageManager/data/PackageManager.Test.M.Whiter.msix/packages.config
cherry-pick 1cd3034c41f33fd1cb0775967e429765b3ebe5f4 from main
[Fix IsPackageDeploymentFeatureSupported (#4598)](https://github.com/microsoft/WindowsAppSDK/pull/4598)
ALSO: DevCheck -SyncDependencies to update stale dependency references reported by DevCheck -CheckDependencies
> 1.6-stable: cherry-pick Fix IsPackageDeploymentFeatureSupported (#4598)

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/ResourceContext.cpp
Sync between old and new API. If old one (Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride) was set more recently than the new one (Microsoft.Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride), also update the new one to the latest value.
Only do this for packaged apps, as Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride is not supported for unpackaged apps.
(cherry picked from commit aaa39d5e70937d39f76bab8e585e485e0ea7cb15)
Co-authored-by: Stefan Markovic <stefan@janeasystems.com>
(cherry picked from commit 68ffb095b3de98fb6fd11c3898dea7bec4fff978)
WARNING:
Please see pipeline link to verify that the …
> [Cherry-pick][WinAppSDK 1.6] [MRTCore] Sync between WGA.PrimaryLanguageOverride and MWGA.PrimaryLanguageOverride

- build/CopyFilesToStagingDir.ps1
This PR addresses a warning that occurs when targeting .NET 8 in projects using the `Microsoft.WindowsAppSDK`. The warning, identified as NETSDK1206, is triggered due to the use of version-specific or distribution-specific runtime identifiers (RIDs) like `win10-arm64`, `win10-x64`, and `win10-x86`. In .NET 8 and higher, these RIDs are not recognized by default, leading to potential issues in locating necessary assets. The runtime identifier paths have been modified from `win10-$Platform` to `win-$Platform` to align with the new RID scheme in .NET 8.
> Update Runtime Identifier Paths for Compatibility with .NET 8

- Directory.Packages.props
- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Define the package versions centrally using PackageVersion tags instead of setting the verisons on PackageReference tags.
> [release/1.4-stable] Define package versions centrally

- specs/CameraCaptureUI/CameraCaptureUI.md
@Saharsh979, this updates the formatting of your spec to [this template](https://github.com/microsoft/WindowsAppSDK/blob/main/specs/spec_template.md), OK of we use this? The changes mainly:
* Aligns the L1 section headings
* L2 headings to align with public doc pages. (Each member in the docs is its own page, so each is an L2 rather than L3)
* Try to keep lines at 100 columns
> Update to template format

- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
We need to call TerminalVelocity to properly remove experimental APIs from stable builds.
> [1.6-stable] Add AppData Terminal Velocity call to yml

- build/CopyFilesToStagingDir.ps1
Reverting #4612  as it is causing failures in pipeline tests.
> Revert #4612 (NETSDK1206 Fix)

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
> Fix ExtractWindowsAppSDKVersion to only look at WindowsAppSDK nupkg

- dev/PackageManager/API/PackageManager.idl
https://task.ms/53375777
```
static Boolean IsPackageDeploymentFeatureSupported(PackageDeploymentFeature feature);
Boolean IsPackageRegistrationPending(String packageFullName);
Boolean IsPackageRegistrationPendingForUser(String userSecurityId, String packageFullName);
```
Should be prefixed with [contract(PackageDeploymentContract, 2)]
NOTE: Also backporting to 1.6
> New PackageDeploymentManager methods not tagged with new v2 contract

- dev/ApplicationData/M.W.S.ApplicationData.cpp
- specs/applicationdata/ApplicationData.md
- test/ApplicationData/ApplicationDataTests.cpp
Per Chris Wall `MachineFolder` path should be `%ProgramData%\Microsoft\Windows\AppRepository\Families\ApplicationData\...pkgfamilyname...\Machine` (that ...\Families\... directory was missing)
> Fix ApplicationData.MachineFolder path

- Directory.Build.props
This repository is mirrored onto an internal Azure DevOps repository that is used for building Windows App SDK releases. This has the unfortunate side effect of embedding into the PDB symbols Source Link information that points at the internal AzDO repo rather than this public Github repo. This change addresses that by adding a custom target that corrects the repo URL that Source Link uses.
Fixes #4633.
> Fix Source Link information so it points to Github rather than internal AzDO mirror

- dev/PackageManager/API/PackageManager.idl
cherry-pick New PackageDeploymentManager methods not tagged with new v2 contract #4663
https://github.com/microsoft/WindowsAppSDK/pull/4663
> 1.6 New PackageDeploymentManager methods not tagged with new v2 contract

- Directory.Build.props
This repository is mirrored onto an internal Azure DevOps repository that is used for building Windows App SDK releases. This has the unfortunate side effect of embedding into the PDB symbols Source Link information that points at the internal AzDO repo rather than this public Github repo. This change addresses that by adding a custom target that corrects the repo URL that Source Link uses.
Fixes #4633.
(cherry picked from commit a820af7d83902a7c6bc396c193caca3d03704591)
> [Cherry-pick][Windows App SDK 1.6] Fix Source Link information so it points to Github rather than internal AzDO mirror

- Directory.Packages.props
- dev/VSIX/Directory.Build.props
Cherry pick from https://github.com/microsoft/WindowsAppSDK/pull/4674
For the projects under the VSIX folder, the build stopped honoring the "Directory.Packages.props" file at the root of the repo. This causes us to pick up old versions of all these packages, and hilarity ensues.
I'm not sure at the moment what caused this change in behavior, but this fix looks safe as we continue to investigate.
> [CP to main] Fix centrally-versioned package references

- build/CopyFilesToStagingDir.ps1
- build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
This PR addresses a warning that occurs when targeting .NET 8 in projects using the Microsoft.WindowsAppSDK. The warning, identified as NETSDK1206, is triggered due to the use of version-specific or distribution-specific runtime identifiers (RIDs) like win10-arm64, win10-x64, and win10-x86. In .NET 8 and higher, these RIDs are not recognized by default, leading to potential issues in locating necessary assets. The runtime identifier paths have been modified from win10-$Platform to win-$Platform to align with the new RID scheme in .NET 8.
> NETSDK1206 Fix

- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x86.pubxml
This PR resolves the `NETSDK1032` error ("_The RuntimeIdentifier platform 'win-x64' and the PlatformTarget 'x86' must be compatible_") encountered when building and publishing WinUI 3 applications with multiple target architectures.
**Context:**
The error occurred on x64 and arm64 machines when selecting both x86 and x64 packages or when building C# WinUI 3 apps with .NET 9.0 set to x64 or x86 platforms.
**Fix:**
To resolve the issue, the RuntimeIdentifier (RID) has been reintroduced in the pubxml file, explicitly setting it to win-{arch} to ensure compatibility between the target platform and architecture. Conditional RIDs have also been removed across all project templates in favour of non-portable RIDs.
> Reintroduce Runtime Identifier in Pubxml to Resolve Platform Mismatch

- dev/WindowsAppRuntime_DLL/packages.config
- eng/common/DevCheck.ps1
- test/PackageManager/API/packages.config
New options
* -Settings => Load the settings file (if exists) to enable future customization (default=$True)
* -SettingsFile=file => Settings file to load (default = ...repo...\.user\DevCheck-Settings.ps1)
* -SaveSettingsFile=file => Save a default settings file (fail if exists; won't overwrite existing files)
* -UserSettings => Load the user settings file (if exists) to enable future customization (default=$True)
* -UserSettingsFile=file => User Settings file to load (default = ...repo...\.user\DevCheck-Settings.ps1)
* -SaveUserSettingsFile=file => Save a default user settings file (fail if exists; won't overwrite existing files)
Settings file is for a project to customize behavior. User Settings file is per user to mess with.
NOTE: A future update will change the default location for …
> DevCheck: Settings options, configuration dependency paths, Sync'd dependencies

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/ResourceContext.cpp
Unfortunately, `Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride` relies on an internal API that throws an exception if no language override has been set. Even though this exception is expected and caught further up the stack, this can cause an incredible amount of noise in the debugger if it's configured to break on thrown exceptions. As a result, it is necessary to revert #4608 (which allows `Microsoft.Globalization.ApplicationLanguages.PrimaryLanguageOverride` to reflect the value of `Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride` if the latter API is used by the app) in order to suppress the noisy exception.
WARNING:
Comments made by azure-pipelines bot maybe …
> Revert "[MRTCore] Sync between WGA.PrimaryLanguageOverride and MWGA.PrimaryLanguageOverride (#4608)"

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/ResourceContext.cpp
Cherry-pick of #4712 to WinAppSDK 1.6.
Original description:
> Unfortunately, `Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride` relies on an internal API that throws an exception if no language override has been set. Even though this exception is expected and caught further up the stack, this can cause an incredible amount of noise in the debugger if it's configured to break on thrown exceptions. As a result, it is necessary to revert #4608 (which allows `Microsoft.Globalization.ApplicationLanguages.PrimaryLanguageOverride` to reflect the value of `Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride` if the latter API is used by the app) in order to suppress the noisy exception.
(cherry picked from commit b9a3c8c6ba9fb96a4c9ff4029b9f29a4ad0210b8)
A …
> [WinAppSDK 1.6] Revert "[MRTCore] Sync between WGA.PrimaryLanguageOverride and MWGA.PrimaryLanguageOverride (#4608)"

- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
Disable auto bug filing via TSA for the 1.6-Stable branch on the Foundation repo, as we focus on enabling TSA for the main branch.
Once this PR has been merged, I will attempt to CP it to 1.5.
----
WARNING:
> 53812687 - Disable auto bug filing via TSA for the 1.6-Stable branch on the Foundation repo

- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
CP the [PR](https://github.com/microsoft/WindowsAppSDK/pull/4727) to 1.5.
////////
WARNING:
> [CP to 1.5] 53812687 - Disable auto bug filing via TSA for the 1.6-Stable branch on the Foundation repo

- dev/Deployment/DeploymentManager.cpp
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
Feel free to suggest some other wording.  The goal is to communicate that "the Windows App Runtime" is no longer synonymous with the Microsoft.WindowsAppRuntime FWP (for the purpose of dependency detection) and includes other FWPs like DDLM.
> clarified error message for when the Microsoft.WindowsAppRuntime FWP alone has been installed (and not DDLM, e.g.)

- BuildAll.ps1
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj.filters
Strictmode was causing the failure below
```
The variable '$WindowsAppSDKVersionProperty' cannot be retrieved because it has not been set.
at <ScriptBlock>, D:\WindowsAppSDK\BuildAll.ps1: line 162
```
The fix was to simply declare the variable outside of the scope.
> Fix BuildAll Error Stemming from StrictMode and Retarget Solution

- build/WindowsAppSDK-CommonVariables.yml
Our build image recently got updated to VS 17.10, which caused some changes and broke a few unit tests. This change rolls our image back to a previous version, that contains VS 17.9.
This is the "1.0.02629.40" image, described on this page:
https://eng.ms/docs/products/onebranch/infrastructureandimages/buildinfrastructureandimages/containerimages/windowsimages/windows2019vse2022/releasenotes
> [WinAppSDK 1.5] Roll back build image to VS 17.9

- build/WindowsAppSDK-SyncTrigger.yml
git push didn't seem to work and I suspect it might be the refs/branch/main from $(Source.BuildBranch)
> Bring back SourceToTargetBranch parameter

- build/WindowsAppSDK-SyncTrigger.yml
This didn't work in the previous PRs but I believe it should work now because refs/heads/ is being stripped
> Use $(Source.BuildBranch) parameter in SyncMirrors

- build/WindowsAppSDK-SyncTrigger.yml
refs/heads should be refs/heads/
Or else the $branch will be set to /main instead of main
> Fix Typo refs/heads/ in SyncMirrors

- .config/tsaoptions.json
The same changes as in [Pull Request 11512903](https://microsoft.visualstudio.com/ProjectReunion/_git/WindowsAppSDKAggregator/pullrequest/11512903?_a=files) but here for the Foundation repo instead.
--
WARNING:
> [Build] Fix obsolete area path for filing TSA bugs on the Foundation repo

- tools/DevCheck/nuspec/Microsoft.WindowsAppSDK.DevCheck.nuspec
According to [this](https://learn.microsoft.com/en-us/nuget/reference/nuspec), the Tags element string is space-delimited, so ',' alone would not split a tag string.
How built:
- These changes will go through PR validation as usual.
How tested:
- The ultimate test is to visually verify that the Tags are shown correctly in the landing page of the related feed.
////
WARNING:
and run the build against your PR branch with the default …
> Bug 54198205: The Tags in nuspec file is wrong on Foundation repo

- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.h
- specs/packagemanager/PackageManagement.md
- test/PackageManager/API/PackageDeploymentManagerTests_Register.cpp
- test/PackageManager/API/PackageManagerTests.Packages.h
`PackageDeploymentManager.RegisterPackageSetAsync()` only registered packages by URIs in the packageset making it the moral equivalent of `Register(uri[])` when it should also support `Register(packagefamilyname[])`. The PackageSet's PackageUri field(s) were required blocking registering by package family name.
`RegisterPackageSetAsync()` now considers PackageUri to be optional. To register packages by family name don't set `PackageUri`
See 3.8.2. PackageSetItem Properties in `specs\packagemanager\PackageManagement.md` for more details
https://task.ms/54517063
> RegisterPackageSetAsync() requires URI when it should be optional to register by PackageFamilyName

- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.h
- specs/packagemanager/PackageManagement.md
- test/PackageManager/API/PackageDeploymentManagerTests_Register.cpp
- test/PackageManager/API/PackageManagerTests.Packages.h
RegisterPackageSetAsync() requires URI when it should be optional to register by PackageFamilyName (#4813)
Backport https://github.com/microsoft/WindowsAppSDK/pull/4813 to 1.6-stable
https://task.ms/54537341
> [1.6 servicing] RegisterPackageSetAsync() requires URI when it should be optional to register by PackageFamilyName

- build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
Currently the references for winmd that comes from WindowsAppSDK nuget package is getting affected by the references mentioned in targets file of WinUI. This change to de-couple the definition of references between both the packages. 
Related Bug: https://task.ms/54538137
> Fix for the winmd references

- specs/BackgroundTask/BackgroundTaskBuilder.md
- specs/WinRT/WinRTAPIContracts.md
This is the API spec doc for BackgroundTaskBuilder API to support Background Task Registration for WinAppSDK apps.
Related Bug Report #3840
> API spec for BackgroundTaskBuilder API

- build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
Currently the references for winmd that comes from WindowsAppSDK nuget package is getting affected by the references mentioned in targets file of WinUI. This change to de-couple the definition of references between both the packages.
Related Bug: https://task.ms/54538137
> Adding reference for DynamicDependency winmd

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
- tools/DevCheck/DevCheck.ps1
> Automatically generate password to avoid using Convert-To-SecureString (Cherry Pick)

- tools/DevCheck/DevCheck.ps1
If `DevCheck` found no TAEF service installed `DevCheck` installs it...but doesn't start it (unlike other cases where `DevCheck` installed the service is also started it).
Kudos to @wcheng-msft for spotting the problem
> DevCheck: Start the TAEFService if we install it

- build/NuSpecs/AppxManifest.xml
UniversalBGTask activation class declaration needs to get added directly in the app package based on status of `WindowsAppSDKBackgroundTask` property, Hence removing it from framework package manifest
> Removing UniversalBGTask Activation class entry from framework manifest

- dev/MRTCore/mrt/Core/src/MRM.cpp
PathCchCombineEx's cchPathOut is a character count, not a byte count.  Result was an occasional crash when PathCchCombineEx would use what it thought was available storage as scratch space, causing a buffer overrun.
> Fix incorrect cch param

- specs/CameraCaptureUI/CameraCaptureUI.md
- specs/WinRT/WinRTAPIContracts.md
This PR includes the following changes:
1) The change updates the CameraCaptureUI specifications doc to include important notes on usage for PhotoSettings and VideoSettings.
2) Added the CameraCaptureUIContract in the WinRT contracts as well.
3) A small update by removing the marshalling=none and threading=STA attributes. These settings were relevant to the UWP version of CameraCapture, but they are no longer applicable in the context of WinAppSDK.
> Updating CameraCaptureUI Spec Doc

- installer/dev/install.cpp
**Issue Description:** 
There is an issue with the installation of DDLM packages, specifically when a newer installer version (e.g., 1.6.1) is run before an older version (e.g., 1.5.7). This sequence causes the DDLM packages to not install for the older version, resulting in a "package not found" error during provisioning. 
**Root Cause:** 
Processing the DDLM package enters a conditional statement due to the stale value for GetExistingPackageIfHigherVersion (set because the singleton packages have already been processed). Consequently, the singleton package is merely re-registered, and the DDLM package is not added when older versions are executed.
**Fix:** 
Once the higher version package has been re-registered or its status is confirmed to be okay, the value for …
> Bug Fix for Cannot install version 1.3: DDLM package not found

- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
- dev/Common/TerminalVelocityFeatures-OAuth.xml
This PR introduces a TerminalVelocity check to control the availability of an experimental feature in the Windows App SDK. The feature is enabled in the Experimental channel, while it remains NOOP'd in the Preview and Stable channels, following the TerminalVelocity guidelines for efficient code stripping.
For more information:
https://github.com/microsoft/WindowsAppSDK/blob/main/docs/Coding-Guidelines/Experimental.md
https://github.com/microsoft/WindowsAppSDK/blob/main/docs/Coding-Guidelines/TerminalVelocity.md
WARNING:
For status checks on the main branch, please use …
> Update TeminalVelocity changes for OAuth2Manager Experimental API

- .github/policies/resourceManagement.yml
This PR adds a trigger action to automatically request diagnostics using FeedbackHub. 
---------------------------------------------------------------------------------------------------------------------------------------
WARNING:
> Add FeedbackHub trigger to WindowsAppSDK repository

- dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
Add `DetourFinishHelperProcess` export to help with `DetourIsHelperProcess()` and avoid stack overflow.
Per https://github.com/microsoft/Detours/wiki/Using-Detours
>...If the DLL may be used in mixed 32-bit and 64-bit environments, then the DllMain function must call the [DetourIsHelperProcess](https://github.com/microsoft/Detours/wiki/DetourIsHelperProcess) API. The DLL must export the [DetourFinishHelperProcess](https://github.com/microsoft/Detours/wiki/DetourFinishHelperProcess) API as export Ordinal 1, which will be called by rundll32.exe to perform the helper tasks.
[DetourFinishHelperProcess](https://github.com/microsoft/Detours/wiki/DetourFinishHelperProcess) implies this is only relevant when cross bit-ness across process creation
>***When creating a 32-bit target process from a …
> Add DetourFinishHelperProcess export

- dev/WindowsAppRuntime_DLL/WindowsAppRuntime.def
Cherry-pick [Add DetourFinishHelperProcess export #4934](https://github.com/microsoft/WindowsAppSDK/pull/4934) to 1.6.x servicing
Add `DetourFinishHelperProcess` export to help with `DetourIsHelperProcess()` and avoid stack overflow.
Per https://github.com/microsoft/Detours/wiki/Using-Detours
>...If the DLL may be used in mixed 32-bit and 64-bit environments, then the DllMain function must call the [DetourIsHelperProcess](https://github.com/microsoft/Detours/wiki/DetourIsHelperProcess) API. The DLL must export the [DetourFinishHelperProcess](https://github.com/microsoft/Detours/wiki/DetourFinishHelperProcess) API as export Ordinal 1, which will be called by rundll32.exe to perform the helper tasks.
[DetourFinishHelperProcess](https://github.com/microsoft/Detours/wiki/DetourFinishHelperProc …
> [1.6 servicing] Add DetourFinishHelperProcess export

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
- tools/DevCheck/DevCheck.ps1
The redist files (DotNet, VCRedist, VCLibs) were being dropped in the local nuget cache folder, packages, resulting in 4GB of unnecessary freight being published and downloaded.
> Use separate folder for publishing redist files, not the nuget package cache

- LkgToolset.props
Fix build break - custom.props in parent directory
WARNING:
> Find custom.props in parent dir

- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
The Packages folder contain binaries that are from external sources. 
We've applied the policy of "each repo should focus on scanning its own binaries" to most other repos, so adding exclusion of the Packages folder to skip BinSkim scans on the Foundation repo.
How verified:
- A private pipeline run shows the Build Stage is successful (no BinSkim errors) with the changes in this PR.
/////
WARNING:
and run the build against your …
> Bug 55435589: MrtCore build now fails due to mrt.gdnsuppress exclusions not being found, due to case sensitive of nuget package cache

- BuildAll.ps1
- Directory.Build.props
- LkgToolset.props
- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-AnyCPU-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
- installer/dev/main.cpp
See:
https://github.com/microsoft/WindowsAppSDK/pull/4933
> Cherry pick LKG/MsUCRT fixes

- installer/dev/install.cpp
Cherry-pick https://github.com/microsoft/WindowsAppSDK/pull/4890 to 1.6.x servicing
Issue Description:
There is an issue with the installation of DDLM packages, specifically when a newer installer version (e.g., 1.6.1) is run before an older version (e.g., 1.5.7). This sequence causes the DDLM packages to not install for the older version, resulting in a "package not found" error during provisioning.
Root Cause:
Processing the DDLM package enters a conditional statement due to the stale value for GetExistingPackageIfHigherVersion (set because the singleton packages have already been processed). Consequently, the singleton package is merely re-registered, and the DDLM package is not added when older versions are executed.
Fix:
Once the higher version package has been re-registered or its …
> [1.6 servicing] Bug Fix for Cannot install version 1.3: DDLM package not found 

- test/TestApps/OAuthTestApp/OAuthTestApp.vcxproj
- test/TestApps/OAuthTestAppPackage/OAuthTestAppPackage.wapproj
> Updating windows SDK version to 10.0

- dev/OAuth/AuthRequestAsyncOperation.cpp
- dev/OAuth/AuthRequestAsyncOperation.h
- dev/OAuth/OAuth.idl
- dev/OAuth/OAuth2Manager.cpp
- dev/OAuth/OAuth2Manager.h
- dev/OAuth/OAuth2ManagerTelemetry.h
- dev/OAuth/TokenRequestParams.cpp
- dev/OAuth/TokenRequestParams.h
- specs/OAuth/OAuth2Manager.md
Removing APIs added for Implicit grant type suggested by security review. 
Implicit grant type is not the recommended way to perform OAuth2.0. Authorization code grant type should be used.
WARNING:
> [OAuth2Manager] Remove APIs for Implicit grant type

- dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.cpp
- dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.h
- dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.idl
- specs/BackgroundTask/BackgroundTaskBuilder.md
TaskGroup property support has been added to the BackgroundTaskBuilder API.
> Added TaskGroup property support to BackgroundTaskBuilder API

- build/NuSpecs/WindowsAppSDK-Nuget-Native.Bootstrap.targets
- build/NuSpecs/WindowsAppSDK-Nuget-Native.DeploymentManager.targets
- build/NuSpecs/WindowsAppSDK-Nuget-Native.UndockedRegFreeWinRT.targets
Add auto initializer targets via `<BeforeClCompileTargets>` (rather than `BeforeTargets="ClCompile"`) to get better timing for picking up added compiler options. This helps to ensure they are added after dynmically-added compiler options, such as `/arm64ec`.
A separate `AddUndockedRegFreeWinRTCppDefines` target was created to ensure those global defines are still added with the same timing they had previously. (I'm not sure if those global defines are required, but that is a question for another day.)
> Switch auto initializer targets to add via BeforeClCompileTargets

- dev/Notifications/BadgeNotifications/BadgeNotificationManager.h
- dev/Notifications/BadgeNotifications/BadgeNotifications.idl
- specs/BadgeNotifications/BadgeNotifications-spec.md
Taskbar does not support expiration of badge functionality, hence removing these API from BadgeNotification
WARNING:
> removing BadgeNotification Expiration API

- build/NuSpecs/AppxManifest.xml
Adding AppNotificationConferencingConfig to AppxManifest.xml
Issue : "the Enhanced UX Notification for Video and Audio Call feature on 1.7-exp2, throws exception from AppNotificationConferencingConfig.IsCallingPreviewSupported() - 80040154 - Class not registered."
WARNING:
> Adding AppNotificationConferencingConfig to AppxManifest.xml

- build/WindowsAppSDK-CommonVariables.yml
Update Agg repo to use latest LKG17 compiler version 19.40.33817100.
Private run of internal WinAppSDK pipeline with these changes was successful.
/////////////
WARNING:
> 54239817 - Update Agg repo to use latest LKG17 compiler version 19.40.33817100

- build/WindowsAppSDK-CommonVariables.yml
This is a straight CP of https://github.com/microsoft/WindowsAppSDK/pull/5042.
///////
WARNING:
> [CP to 1.7] 54239817 - Update Foundation repo to use latest LKG17 compiler version 19.40.33817100

- build/ProjectReunion-BuildFoundation.yml
- build/ProjectReunion-CI.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
Build Number and Version should match.
Currently, the revision number are off by one.
Change is validated on the OneBranch pipelines.
WARNING:
> Match Build Number and Version

- dev/Common/TerminalVelocityFeatures-CameraCaptureUI.xml
- dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUI.h
- dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUI.idl
- test/CameraCaptureUITests/APITests.cpp
This PR removes the TerminalVelocity mechanism from the CameraCaptureUI API, which was previously used to control its visibility across different release channels (Preview, Stable, Experimental). As the feature is now moving towards broader availability (**Preview Release**) and no longer needs the experimental feature flagging, we are removing the TerminalVelocity-related checks.
The API has gone through spec-review:  https://github.com/microsoft/WindowsAppSDK/pull/4721
> Removing terminal velocity from CameraCaptureUI

- dev/Common/TerminalVelocityFeatures-BackgroundTask.xml
As [spec](https://github.com/microsoft/WindowsAppSDK/blob/main/specs/BackgroundTask/BackgroundTaskBuilder.md) had gone through review and we haven't seen any feedbacks regarding API surface, we are good with enabling the APIs for stable release
> Setting BackgroundTask API as AlwaysEnabled

- dev/Common/TerminalVelocityFeatures-OAuth.xml
- dev/OAuth/AuthRequestParams.cpp
- dev/OAuth/ClientAuthentication.cpp
- dev/OAuth/OAuth.idl
- dev/OAuth/OAuth2Manager.cpp
- dev/OAuth/TokenRequestParams.cpp
- dev/OAuth/common.h
- test/OAuth2ManagerTests/OAuth2APITests.cpp
This PR removes the TerminalVelocity mechanism from the OAuth2Manager API, which was previously used to control its visibility across different release channels (Preview, Stable, Experimental). As the feature is now moving towards broader availability (Preview Release) and no longer needs the experimental feature flagging, we are removing the TerminalVelocity-related checks.
The API has gone through spec-review: #4772 
WARNING: …
> Remove terminal velocity feature tag from OAuth2Manager APIs, enabling for stable release

- Directory.Packages.props
- dev/WindowsAppRuntime_DLL/packages.config
- test/CameraCaptureUITests/packages.config
- test/OAuth2ManagerTests/packages.config
- test/PackageManager/API/packages.config
This is a mitigation. A real fix for these to use the version.details.xml coming soon.
WARNING:
> Update IXP in hardcoded packages.config

- build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
Validated in internal runs. 
> Brian Barthel
> Submitted at 2025-01-28 05:39:22 PST
> So I took a look at the run with debug logs and interestingly it doesn't show the machine being under any particular memory pressure when it was throwing OOM:
> 
> ##[debug]Agent environment resources - Disk: D:\ Available 148641.40 MB out of 153598.00 MB, Memory: Used 4792.00 MB out of 16380.00 MB, CPU: Usage 100.00%
> 
> 
> That doesn't really strike me as problematic memory usage.  At the beginning of the download it showed 3904.00 MB used so it doesn't appear to be going wild and even with only 8gb memory it isn't overwhelming the system.  This memory usage also follows the same pattern as the successful downloads.
> 
> Another thing that could be tried is to reduce the parallelism by setting the …
> Fix DownloadPipelineArtifacts Failing With System.OutOfMemoryException on Arm64 Testjobs

- build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
- build/scripts/Install-WindowsSdkISO.ps1
…n on Arm64 Testjobs (#5080)
Also cherrypick of 
https://github.com/microsoft/WindowsAppSDK/pull/5020
> Fix DownloadPipelineArtifacts Failing With System.OutOfMemoryException on Arm64 Testjobs; Update Install-WindowsSdkISO.ps1 to use new FW links

- dev/Common/TerminalVelocityFeatures-BadgeNotifications.xml
- dev/Notifications/BadgeNotifications/BadgeNotifications.idl
This PR removes the TerminalVelocity mechanism from the Badge NotificationAPI, which was previously used to control its visibility across different release channels (Preview, Stable, Experimental). As the feature is now moving towards broader availability (Preview Release) and no longer needs the experimental feature flagging, we are removing the TerminalVelocity-related checks.
API Spec PR - https://github.com/microsoft/WindowsAppSDK/pull/4823
WARNING:
(https://microsoft.visualstudio.com/ProjectReunion/_build?definit …
> Remove terminal velocity feature tag from Badge Notification APIs, enabling it for stable release

- Directory.Packages.props
- dev/WindowsAppRuntime_DLL/packages.config
- test/CameraCaptureUITests/packages.config
- test/OAuth2ManagerTests/packages.config
- test/PackageManager/API/packages.config
The hardcoded versions are going to get stale since Maestro isnt able to update these!
This PR adds FrameworkUDK and IXP to Central Package Management by adding them to Directory.Packages.props. Additionally, hardcoded package references have been removed from packages.config to align with best practices.
https://task.ms/55990470
> Adding IXP & FrameworkUDK to Central Package Management

- specs/Compatibility/CompatibilityOptions.md
- specs/Compatibility/RuntimeCompatibilityOptions.md
Spec for app-configurable compatibility options, which can be set via `RuntimeCompatibilityOptions` APIs or via project properties.
> App-configurable compatibility options spec: RuntimeCompatibilityOptions

- dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUITelemetry.h
This PR updates CameraCaptureUI telemetry to critical to ensure we collect complete data on its reliability and usage.
> Marking CameraCaptureUI Telemetry as Critical 

- dev/OAuth/OAuth2ManagerTelemetry.h
Make Telemetry Critical event for OAuth2Manager.
WARNING:
> [OAuth2Manager]: Make Telemetry Critical

- dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.idl
> [Cherry-pick to 1.7] Removed TerminalVelocity usages from IDL

- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
- dev/AppNotifications/AppNotificationConferencingConfig.cpp
> [1.7] Fix TerminalVelocityFeatures-CallingPreviewSupport.h to be generated. #5108

- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
- dev/AppNotifications/AppNotificationConferencingConfig.cpp
TerminalVelocityFeatures-CallingPreviewSupport.h is not correctly being generated today, resulting in the velocity having the wrong state in preview/stable. Add the proper generation.
> Fix TerminalVelocityFeatures-CallingPreviewSupport.h to be generated.

- dev/OAuth/OAuth2ManagerTelemetry.h
Making the telemetry for OAuth2Manager Critical.
WARNING:
> [Cherry-pick to 1.7]Making the telemetry for OAuth2Manager Critical.

- dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.cpp
- dev/PushNotifications/PushNotificationsLongRunningTask/NotificationListener.h
These changes are done to support CTA compliance for unpackaged apps using notifications. For CTA we need to attribute data used by unpackaged apps for notifications in SRUM DB. Since unpackaged app does not have an identity (e.g - AppUserModuleId). SRUM uses ProcessName to attribute data to unpackaged apps
WARNING:
> Unpackaged App CTA compliance code changes

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-Steps.yml
Reducing the number of binaries we feed to APIscan, to void the recent problem of APIScan hitting timeout failure.
After last Tuesday, APIScan started hitting timeout error because the number of binaries to scan increased from 331 to 367.
This PR reduces the number of binaries to scan to 217, by skipping 1) arm/arm64 binaries, 2) test binaries, 3) TAEF binaries.
A private pipeline run showed that APIScan no longer hit the timeout error.
//////////////////////////////
WARNING: …
> [Build] Update WindowsAppSDK-BuildFoundation-Steps.yml

- tools/DevCheck/DevCheck.ps1
- Previously, the script checked multiple sources for an existing password, including a stored password file (winappsdk.certificate.test.pwd).
- Now, the function warns if a pre-existing password file is found but does not attempt to reuse it.
- This was done as we don't see any scenario where we would run DevCheck twice and reuse the password.
- If passwords were read from the files, the existing change would have triggered exceptions in the pipelines, which we haven't seen.
- Also, if we try to convert the plain text password from the file to securestring, we will hit PSAvoidUsingConvertToSecureStringWithPlainText error.
> Removed Handling for Pre-Existing Password Files

- test/BadgeNotificationTest/BadgeNotification.testdef
- test/BadgeNotificationTest/BadgeNotificationTest.vcxproj
- test/BadgeNotificationTest/BadgeNotificationTest.vcxproj.filters
- test/BadgeNotificationTest/BadgeNotifications-AppxManifest.xml
- test/BadgeNotificationTest/PackagedTests.cpp
- test/BadgeNotificationTest/resource.h
The changes involve onboarding unit tests for the BadgeNotification API to run as part of the pipeline test runs (Checkin, Nightly, and Release).
Testing - In the build pipeline all tests are passing
WARNING:
> BadgeNotification: Onboarding Unit tests to the pipeline test runs

- dev/Interop/StoragePickers/PickerCommon.cpp
The application should fallback to PickerLocationId.Documents when the specified folder does not exist.
This is also consistent with the behavior of the existing pickers (Windows.Storage.Pickers).
> Fallback to the Documents Library when the specified SuggestedStartLocation doesn't exist on end user's environment

- build/WindowsAppSDK-CommonVariables.yml
Upgrade the Foundation repo to use the latest LKG18 native compiler.
Similar changes have been applied to the Closed repo.
How tested:
- The PR validation pipeline run is successful. Verified that LKG18 was used to build the product.
/////
WARNING:
> 56138352 - Upgrade the Foundation repo to use the latest LKG18 native compiler

- dev/WindowsAppRuntime_UniversalBGTaskDLL/Task.cpp
- dev/WindowsAppRuntime_UniversalBGTaskDLL/Task.h
In case `CoCreateInstance` fails, currently backgroundtaskhost process terminates with access violation, this change is to throw the right exception before termination which helps in debugging.
> Throw right exception in case of CoCreateInstance failure

- specs/StoragePickers/FileOpenPicker.md
- specs/StoragePickers/FileSavePicker.md
- specs/StoragePickers/FolderPicker.md
- specs/StoragePickers/Microsoft.Windows.Storage.Pickers.md
- specs/StoragePickers/PickFileResult.md
- specs/StoragePickers/PickFolderResult.md
- specs/StoragePickers/PickerLocationId.md
- specs/StoragePickers/PickerViewMode.md
The public Spec for `Microsoft.Windows.Storage.Pickers`
Preview: [Microsoft.Windows.Storage.Pickers.md](https://github.com/microsoft/WindowsAppSDK/blob/user/DinahK-2SO/storage_pickers_public_spec/specs/StoragePickers/Microsoft.Windows.Storage.Pickers.md)
The code is also open for review. Find PR: #5240
> Public Spec for Microsoft.Windows.Storage.Pickers

- dev/AppNotifications/AppNotificationConferencingConfig.cpp
**What Changed?**
Adding implementation for IsCallingPreviewSupported method. The implementation could call the Framework Udk method to check if feature is enabled on the user's OS.
**Why is this change required?**
Currently this method always returns false.
Original PR : https://github.com/microsoft/WindowsAppSDK/pull/4783
WARNING:
> Adding implementation for IsCallingPreviewSupported method

- tools/DevCheck/DevCheck.ps1
Fix Install-TAEFService using wrong path to Wex.Sevice.exe
Add -RemoveTAEFService to uninstall the TAEF service (if installed).
> Fix Install-TAEFService using wrong path to Wex.Sevice.exe

- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
- dev/PackageManager/API/PackageManager.Containment.h
- dev/PackageManager/API/PackageManager.vcxitems
- dev/PackageManager/API/PackageManager.vcxitems.filters
- dev/PackageManager/API/pch.h
- dev/WindowsAppRuntime_DLL/pch.h
56439870: A/B Containment for EnsurePackage*ReadyAsync() doesn't register v2 if v1 is registered and caller asks for minVersion=v1
Adds A/B Containment for [[1.7] EnsurePackage*ReadyAsync() doesn't register v2 if v1 is registered and caller asks for minVersion=v1 #5182 #5191](https://github.com/microsoft/WindowsAppSDK/pull/5191)
https://task.ms/56439870
> [1.7] 56439870: A/B Containment for EnsurePackage*ReadyAsync()

- installer/dev/tracelogging.cpp
This updates the WIL failure events in the installer to include the same Tracelogging tags and fields used elsewhere in the installer flow.
What's changed:
- Added TelemetryPrivacyDataTag and TraceLoggingKeyword to FailureLog, Exception, FailFast, and FailureReturn events so they show up properly in logs.
- Included _GENERIC_PARTB_FIELDS_ENABLED for version/channel/debug info to match other logged events like Install/Start.
- Replaced direct TraceLoggingCountedWideString(...) calls with the existing WindowsAppRuntimeInstaller_TraceLoggingWString(...) macro for consistency and readability.
These events should now appear as expected in Kusto, with consistent structure and tagging across the installer.
> Add TraceLogging tagging and generic fields to failure events. 

- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
- build/ProjectReunion-BuildFoundation.yml
- build/ProjectReunion-CI.yml
- build/WindowsAppSDK-CommonVariables.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
The new yml file WindowsAppSDK-SetSourceBranchVariableForConfigRepo.yml on the Config repo specifies the global default LKG compiler version. Use that version information, which is branch-specific, unless a different LKG compiler version is specified by the local file WindowsAppSDK-CommonVariables.yml.
How built:
- These changes have passed PR validation
How tested:
Using internal private pipeline runs, verified that:
- Populating WindowsAppSDK-CommonVariables.yml with a different LKG compiler version supersedes the global default LKG compiler version, although that resulted in unrelated build issues due to mismatch of build tool versions.
- An auto triggered pull request pipeline run can succeed.
- Manual re-run of an auto-triggered pull request pipeline run can succeed.
- Manual trigger …
> Task 56847091: [WASDK][Compliance] Update the WindowsAppSDK repo to use the global default LKG compiler version on the Config repo 

- installer/dev/tracelogging.cpp
Backport of https://github.com/microsoft/WindowsAppSDK/pull/5283
This updates the WIL failure events in the installer to include the same Tracelogging tags and fields used elsewhere in the installer flow.
What's changed:
Added TelemetryPrivacyDataTag and TraceLoggingKeyword to FailureLog, Exception, FailFast, and FailureReturn events so they show up properly in logs.
Included _GENERIC_PARTB_FIELDS_ENABLED for version/channel/debug info to match other logged events like Install/Start.
Replaced direct TraceLoggingCountedWideString(...) calls with the existing WindowsAppRuntimeInstaller_TraceLoggingWString(...) macro for consistency and readability.
These events should now appear as expected in Kusto, with consistent structure and tagging across the installer.
> [1.7] Add TraceLogging tagging and generic fields to failure events.

- installer/dev/tracelogging.cpp
Backport of https://github.com/microsoft/WindowsAppSDK/pull/5283
This updates the WIL failure events in the installer to include the same Tracelogging tags and fields used elsewhere in the installer flow.
What's changed:
Added TelemetryPrivacyDataTag and TraceLoggingKeyword to FailureLog, Exception, FailFast, and FailureReturn events so they show up properly in logs.
Included _GENERIC_PARTB_FIELDS_ENABLED for version/channel/debug info to match other logged events like Install/Start.
Replaced direct TraceLoggingCountedWideString(...) calls with the existing WindowsAppRuntimeInstaller_TraceLoggingWString(...) macro for consistency and readability.
These events should now appear as expected in Kusto, with consistent structure and tagging across the installer.
> [1.6] Add TraceLogging tagging and generic fields to failure events.

- installer/dev/tracelogging.cpp
Backport of https://github.com/microsoft/WindowsAppSDK/pull/5283
This updates the WIL failure events in the installer to include the same Tracelogging tags and fields used elsewhere in the installer flow.
What's changed:
Added TelemetryPrivacyDataTag and TraceLoggingKeyword to FailureLog, Exception, FailFast, and FailureReturn events so they show up properly in logs.
Included _GENERIC_PARTB_FIELDS_ENABLED for version/channel/debug info to match other logged events like Install/Start.
Replaced direct TraceLoggingCountedWideString(...) calls with the existing WindowsAppRuntimeInstaller_TraceLoggingWString(...) macro for consistency and readability.
These events should now appear as expected in Kusto, with consistent structure and tagging across the installer.
> [1.8] Add TraceLogging tagging and generic fields to failure events.

- dev/AppLifecycle/ExtensionContract.h
- dev/AppLifecycle/FileActivatedEventArgs.h
- test/AppLifecycle/FunctionalTests.cpp
For unpackaged App, when opening a file with type registered with [RegisterForFileTypeActivation()](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.windows.applifecycle.activationregistrationmanager.registerforfiletypeactivation?view=windows-app-sdk-1.6), current design is to execute the app with encoded protocol as argument (`----ms-protocol:ms-encodedlaunch:App?ContractId=Windows.File&Verb=open&File=%1`)
E.g.
`"C:\MyApp.exe" "----ms-protocol:ms-encodedlaunch:App?ContractId=Windows.File&Verb=open&File=C:\myfile.foo"`
The expectation is when the app calls `GetActivatedEventArgs()`, the returned value should has a type of `ExtendedActivationKind.File` with file path/name in the data.
However, when the file path contains unicode characters or special characters like …
> [Issue #3871] File activation for unpackaged App would fail when file path contains unicode characters or special characters

- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.h
- dev/PackageManager/API/PackageManagerTelemetry.h
!cherry-pick 0562da1
!cherry-pick 3c17287
* PackageDeploymentManager - Fix .Stop() events not being generated. Include PackageReadyOrNewerAvailableStatus in .Stop() events. [#5278](https://github.com/microsoft/WindowsAppSDK/pull/5278)
* PackageDeploymentManager - Add missing .Stop() event on CompletedSuccess [#5284](https://github.com/microsoft/WindowsAppSDK/pull/5284)
https://task.ms/56951078
> [1.6 servicing] PackageDeploymentManager - Fix .Stop() events not being generated. Include PackageReadyOrNewerAvailableStatus in .Stop() events

- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.h
- dev/PackageManager/API/PackageManagerTelemetry.h
!cherry-pick 0562da1
!cherry-pick 3c17287
* PackageDeploymentManager - Fix .Stop() events not being generated. Include PackageReadyOrNewerAvailableStatus in .Stop() events. [#5278](https://github.com/microsoft/WindowsAppSDK/pull/5278)
* PackageDeploymentManager - Add missing .Stop() event on CompletedSuccess [#5284](https://github.com/microsoft/WindowsAppSDK/pull/5284)
https://task.ms/56951092
> [1.7 servicing] PackageDeploymentManager - Fix .Stop() events not being generated. Include PackageReadyOrNewerAvailableStatus in .Stop() events

- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
The temporarily workaround is simply creating an empty folder for Guardian PREfast to find, so it would stop throwing the "folder not found" error, which the pipeline run currently treats as non-fatal.
But these non-fatal errors are noisy, plaguing Foundation repo pipelines.
Because our Foundation pipelines currently set isNativeCode to false, while that value being true is a pre-requisite for running Guardian PREfast, hence at least in theory, the Guardian PREfast task shouldn't even run in the first place, but it did any way.
AFAICT, when the Guardian PREfast task 1) starts honoring its own isNativeCode pre-requisite and not run unless the pre-req is met, or 2) return to pre-Mar 17, 2025 behavior and stop throwing "folder not found" errors when the pre-req isn't even met, then we can …
> [Build] Eliminate non-fatal PREfast errors with a temporarily workaround

- eng/Version.Details.xml
Reverts microsoft/WindowsAppSDK#5329
As WinUI repo has test issue with newer version of IXP (1.9.0-CI-26108.1805.250410-1448.0)
> Revert "[main] Update dependencies from microsoft/LiftedIXP/DCPP"

- build/WindowsAppSDK-TDBuild.yml
Upgrade OS image from MMS2019 to MMS2022 to reduce dependency on the not well maintained public image MMS2019.
Once we get ride of all references to MMS2019 in WinAppSDK yml files, we can remove the MMS2019 image from our 1ES hosted pool.
The MMS2019 OS image is only being used in ProjectReunionESPool. Only 2 places in WinAppSDK's code is using ProjectReunionESPool, this one, and another instance in the WindowsAppSDKArcadeServices repo.
///////////
WARNING:
(https://microsoft.visualstudio.com/ProjectReunion/_build?def …
> Task 57156413: [SFI][GetSecure] Vulnerability Management - Redeploy With Updated Code References - 4 issues in MMS2019 

- WindowsAppRuntime.sln
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
Bootstrapper uses the Win11 OS DynamicDependency API when available but should only do so for versions of WinAppSDK using the OS API, i.e. WinAppSDK >= 1.7
Also fixed a dependency build order issue
NOTE: This fix is for main/1.8. A separate PR will fix 1.7 per https://task.ms/57143286
> Fix Bootstrapper only use Win11 DynamicDependency API if available AND WinAppSDK target >= 1.7

- BuildAll.ps1
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
- build/NuSpecs/Microsoft.WindowsAppSDK.Bootstrap.CS.targets
- build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.TransportPackage.nuspec
- build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.TransportPackage.props
- build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.TransportPackage.targets
- build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.nuspec
- build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.props
- build/NuSpecs/Microsoft.WindowsAppSDK.Foundation.targets
- build/NuSpecs/WindowsAppSDK-Nuget-Native.Bootstrap.targets
- build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
- build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
- build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
- build/NuSpecs/package.appxfragment
- build/scripts/CopyContents.ps1
- build/scripts/RobocopyWrapper.ps1
- dev/MRTCore/packaging/native/MrtCore.C.props
Adding Microsoft.WindowsAppSDK.Foundation as another way to consume the foundation APIs.
Ensure both the preview way and this way works by using `WindowsAppSDKAggregatePackage` to pivot in shared targets.
WARNING:
> Adding Microsoft.WindowsAppSDK.Foundation

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
> Add binlog for msbuild invoke

- dev/Interop/StoragePickers/FileOpenPicker.cpp
- dev/Interop/StoragePickers/FileSavePicker.cpp
- dev/Interop/StoragePickers/FolderPicker.cpp
This pull request fixes the context parameter used when creating file dialog instances across multiple picker implementations to ensure using the intended context. Specifically, we're replacing `CONTEXT_ALL` with `CLSCTX_INPROC_SERVER` - fixing an error causes the storage pickers to fail to launch on ARM64 devices, throwing error "Class not registered"
This issue did not appear on x64 machines because the value of CONTEXT_ALL on x64 machines happens to be the same as that of CLSCTX_INPROC_SERVER. However, these two values differ on ARM64, thereby exposing the problem during bug bash on ARM64 devices.
* [`dev/Interop/StoragePickers/FileOpenPicker.cpp`](diffhunk://#diff-919dfd32a08a1aa703097fd0fe1b95dd36e0164229d91a3e22e194c7d015187eL90-R90): Replaced `CONTEXT_ALL` with …
> Bugfix - Storage Pickers cannot launch on ARM64

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
As we add more packages, the regex matching previously done doesn't scale.  So instead, I am changing the regex check to correctly match with the WinAppSDK package rather than other packages with the same prefix.
WARNING:
> Fix regex matching for getting the WinAppSDK version number in a generic way

- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-AnyCPU-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
- build/ProjectReunion-CI.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
- eng/common/DevCheck.ps1
This PR contains:
- changes to DevCheck.ps1 that are a wholesale copy of the DevCheck.ps1 from main.
- remove all NuGetToolInstaller tasks
- cherrypick of [5324](https://github.com/microsoft/WindowsAppSDK/pull/5324)
WARNING:
> Remove NuGetToolInstaller Tasks; Update DevCheck

- eng/Version.Details.xml
> Use older IXP package version to produce release candidate

- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Per-Platform-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
This is to address an issue caused by my previous PR #5364, which fails the [foundation nightly build](https://dev.azure.com/microsoft/ProjectReunion/_build/results?buildId=122095756&view=results) due to duplicate artifact publish (PREfast stage uploads once, and the normal build stage uploads another time)
Current fix is to assign a separate artifact base name for PREfast stage
> [Pipeline] Rename artifact base for PREfast stages

- .config/tsaoptions.json
The old area path is no longer valid, replacing it with valid new area path.
///////////
WARNING:
> [Build] Updated area path for filing TSA bugs on WindowsAppSDK repo, per recent re-org

- .gdn/OneBranch.gdnsuppress
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
If not suppressed, these BinSkim BA2004 warnings will break our OneBranch pipelines due to a policy change on May 14, 2025.
We cannot fix these on our side, because our complier command line already contains the '/ZH:SHA_256' that the instruction for the error BA2004 asks us to add. 
The fact that each of these warnings is only for x86 or only for arm64, but not for other architectures (we pretty much use the same compiler command line containing '/ZH:SHA_256' across all 3 architectures), might imply that these are false positives. 
Therefore, suppressing them for ~3 months to avoid breaking the pipelines for now.
Revisit / renew as needed after ~3 months.
How built:
- These changes will go through PR validation as usual.
How tested:
- In private run of the Foundation OneBranch pipeline, …
> [Build] Suppressing 10 BinSkim BA2004 warnings on the Foundation repo

- .config/tsaoptions.json
This is a straight CP of the following PR from main to 1.8:
- [[Build] Updated area path for filing TSA bugs on WindowsAppSDK repo, per recent re-org by alexlamtest · Pull Request #5411 · microsoft/WindowsAppSDK](https://github.com/microsoft/WindowsAppSDK/pull/5411)
////////////////////////
WARNING:
> [CP to 1.8][Build] Updated area path for filing TSA bugs on WindowsAppSDK repo

- .config/tsaoptions.json
Straight forward CP of the following PR from main to 1.7:
- https://github.com/microsoft/WindowsAppSDK/pull/5411
///////////////
WARNING:
> [CP to 1.7][Build] Updated area path for filing TSA bugs on WindowsAppSDK repo 

- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Per-Platform-Stage.yml
When APIScan (or PREfast) is enabled, building Foundation for each architecture currently takes ~1.5 hrs, resulting in timeout error due to hitting the 120 min limit for jobs.
Avoiding the timeout error by setting a higher time limit when APIScan (or PREfast) enabled.
How built:
- These changes will go through PR validation as usual.
How tested:
- In a private run of the Foundation nightly pipeline, the build jobs doing APIScan all passed, e.g., with elapsed time 2hr 28 sec, i.e., this would have hit the original timeout limit of 120 min causing the pipeline run to fail.
/////////////////////////
WARNING:
Please see pipeline link to verify that the build is …
> [Build] Avoid pipeline break due to timeout error by increasing the job time limit when APIScan is enabled

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-Steps.yml
Currently [Foundation Nightly Build](https://dev.azure.com/microsoft/ProjectReunion/_build?definitionId=117346&_a=summary) is broken due to API Scan timeout. 
It is caused by #5375 which adds [the following files](https://dev.azure.com/microsoft/ProjectReunion/_build/results?buildId=122254004&view=logs&j=1d94a253-0a42-5ee8-5aa9-69e4b17444cb&t=854fa6be-0731-5cfb-be0c-f78accbc7b81) to be included in API Scan:
```
BuildOutput\Release\x64\DecimalCalculator_CS\DecimalCalculator_CS.dll
BuildOutput\Release\x64\DecimalCalculator_CS\DecimalCalculator_CS.exe
BuildOutput\Release\x64\DecimalCalculator_CS\DecimalCalculator_CS.pdb
BuildOutput\Release\x64\DecimalCalculator_CS\Microsoft.Windows.Foundation.Projection.dll
BuildOutput\Release\x64\DecimalCalculator_CS\Microsoft.Windows.Foundation.Projection.p …
```
> Exclude DecimalCalculator from APIScan to avoid Timeout in Build Pipeline

- .config/tsaoptions.json
The old area path is no longer valid, replacing it with valid new area path.
////////////
WARNING:
> [1.7][Build] Updated area path for filing TSA bugs on Agg repo, per recent re-org

- .config/tsaoptions.json
The old area path is no longer valid, replacing it with valid new area path.
//////////////////////
WARNING:
> [Build] Updated area path for filing TSA bugs on Agg repo, per recent re-org

- dev/Interop/StoragePickers/FolderPicker.cpp
When users attempt to select "This PC" or other special paths in the FolderPicker, the dialog closes unexpectedly and crashes instead of providing guidance.
**gif for the behavior before fix**
After end user have selected "This PC" in the folder picker dialog, the dialog shows a message to inform user this is not valid, instead of crashing
* [`dev/Interop/StoragePickers/FolderPicker.cpp`](diffhunk://#diff-fafd9b82668f2ebe3d318ec048dab1bf54074c05dd6f56dc392b0d3e5c0294c1L91-R91): Updated the `SetOptions` method to include the `FOS_FORCEFILESYSTEM` flag in addition to `FOS_PICKFOLDERS`, ensuring that the folder picker dialog enforces the selection of filesystem objects.
**gif for the behavior after fix**
> Fix FolderPicker crash when selecting "This PC" or special paths

- dev/MRTCore/mrt/Core/src/MRM.cpp
> search vars should persist, not be loop local

- build/ProjectReunion-BuildFoundation.yml
- build/ProjectReunion-CI.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
Current settings do not actually point our pipelines to the correct branch of WindowsAppSDKConfig. mySourceBranch variable does not resolve correctly in the Pipeline Resources field.
WARNING:
> Hardcode release/1.8-stable Branch Value into WindowsAppSDKConfig reference

- BuildAll.ps1
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
- build/CopyFilesToStagingDir.ps1
- build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
- build/NuSpecs/WindowsAppSDK-Nuget-Native.props
- dev/MRTCore/packaging/native/MrtCore.C.props
Restructuring the foundation libs to be under lib\native\<arch> rather than lib\<arch>.  And add back MrtCore.props as it is still needed and fix package name for Runtimes.
WARNING:
> Fix Foundation component package libs to be under native folder

- dev/Deployment/DeploymentTraceLogging.h
- dev/Deployment/DeploymentTracelogging.cpp
- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
- dev/PackageManager/API/PackageDeploymentResolver.cpp
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrap.cpp
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapTracelogging.h
Improve TraceLogging
* Always include _GENERIC_PARTB_FIELDS_ENABLED in TraceLoggingWrite calls for rich log information
* Always specify PDT Keyword per PII practices. Usually TraceLoggingKeyword(PDT_ProductAndServicePerformance) (was in these cases but any future devs reading this should consult with your privacy representative)
https://task.ms/56757819
> Improve TraceLogging

- BuildAll.ps1
- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Per-Platform-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
- build/ProjectReunion-BuildFoundation.yml
- build/ProjectReunion-CI.yml
- build/WindowsAppSDK-BuildDevCheck.yml
- build/WindowsAppSDK-CommonVariables.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
- build/WindowsAppSDK-Versions.yml
- eng/Version.Details.xml
> Use WindowsAppSDK-Versions.yml from WindowsAppSDKConfig

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildFoundation-AnyCPU-Steps.yml
> fix: Add temporary workaround for component governance blocking pipeline due to low .NET version

- build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
- build/ProjectReunion-CI.yml
> Fix bug caused by PublishPipelineArtifact

- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Per-Platform-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-Test-Stage.yml
- build/ProjectReunion-BuildFoundation.yml
> Move matrix extraction to Build stage

- build/NuSpecs/WindowsAppSDK-Nuget-Native.AutoInitializer.targets
- build/NuSpecs/WindowsAppSDK-Nuget-Native.Bootstrap.targets
**Fix MSB4120 and MSB8027 warnings in MSBuild targets files
Problem:
MSBuild was generating multiple warnings when building the project:
1. MSB4120: "Item 'ClCompile' definition within target references itself via (qualified or unqualified) metadatum 'PreprocessorDefinitions'. This can lead to unintended expansion and cross-applying of pre-existing items."
2. MSB8027: Multiple targets were being executed repeatedly due to cross-target interference caused by the self-referencing item definitions.
Root Cause:
The issue occurred because multiple PreprocessorDefinitions were being set conditionally within ClCompile items inside targets, each referencing %(PreprocessorDefinitions) to append to existing definitions. This created several problems:
1. **Self-reference pattern**: MSBuild flags …
> fix: MSB8027, two or more files with the same name

- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Per-Platform-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
> Avoid non-fatal BinSkim errors in Post* job inject by OneBranch

- dev/Interop/StoragePickers/Strings/StoragePickers.resw
Updating storage pickers resources
The existing resources failed to generate localized messages for `IDS_APIERROR_INVALIDVIEWMODEVALUE` and `IDS_APIERROR_INVALIDSUGGESTEDSTARTLOCATIONVALUE` in the touch down pipeline.
> Updating storage pickers resources

- dev/Interop/StoragePickers/PickerCommon.cpp
- test/StoragePickersTests/PickerCommonTests.cpp
In #5547 we removed the FileTypeFilter attribute of FolderPicker. While in `PickerParameters::ConfigureDialog`, it was assumed there's always the file type filter initialized, which is a wrong and will cause `null reference` error when configuring dialog for FolderPicker, who doesn't have the FileTypeFilter attribute any more.
This PR fixes above issue, and adds a unit test to ensure the no values passed by PickerParameters are required to configure dialog.
> BugFix: fix the null reference error of FolderPicker

- dev/Deployment/DeploymentManager.cpp
This pull request resolves an application crash/fail fast occurring during the call to `DeploymentManager.Initialize()`, as reported in issue #5605. The DeploymentManager initialize is expected to only be called once, but in the case of the issue repro, it is getting called twice. This is because of the explicit call to initialize in the constructor and the default property value for WindowsAppSdkDeploymentManagerInitialize being set to true.
The change corrects error handling in `DeploymentManager.Initialize()` to prevent crash scenarios/fail fast. Instead an exception is thrown that is explanatory on the issue and can be handled by the application. 
- The change was tested manually in the repro scenario to observe the new exception being thrown
- Pipeline Runs …
> Bug Fix #5605 - 1.8 exp4: App crashes at DeploymentManager.Initialize();

- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WapProjTemplate.wapproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WapProjTemplate.wapproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/ProjectTemplate.vcxproj
* The `WinUISDKReferences` property was added to allow developers with pre-existing projects to opt-in to Hybrid CRT. New projects can use Hybrid CRT (`WinUISDKReferences=false`) by default.
Sets `WinUISDKReferences` to `false` in the template files. See diff for more details.
Manually verified by:
* Building the VsixExtension solution
* Removing the component template vsixes from the Visual Studio Installer
* Double clicking the Standalone vsix file for each project (which installs them on Visual Studio)
* Built a sample project with each template
* Verified that the C# project `AppxManifest.xml` does not have a reference to `Microsoft.VCLibs.140.00.Debug.UWPDesktop`, while the C++ project does
WARNING:
Please see pipeline link to …
> Set WinUISDKReferences=false in Templates

- dev/Interop/StoragePickers/Microsoft.Windows.Storage.Pickers.idl
- test/StoragePickersTests/PickerCommonTests.cpp
- test/StoragePickersTests/StoragePickersTests.cpp
There's an open question regarding the design of SuggestedSaveFilePath during the official API review #5634
Hence hiding this property from preview release.
Related PR on preview-1: #5664
> Hide FileSavePicker.SuggestedSaveFilePath

- dev/VSIX/Directory.Build.props
- dev/WindowsAppRuntime_DLL/packages.config
- dev/WindowsAppRuntime_UniversalBGTaskDLL/WindowsAppRuntime_UniversalBGTaskDLL.vcxproj
- dev/WindowsAppRuntime_UniversalBGTaskDLL/packages.config
- eng/Version.Dependencies.xml
> Update BuildTools* dependencies for new Base package

- build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
- build/ProjectReunion-CI.yml
In https://github.com/microsoft/WindowsAppSDK/pull/5498, the `checkout` task is added to `WindowsAppSDK-RunTests-Steps.yml`. This PR moves the `checkout` task to the beginning of the job
WARNING:
> Modify checkout task to job level

- dev/WindowsAppRuntime_DLL/packages.config
- eng/Version.Dependencies.xml
> Update BuildTool.MSIX reference to pick up missing task build error

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-StaticValidationTest-Stage.yml
- build/scripts/windows-sdk.ps1
Updating 1.7-stable's BuildInstaller and StaticValidationTest stages to explicitly install Windows SDK 22000 in a pipeline run, because this version is no longer included in VS 2022.
The script windows-sdk.ps1, which already installs another version of the Windows SDK, is now upgraded to support installing 2 different version of the Windows SDK.
////////
WARNING:
and run the build against your PR branch with the default …
> [FixBuildBreak][1.7] Adding explicit install of Windows SDK 22000 to the BuildInstaller and StaticValidationTest stages

- dev/AppLifecycle/Association.cpp
> Using lowercase seed so hash gets case insensitive on AppLificycle Association class

- test/BypassTests.json
Testing on Win10_Ent_LTSC_2021 v85.0.0 revealed that we need to add 1 more DynDep test to BypassTests.json for Win10_Ent_LTSC_2021.
////
WARNING:
> Bug 58790285: [WinAppSDK] Adding 1 more DynDep test to BypassTests.json for Win10_Ent_LTSC_2021

- test/BypassTests.json
Testing on Win10_Ent_LTSC_2021 v85.0.0 revealed that we need to add 1 more DynDep test to BypassTests.json for Win10_Ent_LTSC_2021.
////
WARNING:
> [CP to 1.8] Bug 58790285: [WinAppSDK] Adding 1 more DynDep test to BypassTests.json for Win10_Ent_LTSC_2021

- dev/MRTCore/build/DownloadDotNetCoreSdk.ps1
Fixed a psscriptanalyzer: MissingStatementBlock issue.
How verified:
- A private pipeline run confirmed that the issue is fixed with the changes in this PR
////
WARNING:
> Task 47803694: Fix psscriptanalyzer: MissingStatementBlock warning in Foundation pipeline

- test/AppNotificationBuilderTests/APITests.cpp
- test/AppNotificationBuilderTests/AppNotificationBuilderTests.testdef
- test/AppNotificationBuilderTests/AppNotificationBuilderTests.vcxproj
This PR enables the App Notification Builder tests, with a small fix for adapting to the Win11 TestInitialize requirements.
WARNING:
> Enabling AppNotification builder tests

- build/NuSpecs/WindowsAppSDK-Nuget-Native.AutoInitializer.targets
- build/NuSpecs/WindowsAppSDK-Nuget-Native.UndockedRegFreeWinRT.targets
Reverts microsoft/WindowsAppSDK#5685
Because this pr caused winUI build error.
> Revert "[Issue 5395] Fix msbuild warnings"

- dev/WindowsAppRuntime_DLL/packages.config
- eng/Version.Dependencies.xml
> Update MSIX build tools version to 1.7.20250829.1

- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
Use ComponentType as a suffix for dev pipeline, to make sure the component package version won't conflict with nightly build.
And with the config in -dev pipeline, we could get 2 packages like this
WARNING:
> change dev package suffix

- inc/README.md
- inc/abi/runtime/WindowsAppSDK-VersionInfo.h
- inc/abi/winml/Microsoft.Windows.AI.MachineLearning.h
- inc/abi/winml/WindowsMLAutoInitializer.cpp
- inc/abi/winml/onnxruntime/cpu_provider_factory.h
- inc/abi/winml/onnxruntime/provider_options.h
- inc/abi/winml/onnxruntime/win_onnxruntime_c_api.h
- inc/abi/winml/onnxruntime/win_onnxruntime_cxx_api.h
- inc/abi/winml/onnxruntime/win_onnxruntime_cxx_inline.h
- inc/abi/winml/onnxruntime/win_onnxruntime_float16.h
- inc/abi/winml/onnxruntime/win_onnxruntime_lite_custom_op.h
- inc/abi/winml/onnxruntime/win_onnxruntime_run_options_config_keys.h
- inc/abi/winml/onnxruntime/win_onnxruntime_session_options_config_keys.h
This adds the remainder of the ORT headers from the WinML package the initial commit missed. It also adds the WASDK version information for the runtime.
> Add the matching ORT headers and version header

- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
According to Bug 59105489, Pack stage should not run if the build stage has failed
WARNING:
> Update Pack stage's condition

- build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
- docs/Coding-Guidelines/GettingStarted.md
- tools/DevCheck/DevCheck-Settings.ps1
- tools/DevCheck/DevCheck.ps1
* New options:
* -CheckNugetExe - Verify nuget.exe is present
* -FixAll - Enable all -Fix* options plus -NugetRestore
* -FixLongPath - Enable LongPath support if necessary
* -InstallWindowsSDK - Download and install Windows Platform SDKs (if necessary)
* -NugetExe <path> - Location of nuget.exe (default=".user\nuget.exe")
* -NugetMinVersion <version> - Minimum required version of nuget.exe (default="6.14.0.116")
* -NugetExeUpdate - Download nuget.exe to the -NugetExe path
* -NugetRestore - Restore nuget packages
* Fixed error reporting. ExitCode=0 if successful, ExitCode=1 if 1+ issue(s) occurred
* Added LongPath detection/enablement
* Enhanced -CheckVisualStudio to detect `vswhere.exe` in PATH if not found at default install location
* Fixed Install-WindowsSDK to respect -Offline
* …
> DevCheck: LongPath support, verify nuget.exe, fix ExitCode, fix InstallWindowsSDK, add/fix SettingsFile, update Getting Started docs

- build/AzurePipelinesTemplates/WindowsAppSDK-StaticValidationTest-Stage.yml
> change staticValidationTest windowsSdk version

- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
- test/PackageManager/API/PackageDeploymentManagerTests.h
Set the ProgressStatus to InProgress once we have started making progress, and make sure that the Test validates this for all things that use the Async code in the future.
fixes #5532
> PackageDeployment API Progress status bug #5532

- dev/DynamicDependency/Powershell/Add-PackageDependency.ps1
- dev/DynamicDependency/Powershell/Get-PackageDependency.ps1
- dev/DynamicDependency/Powershell/Get-PackageDependencyProcesses.ps1
- dev/DynamicDependency/Powershell/MsixDynamicDependency.psm1
`Get-PackageDependency.ps1` dumps information about dynamic dependencies. For example
```
pwsh -c .\Get-PackageDependency.ps1 -PackageDependencyId T:1BB73916-AB6B-4281-A97B-0672ED4497CF
pwsh -c .\Get-PackageDependency.ps1 -PackageFamilyName Microsoft.WindowsAppRuntime.1.8_8wekyb3d8bbwe
pwsh -c .\Get-PackageDependency.ps1 -All
```
`pwsh -c .\Get-PackageDependency.ps1 -?` for more details.
NOTE: This only works for OS Dynamic Dependencies (like everything else in `dev\dynamicdependency\powershell`)
P.S. I'd like to add support to make the `-PackageDependencyId/-PackageFamilyName/-All` optional and (pardon the pun) dynamically figure it out given the input string but so far all attempts don't work, break explicit scenarios or introduced undesired side effects. This is deferred to a future …
> DynamicDependency: Expanded powershell cmdlets

- dev/Deployment/DeploymentActivityContext.cpp
- dev/Deployment/DeploymentManager.cpp
On the method `Initialize` from the deployment manager, the two inside methods `InstallLicences` and `DeployPackages` were resetting the activity data without setting it back, causing loss of data on our telemetry measurements.
Removed the `Reset()` call for every license file found, changing it to a single reset in the beginning of the method. This way, it keeps the information of the install stage but still clearing possible remaining data (like resource id).
Added a `Reset()` call in the beginning of the method so it clears previous data (for example, the resource ids that were set from install packages). This is important because if a error happens here, the telemetry data would be confusing as it would still showing a license file.
Set back the install stage after the reset for each …
> Fixing reset activity data on deployment initialization

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildSamplesCompat-Job.yml
- test/ModifySampleAppsReferences.ps1
> Fix the Sample Tests failure caused by ModifySampleAppsReferences.ps1

- test/AppNotificationTests/AppNotificationTests.testdef
Some packaged app notification tests are also flake. Disabling them for now.
WARNING:
> Disabling packaged app notification tests

- specs/Storage.Pickers/FileOpenPicker.md
- specs/Storage.Pickers/FileSavePicker.md
- specs/Storage.Pickers/FolderPicker.md
- specs/Storage.Pickers/Microsoft.Windows.Storage.Pickers.md
This is a design spec for adding new functionality to the `Microsoft.Windows.Storage.Pickers` APIs, including 2 main changes:
1. the `SuggestedFolder` and `SuggestedStartFolder` properties for all three picker types, 
2. the new `FileTypeChoices` property for `FileOpenPicker`. The documentation and code samples are updated to reflect these changes, with detailed explanations of how each property affects picker behavior.
**New and enhanced picker properties:**
* Added `SuggestedFolder` and `SuggestedStartFolder` properties to `FileOpenPicker`, `FileSavePicker`, and `FolderPicker`, allowing developers to control both the persistent and initial folder shown when the picker dialog opens. [[1]](diffhunk://#diff-5cfa035ddfdddfd5f0ea035dc2e78ac86e1b55c323ed0dd06dc9c8bcbf3b5869R22-R29) …
> API review for new properties in Storage.Pickers - SuggestedDefaultFolder, FileTypeChoices
