microsoft/WindowsAppSDK

- docs/faq.md
There's a bunch of issues and comments that should turn into FAQ content instead.
Related issues are #42, #40, #33, #24, and #18 .
> FAQ update from issues

- docs/faq.md
- docs/roadmap.md
* Changed ```priviledge``` to ```privilege``` (spelling error)
* Changed ```WinUi``` to ```WinUI``` (capitalization error)
> Some fixes

- docs/README.md
- specs/README.md
- specs/spec_template.md
We're drafting off the WinUI API review process, so I've cloned [their template](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/master/spec_template.md) and process.
> Add API spec template and handling instructions

- .github/workflows/build.yml
Fixes #117 by excluding some paths
> Exclude specs and docs for builds

- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
> set TargetPlatformMinVersion to 10.0.17134.0

- build/ProjectReunion-release.yml
Sign the Microsoft.ProjectReunion.dll in the release pipeline
> Sign the Microsoft.ProjectReunion.dll in the release pipeline

- build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
- build/NuSpecs/ProjectReunion-Nuget-Native.targets
This file seems to be giving me issues in the sample app soI am removing the reference to it, so it is not pulled in.
> Remove common targets file

- build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
Make the default version 0.1.0in the build scripts
> Fix version to 0.1.0

- ProjectReunion.sln
- build/AzurePipelinesTemplates/ProjectReunion-BuildProject-Steps.yml
- dev/AppLifecycle/AppLifecycle.cpp
- test/AppLifecycle/AppLifecycle.vcxitems
- test/AppLifecycle/AppLifecycle.vcxitems.filters
- test/AppLifecycle/FunctionalTests.cpp
- test/CppTest/CppTest.vcxproj
- test/CppTest/Cpptest.vcxproj.filters
Start Running Passing Win32 AppLifeCycle Tests in Foundation Pipeline
> Start Running Passing Win32 AppLifeCycle Tests in Foundation Pipeline

- build/Helix/NuGet.config
- build/Helix/PrepareHelixPayload.ps1
- build/Helix/packages.config
- dev/MRTCore/mrt/mrm/UnitTests/BaseUnitTests.vcxproj
- dev/MRTCore/mrt/mrm/UnitTests/packages.config
- nuget.config
- test/CppTest/CppTest.vcxproj
- test/CppTest/packages.config
> Fix nuget config

- docs/roadmap.md
had a chat with AndrewC - feedback from that incorporated in PR
> Updates requested by Andrew Clinick

- ProjectReunion.sln
- dev/PushNotifications/PushNotifications.vcxitems
Description: Creating a PushNotifications Project for handling push notifications.
> Add PushNotifications folder to the project

- dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.props
we need to find a better way to handle this. But i just update the version for now.
> Update FWP version registration

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.References.targets
- dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.WinRt.props
- dev/MRTCore/packaging/native/Microsoft.ApplicationModel.Resources.props
I will stamp ProjectReunionFrameworkPackage in aggregation pipeline.
> Make MRTCore work in framework package

- dev/VSIX/Directory.Build.props
- dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/WinUI.UWP.Cs.BlankApp.vstemplate
* candidate versions of 0.5 preview nupkgs
* update to latest nupkgs
* another update and template fix
> Cherry Pick: Tweaks for Reunion 0.5 Preview release (#524)

- dev/MRTCore/mrt/Core/src/MRM.cpp
https://github.com/microsoft/ProjectReunion/pull/554
> Cherry pick: MRTCore will also lookup parent folder

- build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
> Bump transport package version to 0.5 (#576)

- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/packages.config
Version Alightment/Contains fixes
> Update Framework UDK

- dev/VSIX/Extension/source.extension.vsixmanifest
Removing preview tag from VSIX in release branch
> Removing preview tag from VSIX in release branch

- specs/AppLifecycle/Activation/AppLifecycle Activation.md
ActivationArguments --> AppActivationArguments
> Update AppLifecycle Activation.md

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
cherry pick https://github.com/microsoft/ProjectReunion/pull/674.
> Set SDKVersion (#674)

- dev/MRTCore/build-mrt.yml
- dev/MRTCore/build/DownloadDotNetRuntimeInstaller.ps1
- dev/MRTCore/build/versions.props
- dev/MRTCore/global.json
This is required for using CSWinRT 1.2
> Update MRTCore to .net 5.0.3

- build/AzurePipelinesTemplates/ProjectReunion-ProcessTestResults-Job.yml
- build/AzurePipelinesTemplates/ProjectReunion-RunHelixTests-Job.yml
- build/Helix/RunTestsInHelix.proj
cherry-pick https://github.com/microsoft/ProjectReunion/pull/665
> Switch to Open Helix Queues (#665)

- dev/MRTCore/build-mrt.yml
- dev/MRTCore/build/DownloadDotNetRuntimeInstaller.ps1
- dev/MRTCore/build/versions.props
- dev/MRTCore/global.json
Cherry pick https://github.com/microsoft/ProjectReunion/pull/703
> Update MRTCore to .net 5.0.3 (#703)

- dev/VSIX/Directory.Build.props
- dev/VSIX/Directory.Build.targets
Remove other version references in props and targets
Continuation of work from
https://github.com/microsoft/ProjectReunion/pull/702
> Remove other version references in props and targets

- dev/VSIX/Directory.Build.props
- dev/VSIX/Extension/ProjectReunion.Extension.csproj
Bring in VSIX Updates from release
Takes changes from these PR
https://github.com/microsoft/ProjectReunion/pull/631
https://github.com/microsoft/ProjectReunion/pull/640
> Bring in VSIX Updates from release

- ProjectReunion.props
- build/AzurePipelinesTemplates/ProjectReunion-BuildProject-Steps.yml
- build/CopyFilesToStagingDir.ps1
- tools/GenerateDynamicDependencyOverrides.ps1
Move DynamicDependencies overrides to BuildOutput\override
> Move DynamicDependencies overrides to BuildOutput\override

- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/Microsoft.ApplicationModel.Resources.vcxproj
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/src/packages.config
> Update frameworkUDK version

- build/AzurePipelinesTemplates/ProjectReunion-PublishProjectOutput-Steps.yml
- build/CopyFilesToStagingDir.ps1
- build/NuSpecs/AppxManifest.xml
Updated the appxmanifest.xml snippet fed to the build pipeline to include in the final PRfwk's appxmanifest.xml
> Update appxmanifest.xml inproc servers snippet

- dev/DynamicDependency/PackageDependency.cpp
- tools/DevCheck.ps1
(cherry-pick from main to preview/0.8-preview2)
* Fixed cert enumeration (incorrect probing caused failures)
* Fixed incorrect PCWSTR[] access
> DynamicDependencies: fix PCWSTR[] access (#872)

- dev/PowerNotifications/PowerNotifications.cpp
- dev/PowerNotifications/PowerNotifications.h
- dev/PowerNotifications/PowerNotifications.idl
- test/PowerNotificationsTests/PowerTests.cpp
> Adding Suspend/Resume notification code()

- README.md
We're closing the survey, need to remove it
> Remove survey

- build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
- eng/common/Maestro-PublishBuildToMaestro.yml
- eng/common/MaestroHelpers.ps1
This is a manual step now but in the future it should be automatic.
Improvements/bug fixes for eng/common folder
- Maestro update wasn't working for AzureDevOps repositories, it works now
- Only trigger subscriptions whose source repository is the same as ours
> Update eng/common folder

- build/ProjectReunion-BuildFoundation.yml
Enable publishToMaestro when build is scheduled
> Enable publishToMaestro when build is scheduled

- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/ProjectTemplate.vcxproj
- dev/VSIX/ProjectTemplates/UWP/CSharp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/UWP/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/UWP/CSharp/RuntimeComponent/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/UWP/CppWinRT/BlankApp/ProjectTemplate.vcxproj
cherry pick https://github.com/microsoft/ProjectReunion/pull/897.
> Add UseWinUI property (#897)

- dev/MRTCore/packaging/Microsoft.ApplicationModel.Resources.PriGen.targets
This is a regression due to https://github.com/microsoft/ProjectReunion/pull/696.
> Fix copy xbf file

- eng/common/Maestro-PublishBuildToMaestro.yml
Only trigger subscription if updateFrequency is everyBuild
This is usually updated automatically but Maestro does not ever update to this repo.
> Only trigger subscription if updateFrequency is everyBuild

- tools/GenerateDynamicDependencyOverrides.ps1
Removed trailing comma in json element in GenerateDynamicDepenedencyOverrides.ps1
> Fixed DynamicDependency-Override.json error

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/UnpackagedTests.csproj
this is a regression from https://github.com/microsoft/WindowsAppSDK/pull/938.
> fix path for unpackagedtests

- build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
- build/ProjectReunion-BuildFoundation.yml
Revert the rename for the connection string. This would fall under azure dev ops category which is out of scope.
> Revert the rename for the connection string

- build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
> Revert feed name

- build/NuSpecs/WindowsAppSDK-Nuget-Native.props
> ProjectReunion -> WindowsAppSDK rename patch

- build/WindowsAppSDK-Versions.yml
Update version for experimental
> Update version for experimental

- build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
- build/CopyFilesToStagingDir.ps1
- build/NuSpecs/Intellisense/Microsoft.Windows.System.Power.xml
- build/NuSpecs/WindowsAppSDK-Nuget-Native.WinRt.props
- build/NuSpecs/WindowsAppSDK-Nuget-Native.targets
Adding entries for the new WinMD file, Microsoft.Windows.System.Power.winmd
> Adding entries for PowerNotifications WinMD file

- dev/PowerNotifications/PowerNotifications.h
- dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
Carried over from https://github.com/microsoft/WindowsAppSDK/pull/1331 due to merge issues. Refer to the link for original comments.
> Adding Telemetry to PowerNotifications

- installer/nuget.config
Add Nuget.Config to installer directory
> Add Nuget.Config to installer directory 

- installer/nuget.config
Move Installer Nuget.Config comment down one line
> Move Installer Nuget.Config comment down one line

- dev/MRTCore/mrt/mrm/include/mrm/common/MrmTraceLogging.h
- dev/MRTCore/mrt/mrm/include/mrm/common/PlatformWin32.h
I verified that the change builds fine.
There is an issue where none of the log data (HR values, etc.) are showing up in the ETL logs... Outside of that, I confirmed the events are logged. Proceeding with check-in. Will follow up on the issue separately.
> For MRT Core, exclude file names and file paths from logging as they contain PII.

- build/AzurePipelinesTemplates/WindowsAppSDK-CallTouchDownBuild-Steps.yml
- build/WindowsAppSDK-TDBuild.yml
> Set TDBuild to commit by default and refactor parameters

- dev/AppLifecycle/AppLifecycle.idl
Remove experimental tag from AppLifecycle feature.
> Remove experimental tag from AppLifecycle feature.

- build/ProjectReunion-BuildFoundation.yml
> (CherryPick) Use public pool and PAT for publishing public symbols #1267

- dev/VSIX/Directory.Build.props
The 22000 BuildTools package contains a fix that will address this issue: https://github.com/microsoft/microsoft-ui-xaml/issues/5828. This PR is paired with PR 6532299 in the internal repo.
> Update to the 22000 Microsoft.Windows.SDK.BuildTools nuget package

- dev/AppLifecycle/AppLifecycle.idl
> Remove experimental tag from AppLifecycle feature. (#1517)

- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win10-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win10-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win10-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win10-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win10-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win10-x86.pubxml
> fix Hot Reload regression, incompatible with PublishReadyToRun (#1739)

- build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
- build/ProjectReunion-BuildFoundation.yml
- eng/common/AzurePipelinesTemplates/Maestro-PublishBuildToMaestro-Steps.yml
- eng/common/AzurePipelinesTemplates/WinAppSDK-Build-Steps.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-Build-Steps.yml
- eng/common/Scripts/UpdateVersionDetailsConfig.ps1
Build the WindowsAppSDK NugetPackage in the Internal Foundation Build pipeline with Foundation transport package that was built
Includes updates to Eng/Common
> Build the WindowsAppSDK NugetPackage in the Internal transport package pipeline

- dev/MRTCore/build/versions.props
- dev/MRTCore/global.json
- dev/MRTCore/mrt/Microsoft.ApplicationModel.Resources/projection/Microsoft.ApplicationModel.Resources.Projection.csproj
> Update CSWinRT to 1.4.1

- build/ProjectReunion-BuildFoundation.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-Build-Steps.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
Build WinAppSDK template refactors
> Refactor setup steps into WindowsAppSDK-Build-Setup-Steps.yml

- docs/EngineeringSystem/ReunionMaestro.md
- docs/EngineeringSystem/WinAppSDK-Maestro.md
Documentation for Maestro in WindowsAppSDK
> Documentation for Maestro in WindowsAppSDK

- docs/EngineeringSystem/WinAppSDK-Maestro.md
Onboarding instructions for each type of repository
> Onboarding instructions for each type of repository

- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cpp
Added header so MddBootstrapAutoInitializer.cpp compiles regardless of precompiled headers
> Added header to MddBootstrapAutoInitializer.cpp

- build/ProjectReunion-BuildFoundation.yml
FI main into feature branch - no conflicts
> Forward integrate main into feature branch WNP_ToastNotifications

- build/ProjectReunion-BuildFoundation.yml
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cpp
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-Build-Steps.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildAndIntegrationTest-Steps.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
- global.json
FI main into pseudo feature branch - no conflicts
> Forward integrate main into WNP_ToastNotifications

- build/AzurePipelinesTemplates/WindowsAppSDK-PublishProjectOutput-Steps.yml
- build/ProjectReunion-BuildFoundation.yml
- build/build-mrt.yml
- dev/VSIX/Extension/Cpp/Common/it-IT/VSPackage.it-IT.resx
- dev/VSIX/Extension/Cpp/Common/ko-KR/VSPackage.ko-KR.resx
- dev/VSIX/Extension/Cpp/Common/pt-BR/VSPackage.pt-BR.resx
- dev/VSIX/Extension/Cs/Common/it-IT/VSPackage.it-IT.resx
- dev/VSIX/Extension/Cs/Common/ko-KR/VSPackage.ko-KR.resx
- dev/VSIX/Extension/Cs/Common/pt-BR/VSPackage.pt-BR.resx
- eng/Version.Details.xml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
- global.json
Forward Integration from main to WNP_ToastNotifications_L1; no conflicts
> FI main into WNP_ToastNotifications_L1

- dev/ToastNotifications/NotificationProperties.cpp
- dev/ToastNotifications/ToastNotificationManager.cpp
- dev/ToastNotifications/ToastNotificationManager.h
- dev/ToastNotifications/ToastNotifications.vcxitems
- dev/ToastNotifications/ToastProgressData.cpp
- dev/ToastNotifications/ToastProgressData.h
- dev/ToastNotifications/ToastProgressDataABI.cpp
- dev/ToastNotifications/ToastProgressDataABI.h
- test/Deployment/data/WindowsAppRuntime.Test.Framework/appxmanifest.xml
- test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
- test/TestApps/ToastNotificationsTestApp/main.cpp
- test/ToastNotificationTests/APITests.cpp
Description: Support Toast Progress Updates for a given tag and group
Validation: Implemented Unittests as part of the ToastNotificationTests
> Enable ToastProgressData Updates

- specs/AppLifecycle/StateNotifications/AppLifecycle StateNotifications.md
> Update AppLifecycle StateNotifications.md

- build/build-mrt.yml
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/MrtCoreUnpackagedTests.csproj
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/UnpackagedTests/TestClass.cs
FI main into RI_WNP_ToastNotifications_L1. 
It has a fix for the build pipelines, see: https://github.com/microsoft/WindowsAppSDK/pull/2193
clean merge, no conflicts.
> FI main into RI_WNP_ToastNotifications_L1

- specs/PushNotifications/ToastNotifications-spec.md
This is the Public API spec for Toast Notifications which needs to be vetted and reviewed. Please provide feedback.
> Add Public API spec for Toast Notifications

- test/PushNotificationTests/LRPTests.cpp
Fix CoCreateInstance test for Long Running Process.
> Fix LaunchLRP_FromCoCreateInstance test

- installer/dev/WindowsAppRuntimeInstall.vcxproj
Remove an erroneous dangling Condition check from vcproj file
> Remove an erroneous dangling Condition check from vcproj file

- installer/dev/WindowsAppRuntimeInstall.vcxproj
- installer/dev/pch.h
Define RootRepo for the Installer Solution
> Define RootRepo for the Installer Solution

- dev/AppLifecycle/AppInstance.cpp
Cherry pick from main to 1.1-preview1 branch
> [1.1-preview1] Revert try_create use as it breaks single instancing. (#2245)

- dev/AppLifecycle/AppLifecycle.idl
(cherry picked from commit fd31541e58441c2db3567daf5a2abeb594c36996)
> Add AppLifecycle contract (#2292)

- dev/AppNotifications/AppNotification.cpp
- dev/AppNotifications/AppNotificationManager.cpp
- dev/AppNotifications/AppNotificationProgressData.cpp
- dev/AppNotifications/AppNotifications.idl
- dev/PushNotifications/PushNotificationChannel.cpp
- dev/PushNotifications/PushNotificationChannel.h
- dev/PushNotifications/PushNotificationCreateChannelResult.cpp
- dev/PushNotifications/PushNotificationManager.cpp
- dev/PushNotifications/PushNotificationReceivedEventArgs.cpp
- dev/PushNotifications/PushNotifications.idl
* removing experimental requires removing everything
* Code cleanup
Co-authored-by: Eric Langlois <erlangl@microsoft.com>
> Remove [experimental] tags take 2 (#2306)

- dev/AppNotifications/AppNotifications.idl
- dev/PushNotifications/PushNotifications.idl
Using contract name as defined in: https://github.com/microsoft/WindowsAppSDK/pull/2293
> Add contracts for PushNotifications

- dev/AppNotifications/AppNotificationManager.cpp
- dev/PushNotifications/PushNotificationManager.cpp
Fixed issue with activation on STA thread by adding REGCLS_AGILE.
> Add Agile flag

- specs/Deployment/DeploymentAPI.md
Added API contract version to Deployment interface
> Add API contract version to Deployment interface

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.vcxproj
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/packages.config
- dev/PushNotifications/PushNotificationsLongRunningTask/PushNotificationsLongRunningTask.vcxproj
- dev/PushNotifications/PushNotificationsLongRunningTask/packages.config
- dev/WindowsAppRuntime_DLL/WindowsAppRuntime_DLL.vcxproj
- dev/WindowsAppRuntime_DLL/packages.config
Update FrameworkUDK To 1.1.2-CI-25087.1000.220401-1608.1
> Update FrameworkUDK To 1.1.2-CI-25087.1000.220401-1608.1

- dev/AccessControl/AccessControl.idl
- dev/AppNotifications/AppNotifications.idl
- dev/DynamicDependency/API/M.AM.DynamicDependency.idl
- dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.idl
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/src/Microsoft.Windows.ApplicationModel.Resources.idl
- dev/PowerNotifications/PowerNotifications.idl
- specs/WinRT/WinRTAPIContracts.md
Update WinRT contracts per specs\WinRT\WinRTAPIContracts.md (some contract names didn't match or were absent)
> Update WinRT contracts per specs\WinRT\WinRTAPIContracts.md

- dev/Deployment/PackageDefinitions.h
- specs/Deployment/MSIXPackageVersioning.md
- specs/Deployment/MSIXPackages.md
- test/DynamicDependency/Test_BootstrapAutoInitialize/CPP/WindowsAppSDK-VersionInfo.h
- test/DynamicDependency/Test_BootstrapAutoInitialize/CS/WindowsAppSDK-VersionInfo.cs
Store package Name required for Store package signing
Also, add missing DDLM constants
https://task.ms/39401667
> Change Singleton package Name to Microsoft.WinAppRuntime.Singleton[-shorttag]

- WindowsAppRuntime.sln
- build/CopyFilesToStagingDir.ps1
- test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/Microsoft.WindowsAppRuntime.Framework.vcxproj
This fix is required for DeploymentAgent.exe to be part of Framework package.
> Copy DeploymentAgent executable to TestFwkPkg

- build/NuSpecs/AppxManifest.xml
- test/Deployment/data/WindowsAppRuntime.Test.Framework/appxmanifest.xml
- test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
Update Deployment ACIDs in Framework package manifest
Co-authored-by: Santosh Chintalapati <sachinta@ntdev.microsoft.com>
> Update Deployment ACIDs in Framework package manifest (#2472)

- dev/AppNotifications/AppNotificationManager.cpp
- dev/AppNotifications/AppNotificationManager.h
- dev/AppNotifications/AppNotificationUtility.cpp
- dev/AppNotifications/AppNotificationUtility.h
Description: Refactoring the existing implementation to be able to do specialized operation depending on the Application type. This makes it easy to even introduce overloaded Register API that takes in assets to directly call into appropriate helpers to assist in registration process.
Validation: Run TAEF tests
> Refactor register API

- docs/EngineeringSystem/WinAppSDK-Maestro.md
Update maestro docs. Added a note about dotnet default values.
This is to prevent confusion.
> Update maestro docs. Added a note about dotnet default values.

- WindowsAppRuntime.sln
- dev/UndockedRegFreeWinRT/typeresolution.cpp
cherry-pick 2c23172
PR #1649 for 1.1-servicing
> UndockedRegFreeWinRT: RoGetMetaDataFile() fix for 1.1-servicing

- build/AzurePipelinesTemplates/WindowsAppSDK-CreateNugetPackage-Job.yml
- build/ProjectReunion-BuildFoundation.yml
- build/WindowsAppSDK-CommonVariables.yml
- build/WindowsAppSDK-Versions.yml
Overhaul NuGet versions to include "main" or "develop"
> Overhaul NuGet versions to include "main" or "develop"

- test/TestApps/AccessControlTestAppPackage/AccessControlTestAppPackage.wapproj
- test/TestApps/ToastNotificationsDemoPackage/ToastNotificationsDemoPackage.wapproj
Update these MSTest.pfx remnants to current practice
> Some old MSTest.pfx references were lingering (and now breaking things)

- .github/ISSUE_TEMPLATE/bug-report.yaml
WinAppSDK version of: https://github.com/microsoft/microsoft-ui-xaml/pull/7238
> Add 1.1.1 & 1.0.4 to bug template and remove outdated versions

- dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
> Update Newtonsoft.Json explicit reference in Dev16 projects

- build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
Minor change `<Command>xcopy...` to `<Copy>...` to ensure execution (buttons up a rare problem)
> XCOPY command should be <COPY> to ensure execution

- dev/Deployment/DeploymentManager.cpp
* Search for Main instead of Fw Package
* Add Comments
Cherry-picked from #2753
Co-authored-by: Santosh Chintalapati <sachinta@ntdev.microsoft.com>
> Cherry Pick "User/sachinta/fix DeploymentManager's GetStatus (#2753)" to release/1.1-stable

- dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.cpp
- dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.h
- dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.idl
- dev/AppNotifications/AppNotificationBuilder/AppNotificationBuilder.vcxitems
- dev/AppNotifications/AppNotificationBuilder/AppNotificationProgressBar.cpp
- dev/AppNotifications/AppNotificationBuilder/AppNotificationProgressBar.h
- test/AppNotificationBuilderTests/APITests.cpp
- test/DynamicDependency/data/Microsoft.WindowsAppRuntime.Framework/appxmanifest.xml
@pmpurifoy, there's abuild break in your branch. and this PR fixes it.
It merges the feature branch and address some namespace issues in the apitests file.
You can either merge this as is into your PR, or manually re-implement the changes.
> Fix build break in user/purifoypaul/TimestampFix

- dev/Deployment/DeploymentManager.cpp
- dev/Deployment/DeploymentTraceLogging.h
* Fix DeploymentManager Initialize Activity's incorrect event name
* Fix DeploymentManager Initialize Activity lifetime
Cherry picked from #2802 
Co-authored-by: Santosh Chintalapati <sachinta@ntdev.microsoft.com>
> User/sachinta/fix deployment manager telemetry (#2802)

- specs/dynamicdependencies/DynamicDependencies.md
Update spec w/previous API Review feedback, typo corrections and apicontracts (added in WinAppSDK 1.1)
> Dynamic Depedencies spec: Update w/previous feedback, typo corrections and apicontracts

- build/ProjectReunion-BuildFoundation.yml
> Partially reenable the Integration test to only produce a WinAppSDK package

- eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
Bad merge from https://github.com/microsoft/WindowsAppSDK/pull/2939
> Checkout PRInternal Main instead of release/1.2-preview1

- dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.Insights.h
- dev/EnvironmentManager/API/Microsoft.Windows.System.EnvironmentManager.cpp
For some reason or another EM wasn't firing events.  I changed that.
I believe the reason why was because I wasn't using the correct MACROs(?).
> Making EM fire events.

- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/app.manifest
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/app.manifest
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/app.manifest
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/app.manifest
Added compatibility line in app.manifest that allows unpackaged apps to use a custom titlebar.
> Unpackaged Custom Titlebar template Fix

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildSolution-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
- build/ProjectReunion-BuildFoundation.yml
- build/build-mrt.yml
and run the build against your PR branch with the default paramters.
> Fix Nuget Authentication Issues by forcing Nuget Update

- BuildTransportPackage.ps1
BuikldTransportPackages.ps1 didn't correctly publish MRTCore files.
> Adding mrtcore publishing to BuildTransportPackage.ps1

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-InstallNuget-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-RunHelixTests-Job.yml
- build/ProjectReunion-BuildFoundation.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
This update was done in main but needs to be done in the release branches
> Authenticate NuGet Fix

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildProject-Steps.yml
- dev/VersionInfo/VersionInfo.idl
Cherry-pick #3075 
Fix merge error from #3073 
Fixes ReleaseInfo to be experimental
> [1.2-stable] Fix [experimental] should be [feature(Feature_Blah)]

- eng/Version.Details.xml
- eng/Versions.props
I messed up the Maestro PR that was bringing this in, so just manually created a new one.
> FrameworkUDK 1.2.3-CI-25233.1000.221026-1354.0

- docs/roadmap.md
Edits & refinements to WinAppSDK roadmap based on comments from @riverar, thank you!
> Roadmap edits & refinements

- eng/Version.Details.xml
Update App Licensing Package to 1.2.0-main.20221103
> Update App Licensing Package to 1.2.0-main.20221103.4

- .github/ISSUE_TEMPLATE/bug-report.yaml
> add 22H2 to bug template

- .config/tsaoptions.json
- build/AzurePipelinesTemplates/WindowsAppSDK-BinaryAnalysis-steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-SourceAnalysis-job.yml
Updating TSA config and enabling auto TSA bug filing, to meet Executive Order requirement.
--
> Enable auto TSA bug filing

- .config/tsaoptions.json
> Updated areaPath and codebaseName in TsaOptions.json

- .github/ISSUE_TEMPLATE/bug-report.yaml
- README.md
- Update to bug template for 1.2
- Update to 1.2 across readme
- Remove out of date ProductBoard roadmap
> 1.2 readme updates

- docs/Coding-Guidelines/WinRT-Registration.md
Fixed minor phrasing missed in previous PR 
https://github.com/microsoft/WindowsAppSDK/pull/2359
> Fixed minor phrasing missed in previous PR 2359 

- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/unittests/MrtCoreManagedTest.csproj
- dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
Update Newtonsoft.Json to 13.0.2
> Update Newtonsoft.Json to 13.0.2

- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Update VSIX projects to specify Newtonsoft.Json Version
> Update VSIX projects to specify Newtonsoft.Json Version

- eng/Version.Details.xml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-Build-Steps.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildAndIntegrationTest-Steps.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-IntegrationTest-Steps.yml
- eng/common/README.md
Related release branches PR:
https://github.com/microsoft/WindowsAppSDK/pull/3272
https://github.com/microsoft/WindowsAppSDK/pull/3273
> Rename all references of ProjectReunionInternal to WindowsAppSDK Aggregator except for service connections

- eng/Version.Details.xml
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/3280
> [Cherrypick] Rename references of ProjectReuionClosed to WindowsAppSDKClosed

- eng/Version.Details.xml
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/3280
> [Cherrypick] Rename references of ProjectReuionClosed to WindowsAppSDKClosed 

- DevCheck.ps1
- Directory.Packages.props
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/projection/Microsoft.Windows.ApplicationModel.Resources.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppLifecycle/Microsoft.Windows.AppLifecycle.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppNotifications.Builder.Projection/Microsoft.Windows.AppNotifications.Builder.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppNotifications.Projection/Microsoft.Windows.AppNotifications.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.ApplicationModel.DynamicDependency/Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.ApplicationModel.WindowsAppRuntime/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.PushNotifications.Projection/Microsoft.Windows.PushNotifications.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.Security.AccessControl.Projection/Microsoft.Windows.Security.AccessControl.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.System.Power/Microsoft.Windows.System.Power.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.System/Microsoft.Windows.System.Projection.csproj
- eng/Version.Dependencies.props
- eng/Version.Dependencies.xml
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/3304
> [CherryPick] Separate Maestro dependencies and manual dependencies into two xml files #3304

- eng/Versions.props
Add Versions.props to please Maestro
> Add Versions.props to please Maestro

- dev/VSIX/Extension/Cpp/Dev16/WindowsAppSDK.Cpp.Extension.Dev16.csproj
- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
- dev/VSIX/Extension/Cs/Dev16/WindowsAppSDK.Cs.Extension.Dev16.csproj
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
> [Cherrypick] Update Newtonsoft.Json to 13.0.2 #3229

- docs/pull_request_template.md
> Update PR Template to Address Inaccuracies. 

- DevCheck.ps1
New option: -CheckDeveloperMode verifies Developer Mode is enabled
Kudos to @pmpurifoy for the core logic
Also updated help.
> DevCheck: -CheckDeveloperMode

- DevCheck.ps1
Quick patch to unblock folks.
More dynamic update using Version.Dependencies.xml info coming in a future PR
> Patch version of TAEF referenced by DevCheck

- build/WindowsAppSDK-SyncMirroredRepository.yml
Setting up automation to sync the mirrored release/1.3-stable branch
> Automation Syncing the Mirrored release/1.3-stable Branch

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Updating bug report for WinAppSDK v1.2.4

- eng/Version.Details.xml
Update name from ProjectReunionClosed to WindowsAppSDKClosed
> Update name from ProjectReunionClosed to WindowsAppSDKClosed

- build/ProjectReunion-BuildFoundation.yml
Update ESRP Signing Task to 2: EsrpCodeSigning@2
EsrpCodeSigning@1 has stopped working
> Update ESRP Signing Task to 2: EsrpCodeSigning@2 

- build/ProjectReunion-BuildFoundation.yml
Update ESRP Signing Task to 2: EsrpCodeSigning@2
EsrpCodeSigning@1 has stopped working
> Update ESRP Signing Task to 2: EsrpCodeSigning@2

- test/AppLifecycle/AppLifecycle.testdef
- test/AppLifecycle/AppLifecycle.vcxproj
> AppLifecycle: Add tests to the pipeline test runs

- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Release.yml
Update Defaults for Nightly and Release
PublishToMaestro and Signing should be on by default
> Update Defaults for Nightly and Release

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml to 1.3.1

- build/WindowsAppSDK-SyncMirroredRepository.yml
> Update SyncMirror Pipeline to include 1.4-stable

- build/WindowsAppSDK-Foundation-Release.yml
Not all Binskim issues has been fixed yet
> Don't break on binskim 

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.4 experimental 1

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.3.2

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.4 preview 1

- eng/Version.Details.xml
> Update CsWinRT version to 2.0.3

- eng/Version.Details.xml
> [release/1.4-stable] Update to CsWinRT 2.0.3

- NuGet.config
FI from main made this change.
Need to revert.
> Develop to use Internal Feed

- eng/common/Scripts/MaestroHelpers.ps1
> fix: url typo

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.4 stable

- build/CopyFilesToStagingDir.ps1
- build/NuSpecs/AppxManifest.xml
Add PackageManager info to Transport package (.winmd, manifested ACIDs)
Also, sort the info (was semi-sorted)
> Add PackageManager info to Transport package

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.4.1

- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
- eng/Version.Details.xml
- global.json
- installer/dev/install.cpp
Update global.json to use latest
Update yml to use global.json
Stop installing .NET 5 SDK
Fix warning for unused parameter.
> Update global.json to use latest

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.4.2

- build/WindowsAppSDK-SyncMirroredRepository.yml
> Include release/1.5-stable in Mirror Sync

- .config/tsaoptions.json
Updated area path in tsaoptions.json to cope with re-org changes.
---------
WARNING:
> Update area path in tsaoptions.json

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.4.3

- .config/tsaoptions.json
Updated tsaoptions.json
////////////
WARNING:
> Updated tsaoptions.json

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildTransportPackage-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-RunTestsInPipeline-Job.yml
- build/ProjectReunion-BuildFoundation.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
This will help us streamlines the process of updating our TestMatrix across all branches
> Use Centralized Test Configuration to Define Test Matrix

- build/WindowsAppSDK-Foundation-Nightly.yml
Fix Variables Field Being Defined Twice in Nightly Yml Template
> Fix Variables Field Being Defined Twice in Nightly Yml Template

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.4.4 and 1.5-exp1

- build/WindowsAppSDK-CommonVariables.yml
> Setup Branch for preview1 

- build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
- eng/common/DevCheck.ps1
New DevCheck option -ShowSystemInfo
> DevCheck: -ShowSystemInfo

- dev/Common/IsWindowsVersion.h
- test/DynamicDependency/Test_Win32/DynamicDependency_Test_Win32.vcxproj
- test/DynamicDependency/Test_Win32/Test_Win32.cpp
- test/DynamicDependency/Test_Win32/Test_Win32.h
- test/DynamicDependency/Test_Win32/pch.h
- test/DynamicDependency/Test_WinRT/DynamicDependency_Test_WinRT.vcxproj
- test/DynamicDependency/Test_WinRT/Test_WinRT.cpp
- test/DynamicDependency/Test_WinRT/Test_WinRT.h
- test/DynamicDependency/Test_WinRT/pch.h
- test/inc/WindowsAppRuntime.Test.TAEF.h
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/4083
> [Cherrypick] 48525090 - Skipping a test case to temporarily avoid hitting this bug 

- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-arm64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x64.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/Properties/PublishProfiles/win-x86.pubxml
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/Properties/PublishProfiles/win-x86.pubxml
> fix whitespace to resolve branch differences

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.5-exp2

- build/WindowsAppSDK-CommonVariables.yml
> Switch branch to preview

- dev/Common/AppModel.Identity.h
- installer/dev/console.cpp
- installer/dev/tracelogging.h
These set of changes are flagged by PreFast static analysis tool. Fixing for that.
> PreFast compliance fixes - Installer

- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
The TerminalVelocity Features were added but the header files were not being run. Adding to the Setup script.
> Run Generate-TerminalVelocity for PackageManager

- build/WindowsAppSDK-CommonVariables.yml
> Setup branch for Stable releases

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.5-preview1

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.4.5

- dev/MRTCore/mrt/Core/src/MRM.cpp
#fixes https://github.com/microsoft/WindowsAppSDK/issues/4191
> missing space for null terminator on baseDir

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.5.0

- specs/packagemanager/PackageManagement.md
Add Is*ReadyOrNewerAvailable() and EnsureReadyOptions.RegisterNewerIfAvailable=boolean
https://task.ms/48914090
> PackageDeploymentManager.IsReadyOrNewerAvailable() API spec

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.5.1

- docs/pull_request_template.md
> Update PR Template MD to warn about PullRequests on Forks

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildTransportPackage-Stage.yml
- eng/common/AzurePipelinesTemplates/WindowsAppSDK-BuildSetup-Steps.yml
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/4316
> Remove ProjectReunionInternal Service Connection in NuGetAuthenticate task

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.5.2

- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
- build/WindowsAppSDK-CommonVariables.yml
- eng/common/Scripts/PublishPublicSymbols.ps1
Cherrypick of 
https://github.com/microsoft/WindowsAppSDK/pull/4311
and bringing in eng/common/Scripts/PublishPublicSymbols.ps1
https://github.com/microsoft/WindowsAppSDK/pull/4262/files#diff-e2d4ac1dba1a98a35a8d203b46ee5a5a9ce082b0d42b4af1d2f5a906e4c5560c
> Add SymbolsArtifactName to PublishPDBs and Remove Task to Publish Symbols Publicly

- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
> add condition to prevent disk scanning

- dev/VSIX/Extension/Cpp/Dev17/NuGetPackageList.cs
- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
- dev/VSIX/Extension/Cpp/Dev17/WizardImplementationCpp.cs
- dev/VSIX/Extension/Cs/Dev17/WizardImplementation.cs
- dev/VSIX/Extension/Directory.Build.targets
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/WinUI.Desktop.Cs.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WapProj/WinUI.Desktop.Cs.WapProj.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/BlankApp/WinUI.Desktop.CppWinRT.BlankApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WapProjTemplate.wapproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WapProj/WinUI.Desktop.CppWinRT.WapProj.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.vstemplate
Contains commits
1. https://github.com/microsoft/WindowsAppSDK/pull/4344
2. https://github.com/microsoft/WindowsAppSDK/pull/4347 
3. https://github.com/microsoft/WindowsAppSDK/pull/4339
4. https://github.com/microsoft/WindowsAppSDK/pull/4322
>  Implement Selected Improvements for C++ and C# Support in the Windows App SDK Projects.

- dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.vstemplate
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.vstemplate
This change removes package references to C++ item template classes and adds the NuGetInstaller to the C# class library.
> Completing addition of Nuget Installation Wizard to all .vstemplate files

- dev/Deployment/DeploymentManager.cpp
- dev/UndockedRegFreeWinRT/typeresolution.cpp
> Fix Prefast C6101 on Foundation Solution 

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.5.3

- build/WindowsAppSDK-SyncMirroredRepository.yml
> Setup release/1.6 branch to sync to the internal mirror 

- build/WindowsAppSDK-Versions.yml
> Update MinorVersion to 7

- docs/Coding-Guidelines/GettingStarted.md
- eng/common/DevCheck.ps1
Update GettingStarted docs with winget tip to install the RS5 SDK
Enhance DevCheck to explicitly check for the Windows 10.0.17763.0 (RS5) SDK as VS won't.
Fix some global variable references in DevCheck
> Improve GettingStarted docs. DevCheck verify RS5 SDK.

- docs/faq.md
> Removing UWP reference

- Directory.Build.props
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/projection/Microsoft.Windows.ApplicationModel.Resources.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppLifecycle/Microsoft.Windows.AppLifecycle.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppNotifications.Builder.Projection/Microsoft.Windows.AppNotifications.Builder.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppNotifications.Projection/Microsoft.Windows.AppNotifications.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.ApplicationModel.DynamicDependency/Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.ApplicationModel.WindowsAppRuntime/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.Management.Deployment.Projection/Microsoft.Windows.Management.Deployment.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.PushNotifications.Projection/Microsoft.Windows.PushNotifications.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.Security.AccessControl.Projection/Microsoft.Windows.Security.AccessControl.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.System.Power/Microsoft.Windows.System.Power.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.System/Microsoft.Windows.System.Projection.csproj
- eng/Version.Details.xml
- tools/ProjectTemplates/dev.cs.dll.projection/PurojekutoTenpuret.Projection.csproj
> Update version of CsWinRT and Windows SDK projection

- Directory.Build.props
- dev/MRTCore/mrt/Microsoft.Windows.ApplicationModel.Resources/projection/Microsoft.Windows.ApplicationModel.Resources.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppLifecycle/Microsoft.Windows.AppLifecycle.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppNotifications.Builder.Projection/Microsoft.Windows.AppNotifications.Builder.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.AppNotifications.Projection/Microsoft.Windows.AppNotifications.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.ApplicationModel.DynamicDependency/Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.ApplicationModel.WindowsAppRuntime/Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.Management.Deployment.Projection/Microsoft.Windows.Management.Deployment.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.PushNotifications.Projection/Microsoft.Windows.PushNotifications.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.Security.AccessControl.Projection/Microsoft.Windows.Security.AccessControl.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.System.Power/Microsoft.Windows.System.Power.Projection.csproj
- dev/Projections/CS/Microsoft.Windows.System/Microsoft.Windows.System.Projection.csproj
- dev/Projections/Directory.Build.props
- eng/Version.Details.xml
- eng/common/VersionInfo/AssemblyInfo.cs
- eng/common/VersionInfo/GenerateVersionInfo.ps1
- tools/ProjectTemplates/dev.cs.dll.projection/PurojekutoTenpuret.Projection.csproj
Update CsWinRT version
---------
WARNING:
> [release/1.6-stable] Update version of CsWinRT and Windows SDK projection (#4427)

- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/4458
> Remove condition for develop and main branch on versioning and always add $(PipelineType) to the tag

- build/ProjectReunion-BuildFoundation.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/4481
> Remove unused variable group: PublicSymbols-Secrets

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.5.4

- specs/packagemanager/PackageManagement.md
API spec for IsProvisioned overloads
- IsPackageProvisioned
- IsPackageProvisionedByUri
- IsPackageSetProvisioned
> Package Management: Is Provisioned API spec

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.6-exp2

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-AnyCPU-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-PackNuget-Steps.yml
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/4499
> Update ESRPCodeSigningTask to Version 5; Use WindowsAppSDK-EsrpCodeSigning-Steps.yml From WindowsAppSDKConfig Repository

- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
> Disable Maestro Publishing

- dev/VSIX/Extension/Cpp/Dev17/WindowsAppSDK.Cpp.Extension.Dev17.csproj
- dev/VSIX/Extension/Cs/Dev17/WindowsAppSDK.Cs.Extension.Dev17.csproj
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/4554
> Override System.Text.Json version to work around false positive CVE-2024-30105

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Stage.yml
This will allow the stages to be turned off on the allowing us to unblock the build easily
> Installer and VSIX validation stages condition on LatestOfficialBuildID variable

- build/WindowsAppSDK-CommonVariables.yml
- eng/Version.Details.xml
From 
https://microsoft.visualstudio.com/DefaultCollection/LiftedIXP/_build/results?buildId=103537475&view=results
This pull request updates the dependencies for the project to the latest versions from the microsoft/LiftedIXP/DCPP repository.
- Updated `Microsoft.FrameworkUdk` dependency version and SHA in `/eng/Version.Details.xml`.
> [release/1.6-stable] Update dependencies from microsoft/LiftedIXP/DCPP and Update Channel to Preview

- eng/Version.Details.xml
Update AppLicensing to 1.6.0-preview1.20240726.0
> [release/1.6-stable] Update dependencies from microsoft/ProjectReunion/WindowsAppSDKClosed

- eng/Version.Details.xml
Update IXP to 1.6.4-CI-26107.1007.240806-0649.0
> [release/1.6-stable] Update dependencies from DCPP and AppLicensing

- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
* Add AppData Terminal Velocity call to yml
* fix namespace
Cherry-pick of 6a0b9dcf278e67147e5ac3ae1961853a87c36209
WARNING:
> [main] Add AppData Terminal Velocity call to yml (#4619)

- eng/Version.Details.xml
> Update AppLicensing to 1.7.0-main.20240611.0

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.5.6 and 1.6-preview1

- Directory.Build.props
- eng/Version.Details.xml
> Update CsWinRT version to stable versions

- build/WindowsAppSDK-CommonVariables.yml
> Update Channel to stable

- Directory.Build.props
- eng/Version.Details.xml
- global.json
> update versions for 1.6 stable

- eng/Version.Details.xml
> fix dotnet versions in Versions.Details.xml

- eng/Version.Details.xml
> [1.6] Update dependencies from WinAppSDKClosed

- eng/Version.Details.xml
> update dependencies from WinAppSDKClosed, DCPP

- dev/ApplicationData/M.W.S.ApplicationData.cpp
- specs/applicationdata/ApplicationData.md
- test/ApplicationData/ApplicationDataTests.cpp
cherry-pick [Fix ApplicationData.MachineFolder path](https://github.com/microsoft/WindowsAppSDK/pull/4664#top) #4664 
https://github.com/microsoft/WindowsAppSDK/pull/4664
> 1.6 Fix ApplicationData.MachineFolder path

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.6-preview2

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
> Binlogs for Installer and VSIX

- build/CopyFilesToStagingDir.ps1
- build/NuSpecs/WindowsAppSDK-Nuget-Native.C.props
> [1.6] NETSDK1206 Fix

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.6.0

- .github/policies/resourceManagement.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-Build-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-AnyCPU-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildBinaries-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildMRT-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-BuildVSIX-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-PackTransportPackage-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-Publish-Stage.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
- build/ProjectReunion-BuildFoundation.yml
- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
- build/WindowsAppSDK-Foundation-PR.yml
> .yml cleanup: lower true and false

- eng/Version.Details.xml
Update to latest 1.5 LiftedIXP and WindowsAppSDKClosed.
> [release/1.5-stable] Update dependencies from LiftedIXP and WindowsAppSDKClosed

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.6.1

- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.vstemplate
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/WinUI.Desktop.CppWinRT.UnitTestApp.vstemplate
Visual Studio team recommends this naming standard
> Change default project name to UnitTestApp

- Directory.Packages.props
> Update System.Text.Json to 8.0.5

- build/AzurePipelinesTemplates/WindowsAppSDK-BuildInstaller-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-RunTests-Steps.yml
- build/AzurePipelinesTemplates/WindowsAppSDK-SetupBuildEnvironment-Steps.yml
- tools/DevCheck/DevCheck.ps1
> Automatically generate password to avoid using Convert-To-SecureString

- build/NuSpecs/AppxManifest.xml
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/4863
> Removing UniversalBGTask Activation class entry from framework manifest

- eng/Version.Details.xml
> [release/1.7-stable] Update dependencies from microsoft/LiftedIXP/DCPP

- .github/ISSUE_TEMPLATE/bug-report.yaml
> Update bug-report.yaml for 1.6.2

- dev/Interop/StoragePicker/FileOpenPicker.cpp
- dev/Interop/StoragePicker/FileOpenPicker.h
- dev/Interop/StoragePicker/StoragePickersTelemetry.h
Add one telemetry for FileOpenPicker.PickerSingleFileAsync
> Add one telemetry for FileOpenPicker.PickerSingleFileAsync

- build/scripts/Install-WindowsSdkISO.ps1
> Update Install-WindowsSdkISO.ps1 to use new FW links

- build/scripts/Install-WindowsSdkISO.ps1
> Update Install-WindowsSdkISO.ps1 to use new FW links (#5020)

- dev/WindowsAppRuntime_UniversalBGTaskDLL/Task.idl
- dev/WindowsAppRuntime_UniversalBGTaskDLL/WindowsAppRuntime_UniversalBGTaskDLL.vcxproj
- dev/WindowsAppRuntime_UniversalBGTaskDLL/WindowsAppRuntime_UniversalBGTaskDLL.vcxproj.filters
- dev/WindowsAppRuntime_UniversalBGTaskDLL/pch.h
- Adding contract for UniversalBGTask to avoid build warnings
- Removing unnecessary references and headers
> Adding contract for UniversalBGTask

- test/CameraCaptureUITests/APITests.cpp
- test/CameraCaptureUITests/CameraCaptureUI.testdef
- test/CameraCaptureUITests/CameraCaptureUITests.vcxproj
The changes involve onboarding unit tests for the CameraCaptureUI API to run as part of the pipeline test runs (Checkin, Nightly, and Release).
https://task.ms/55988368
> CameraCaptureUI: Onboarding Unit tests to the pipeline test runs

- Directory.Packages.props
- dev/WindowsAppRuntime_DLL/packages.config
- test/CameraCaptureUITests/packages.config
- test/OAuth2ManagerTests/packages.config
- test/PackageManager/API/packages.config
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/5091
> Adding IXP & FrameworkUDK to Central Package Management

- build/WindowsAppSDK-CommonVariables.yml
> Set Channel to Preview

- dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUI.idl
- test/CameraCaptureUITests/APITests.cpp
> [1.7] Removing terminal velocity (#5070)

- dev/BackgroundTask/BackgroundTaskBuilder/BackgroundTaskBuilder.idl
Cleaning up TerminalVelocity usage from IDL as well to fix build issues on preview channel
> Removed TerminalVelocity usages from IDL

- test/PackageManager/API/PackageDeploymentManagerTests_EnsureReady_RegisterNewerIfAvailable.cpp
Couple of tests running elevated but didn't need elevation
> PackageDeploymentManager: Some tests running elevated but didn't need elevation

- dev/Common/TerminalVelocityFeatures-OAuth.xml
> [OAuth2Manager] Remove velocity tags added due to conflict resolution

- dev/Interop/StoragePickers/FileSavePicker.cpp
- dev/Interop/StoragePickers/PickerCommon.cpp
- dev/Interop/StoragePickers/PickerCommon.h
Autoapply the first extion in FiletypeChoices when the extension's not defined.
> FileSavePicker - Autoapply the first extion in FiletypeChoices when the extension's not defined.

- dev/Interop/CameraCaptureUI/CameraCaptureUI/CameraCaptureUITelemetry.h
Cherry-pick of #5100 
https://task.ms/56142429
> [Cherry-pick to 1.7] Making CameraCapture Telemetry Critical (#5100)

- .github/ISSUE_TEMPLATE/bug-report.yaml
WASDK-BugTemplate Update
WARNING:
> WASDK-BugTemplate Update

- dev/Common/StoragePickersTelemetryHelper.h
- dev/Interop/StoragePickers/FileOpenPicker.cpp
- dev/Interop/StoragePickers/FileOpenPicker.h
- dev/Interop/StoragePickers/FileSavePicker.cpp
- dev/Interop/StoragePickers/FileSavePicker.h
- dev/Interop/StoragePickers/FolderPicker.cpp
- dev/Interop/StoragePickers/FolderPicker.h
- dev/Interop/StoragePickers/StoragePickersTelemetry.h
Add telemetries for the storage pickers.
> Add telemetry

- dev/PackageManager/API/M.W.M.D.PackageDeploymentManager.cpp
> PackageDeploymentManager - Add missing .Stop() event on CompletedSuccess

- dev/RuntimeCompatibilityOptions/RuntimeCompatibilityOptions.idl
Add RuntimeCompatibilityChange values for the containable upcoming 1.7.1 changes.
> Add 1.7.1 RuntimeCompatibilityChange values

- dev/MRTCore/mrt/mrm/UnitTests/DecisionInfo.UnitTests.cpp
- dev/MRTCore/mrt/mrm/UnitTests/testUtils.cpp
- dev/MRTCore/mrt/mrm/mrmmin/DecisionInfoBuilder.cpp
> Fix some type mismatch issues in MRT

- build/WindowsAppSDK-TDBuild.yml
Cheery pick https://github.com/microsoft/WindowsAppSDK/pull/5337 from main to 1.8.
/////////////////////////////////
WARNING:
> [CP to 1.8] Task 57156413: [SFI][GetSecure] Vulnerability Management - Redeploy With Updated Code References - 4 issues in MMS2019

- build/WindowsAppSDK-TDBuild.yml
Cheery pick https://github.com/microsoft/WindowsAppSDK/pull/5337 from main to 1.7.
/////////////////////////////////
WARNING:
> [CP to 1.7] Task 57156413: [SFI][GetSecure] Vulnerability Management - Redeploy With Updated Code References - 4 issues in MMS2019

- build/WindowsAppSDK-TDBuild.yml
Cheery pick https://github.com/microsoft/WindowsAppSDK/pull/5337 from main to 1.6.
/////////////////////////////////
WARNING:
> [CP to 1.6] Task 57156413: [SFI][GetSecure] Vulnerability Management - Redeploy With Updated Code References - 4 issues in MMS2019 

- eng/Version.Details.xml
> Update FrUdk for agg pipeline coherency

- dev/VSIX/Directory.Build.props
> Update BuildTools version for BuildTools.MSIX refactor

- dev/RuntimeCompatibilityOptions/RuntimeCompatibilityOptions.idl
Add RuntimeCompatibilityChange values for the containable upcoming 1.7.2 changes.
> Add 1.7.2 RuntimeCompatibilityChange values

- build/scripts/CreateInstallerOverrideHeader.ps1
- build/scripts/ExtractMSIXFromNuget.ps1
> add strictMode for 2 files

- dev/VSIX/ItemTemplates/Desktop/CSharp/BlankWindow/WinUI.Desktop.Cs.BlankWindow.csproj
- dev/VSIX/ItemTemplates/Desktop/CppWinRT/BlankWindow/WinUI.Desktop.CppWinRT.BlankWindow.csproj
- dev/VSIX/ItemTemplates/Neutral/CSharp/BlankPage/WinUI.Neutral.Cs.BlankPage.csproj
- dev/VSIX/ItemTemplates/Neutral/CSharp/ResourceDictionary/WinUI.Neutral.Cs.ResourceDictionary.csproj
- dev/VSIX/ItemTemplates/Neutral/CSharp/Resw/WinUI.Neutral.Cs.Resw.csproj
- dev/VSIX/ItemTemplates/Neutral/CSharp/TemplatedControl/WinUI.Neutral.Cs.TemplatedControl.csproj
- dev/VSIX/ItemTemplates/Neutral/CSharp/UserControl/WinUI.Neutral.Cs.UserControl.csproj
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/BlankPage/WinUI.Neutral.CppWinRT.BlankPage.csproj
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/ResourceDictionary/WinUI.Neutral.CppWinRT.ResourceDictionary.csproj
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/Resw/WinUI.Neutral.CppWinRT.Resw.csproj
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/TemplatedControl/WinUI.Neutral.CppWinRT.TemplatedControl.csproj
- dev/VSIX/ItemTemplates/Neutral/CppWinRT/UserControl/WinUI.Neutral.CppWinRT.UserControl.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/WinUI.Desktop.Cs.SingleProjectPackagedApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CSharp/UnitTestApp/WinUI.Desktop.Cs.UnitTestApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/SingleProjectPackagedApp/WinUI.Desktop.CppWinRT.SingleProjectPackagedApp.csproj
- dev/VSIX/ProjectTemplates/Desktop/CppWinRT/UnitTestApp/WinUI.Desktop.CppWinRT.UnitTestApp.csproj
- dev/VSIX/ProjectTemplates/Neutral/CppWinRT/RuntimeComponent/WinUI.Neutral.CppWinRT.RuntimeComponent.csproj
Specifying the tag ChecksumAlgorithm as SHA256
> Specifying the tag ChecksumAlgorithm as SHA256

- dev/Deployment/DeploymentManager.cpp
- installer/dev/install.cpp
> Changes for https://github.com/microsoft/WindowsAppSDK/pull/5540/files

- dev/Deployment/DeploymentTracelogging.cpp
- dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapTracelogging.cpp
Adding missing privacy labels and critical tags.
> Compliance for Deployment and Boostrapper Insights

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/policies/resourceManagement.yml
> Fix FeedbackHub trigger

- dev/Interop/StoragePickers/Strings/StoragePickers.resw
The error message of storage pickers.
> The error message of storage pickers

- build/WindowsAppSDK-Foundation-Nightly.yml
- build/WindowsAppSDK-Foundation-Official.yml
> Update Nightly and Official for PR5615

- dev/Interop/StoragePickers/Strings/ko-KR/StoragePickers.resw
- dev/Interop/StoragePickers/Strings/tr-TR/StoragePickers.resw
- dev/Interop/StoragePickers/Strings/zh-CN/StoragePickers.resw
Add new localized resources for storage pickers (complete)
> Add new localized resources for storage pickers (complete)

- build/WindowsAppSDK-CommonVariables.yml
> update release channel to preview

- build/NuSpecs/WindowsAppSDK-Nuget-Native.AutoInitializer.targets
- build/NuSpecs/WindowsAppSDK-Nuget-Native.Bootstrap.targets
This reverts commit 6549492b11a86ae54bd4b86daceb753beb53e410.
WARNING:
> Revert "fix: MSB8027, two or more files with the same name (#5597)"

- dev/Interop/StoragePickers/FileSavePicker.cpp
- dev/Interop/StoragePickers/FileSavePicker.h
- dev/Interop/StoragePickers/Microsoft.Windows.Storage.Pickers.idl
- dev/Interop/StoragePickers/PickerCommon.cpp
- dev/Interop/StoragePickers/PickerCommon.h
- test/StoragePickersTests/PickerCommonTests.cpp
- test/StoragePickersTests/StoragePickersTests.cpp
It is decided during the official view (#5634) to add a new property: `FileSavePicker.SuggestedFolder`
This PR is its implementation.
> FileSavePicker.SuggestedFolder

- build/CopyFilesToStagingDir.ps1
- build/NuSpecs/package.appxfragment
- build/scripts/windows-sdk.ps1
Missed a couple of edits in the previous PR
NOTE: Change made by finding all BadgeNotifications in build\* and adding equivalent
> Fix Decimal missing winmds

- build/WindowsAppSDK-CommonVariables.yml
> Update build channel for 1.8 stable release

- build/AzurePipelinesTemplates/WindowsAppSDK-StaticValidationTest-Stage.yml
Cherrypick of https://github.com/microsoft/WindowsAppSDK/pull/5790
> Update StaticValidationTests to use 26100 SDK

- dev/RuntimeCompatibilityOptions/RuntimeCompatibilityOptions.idl
> Add 1.7.4 runtime compatibility enums

- eng/Version.Details.xml
[build](https://dev.azure.com/microsoft/LiftedIXP/_build/results?buildId=130021024&view=logs&j=d6a3dd77-c558-5164-418c-1ca6160619f5&t=a2c987b1-a0c5-524c-cea6-84129f92c7ee)
> [release/2.0-stable] Update dependencies from microsoft/LiftedIXP/DCPP
